// Package f3548 is the generated HTTP surface of ASTM F3548-21 (UTM USS interoperability)
// (docs/PLAN.md D3): server.gen.go is the strict server of the
// USS-side operations this USSP serves, client.gen.go the client
// (StdClient, StdClientWithResponses) of the DSS operations and the peer
// USS operations it calls. Both are generated by oapi-codegen from the
// pinned copy api/standards/f3548-v21.yaml through
// api/standards/oapi-codegen.f3548.{server,client}.yaml and are never edited
// by hand (scripts/check-generated.sh regenerates and diffs them).
//
// The wire types are not generated here: they are
// github.com/rootxkit/uspace-core/f3548, which core generated from the same
// file at the same commit, and the generated files dot-import that
// package. Code outside this package converts between the wire and the
// validated core values only in internal/stdapi/convert.
//
// The client's base URL is the DSS's (/dss/v1) or a peer's
// uss_base_url; nothing here names a host.
package f3548
