//go:build go1.22

// Package f3548 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package f3548

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	. "github.com/rootxkit/uspace-core/f3548"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// NotifyConstraintDetailsChanged Notify a peer USS of changed constraint details.
	// (POST /uss/v1/constraints)
	NotifyConstraintDetailsChanged(w http.ResponseWriter, r *http.Request)
	// GetConstraintDetails Retrieve the specified constraint details from a USS.
	// (GET /uss/v1/constraints/{entityid})
	GetConstraintDetails(w http.ResponseWriter, r *http.Request, entityid EntityID)
	// GetLogSet Get USS logs
	// (GET /uss/v1/log_sets/{log_set_id})
	GetLogSet(w http.ResponseWriter, r *http.Request, logSetId string)
	// NotifyOperationalIntentDetailsChanged Notify a peer USS of changed operational intent details.
	// (POST /uss/v1/operational_intents)
	NotifyOperationalIntentDetailsChanged(w http.ResponseWriter, r *http.Request)
	// GetOperationalIntentDetails Retrieve the specified operational intent details from a USS.
	// (GET /uss/v1/operational_intents/{entityid})
	GetOperationalIntentDetails(w http.ResponseWriter, r *http.Request, entityid EntityID, params GetOperationalIntentDetailsParams)
	// GetOperationalIntentTelemetry Query detailed information on the position of an off-nominal operational intent from a USS.
	// (GET /uss/v1/operational_intents/{entityid}/telemetry)
	GetOperationalIntentTelemetry(w http.ResponseWriter, r *http.Request, entityid EntityID)
	// MakeUssReport Notify USS of an error encountered that might otherwise go unnoticed.
	// (POST /uss/v1/reports)
	MakeUssReport(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// NotifyConstraintDetailsChanged operation middleware
func (siw *ServerInterfaceWrapper) NotifyConstraintDetailsChanged(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NotifyConstraintDetailsChanged(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConstraintDetails operation middleware
func (siw *ServerInterfaceWrapper) GetConstraintDetails(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entityid" -------------
	var entityid EntityID

	err = runtime.BindStyledParameterWithOptions("simple", "entityid", r.PathValue("entityid"), &entityid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConstraintDetails(w, r, entityid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLogSet operation middleware
func (siw *ServerInterfaceWrapper) GetLogSet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "log_set_id" -------------
	var logSetId string

	err = runtime.BindStyledParameterWithOptions("simple", "log_set_id", r.PathValue("log_set_id"), &logSetId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "log_set_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLogSet(w, r, logSetId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// NotifyOperationalIntentDetailsChanged operation middleware
func (siw *ServerInterfaceWrapper) NotifyOperationalIntentDetailsChanged(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NotifyOperationalIntentDetailsChanged(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperationalIntentDetails operation middleware
func (siw *ServerInterfaceWrapper) GetOperationalIntentDetails(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entityid" -------------
	var entityid EntityID

	err = runtime.BindStyledParameterWithOptions("simple", "entityid", r.PathValue("entityid"), &entityid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityid", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetOperationalIntentDetailsParams

	// ------------- Optional query parameter "version" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "version", r.URL.Query(), &params.Version, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "version"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperationalIntentDetails(w, r, entityid, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetOperationalIntentTelemetry operation middleware
func (siw *ServerInterfaceWrapper) GetOperationalIntentTelemetry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "entityid" -------------
	var entityid EntityID

	err = runtime.BindStyledParameterWithOptions("simple", "entityid", r.PathValue("entityid"), &entityid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entityid", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetOperationalIntentTelemetry(w, r, entityid)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// MakeUssReport operation middleware
func (siw *ServerInterfaceWrapper) MakeUssReport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.MakeUssReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/uss/v1/operational_intents/{entityid}", wrapper.GetOperationalIntentDetails)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/uss/v1/operational_intents/{entityid}/telemetry", wrapper.GetOperationalIntentTelemetry)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/uss/v1/operational_intents", wrapper.NotifyOperationalIntentDetailsChanged)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/uss/v1/constraints/{entityid}", wrapper.GetConstraintDetails)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/uss/v1/constraints", wrapper.NotifyConstraintDetailsChanged)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/uss/v1/reports", wrapper.MakeUssReport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/uss/v1/log_sets/{log_set_id}", wrapper.GetLogSet)

	return m
}

type NotifyConstraintDetailsChangedRequestObject struct {
	Body *NotifyConstraintDetailsChangedJSONRequestBody
}

type NotifyConstraintDetailsChangedResponseObject interface {
	VisitNotifyConstraintDetailsChangedResponse(w http.ResponseWriter) error
}

type NotifyConstraintDetailsChanged204Response struct {
}

func (response NotifyConstraintDetailsChanged204Response) VisitNotifyConstraintDetailsChangedResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type NotifyConstraintDetailsChanged400JSONResponse ErrorResponse

func (response NotifyConstraintDetailsChanged400JSONResponse) VisitNotifyConstraintDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyConstraintDetailsChanged401JSONResponse ErrorResponse

func (response NotifyConstraintDetailsChanged401JSONResponse) VisitNotifyConstraintDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyConstraintDetailsChanged403JSONResponse ErrorResponse

func (response NotifyConstraintDetailsChanged403JSONResponse) VisitNotifyConstraintDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyConstraintDetailsChanged409JSONResponse ErrorResponse

func (response NotifyConstraintDetailsChanged409JSONResponse) VisitNotifyConstraintDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyConstraintDetailsChanged429JSONResponse ErrorResponse

func (response NotifyConstraintDetailsChanged429JSONResponse) VisitNotifyConstraintDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetConstraintDetailsRequestObject struct {
	Entityid EntityID `json:"entityid"`
}

type GetConstraintDetailsResponseObject interface {
	VisitGetConstraintDetailsResponse(w http.ResponseWriter) error
}

type GetConstraintDetails200JSONResponse GetConstraintDetailsResponse

func (response GetConstraintDetails200JSONResponse) VisitGetConstraintDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetConstraintDetails400JSONResponse ErrorResponse

func (response GetConstraintDetails400JSONResponse) VisitGetConstraintDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetConstraintDetails401JSONResponse ErrorResponse

func (response GetConstraintDetails401JSONResponse) VisitGetConstraintDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetConstraintDetails403JSONResponse ErrorResponse

func (response GetConstraintDetails403JSONResponse) VisitGetConstraintDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetConstraintDetails404JSONResponse ErrorResponse

func (response GetConstraintDetails404JSONResponse) VisitGetConstraintDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetConstraintDetails429JSONResponse ErrorResponse

func (response GetConstraintDetails429JSONResponse) VisitGetConstraintDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetLogSetRequestObject struct {
	LogSetId string `json:"log_set_id"`
}

type GetLogSetResponseObject interface {
	VisitGetLogSetResponse(w http.ResponseWriter) error
}

type GetLogSet200JSONResponse USSLogSet

func (response GetLogSet200JSONResponse) VisitGetLogSetResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyOperationalIntentDetailsChangedRequestObject struct {
	Body *NotifyOperationalIntentDetailsChangedJSONRequestBody
}

type NotifyOperationalIntentDetailsChangedResponseObject interface {
	VisitNotifyOperationalIntentDetailsChangedResponse(w http.ResponseWriter) error
}

type NotifyOperationalIntentDetailsChanged204Response struct {
}

func (response NotifyOperationalIntentDetailsChanged204Response) VisitNotifyOperationalIntentDetailsChangedResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type NotifyOperationalIntentDetailsChanged400JSONResponse ErrorResponse

func (response NotifyOperationalIntentDetailsChanged400JSONResponse) VisitNotifyOperationalIntentDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyOperationalIntentDetailsChanged401JSONResponse ErrorResponse

func (response NotifyOperationalIntentDetailsChanged401JSONResponse) VisitNotifyOperationalIntentDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyOperationalIntentDetailsChanged403JSONResponse ErrorResponse

func (response NotifyOperationalIntentDetailsChanged403JSONResponse) VisitNotifyOperationalIntentDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyOperationalIntentDetailsChanged409JSONResponse ErrorResponse

func (response NotifyOperationalIntentDetailsChanged409JSONResponse) VisitNotifyOperationalIntentDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type NotifyOperationalIntentDetailsChanged429JSONResponse ErrorResponse

func (response NotifyOperationalIntentDetailsChanged429JSONResponse) VisitNotifyOperationalIntentDetailsChangedResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentDetailsRequestObject struct {
	Entityid EntityID `json:"entityid"`
	Params   GetOperationalIntentDetailsParams
}

type GetOperationalIntentDetailsResponseObject interface {
	VisitGetOperationalIntentDetailsResponse(w http.ResponseWriter) error
}

type GetOperationalIntentDetails200JSONResponse GetOperationalIntentDetailsResponse

func (response GetOperationalIntentDetails200JSONResponse) VisitGetOperationalIntentDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentDetails400JSONResponse ErrorResponse

func (response GetOperationalIntentDetails400JSONResponse) VisitGetOperationalIntentDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentDetails401JSONResponse ErrorResponse

func (response GetOperationalIntentDetails401JSONResponse) VisitGetOperationalIntentDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentDetails403JSONResponse ErrorResponse

func (response GetOperationalIntentDetails403JSONResponse) VisitGetOperationalIntentDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentDetails404JSONResponse ErrorResponse

func (response GetOperationalIntentDetails404JSONResponse) VisitGetOperationalIntentDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentDetails429JSONResponse ErrorResponse

func (response GetOperationalIntentDetails429JSONResponse) VisitGetOperationalIntentDetailsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentTelemetryRequestObject struct {
	Entityid EntityID `json:"entityid"`
}

type GetOperationalIntentTelemetryResponseObject interface {
	VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error
}

type GetOperationalIntentTelemetry200JSONResponse GetOperationalIntentTelemetryResponse

func (response GetOperationalIntentTelemetry200JSONResponse) VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentTelemetry400JSONResponse ErrorResponse

func (response GetOperationalIntentTelemetry400JSONResponse) VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentTelemetry401JSONResponse ErrorResponse

func (response GetOperationalIntentTelemetry401JSONResponse) VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentTelemetry403JSONResponse ErrorResponse

func (response GetOperationalIntentTelemetry403JSONResponse) VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentTelemetry404JSONResponse ErrorResponse

func (response GetOperationalIntentTelemetry404JSONResponse) VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentTelemetry409JSONResponse ErrorResponse

func (response GetOperationalIntentTelemetry409JSONResponse) VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentTelemetry412JSONResponse ErrorResponse

func (response GetOperationalIntentTelemetry412JSONResponse) VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(412)
	_, err := buf.WriteTo(w)
	return err
}

type GetOperationalIntentTelemetry429JSONResponse ErrorResponse

func (response GetOperationalIntentTelemetry429JSONResponse) VisitGetOperationalIntentTelemetryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type MakeUssReportRequestObject struct {
	Body *MakeUssReportJSONRequestBody
}

type MakeUssReportResponseObject interface {
	VisitMakeUssReportResponse(w http.ResponseWriter) error
}

type MakeUssReport201JSONResponse ErrorReport

func (response MakeUssReport201JSONResponse) VisitMakeUssReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type MakeUssReport400JSONResponse ErrorResponse

func (response MakeUssReport400JSONResponse) VisitMakeUssReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type MakeUssReport401JSONResponse ErrorResponse

func (response MakeUssReport401JSONResponse) VisitMakeUssReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type MakeUssReport403JSONResponse ErrorResponse

func (response MakeUssReport403JSONResponse) VisitMakeUssReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type MakeUssReport429JSONResponse ErrorResponse

func (response MakeUssReport429JSONResponse) VisitMakeUssReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// NotifyConstraintDetailsChanged Notify a peer USS of changed constraint details.
	// (POST /uss/v1/constraints)
	NotifyConstraintDetailsChanged(ctx context.Context, request NotifyConstraintDetailsChangedRequestObject) (NotifyConstraintDetailsChangedResponseObject, error)
	// GetConstraintDetails Retrieve the specified constraint details from a USS.
	// (GET /uss/v1/constraints/{entityid})
	GetConstraintDetails(ctx context.Context, request GetConstraintDetailsRequestObject) (GetConstraintDetailsResponseObject, error)
	// GetLogSet Get USS logs
	// (GET /uss/v1/log_sets/{log_set_id})
	GetLogSet(ctx context.Context, request GetLogSetRequestObject) (GetLogSetResponseObject, error)
	// NotifyOperationalIntentDetailsChanged Notify a peer USS of changed operational intent details.
	// (POST /uss/v1/operational_intents)
	NotifyOperationalIntentDetailsChanged(ctx context.Context, request NotifyOperationalIntentDetailsChangedRequestObject) (NotifyOperationalIntentDetailsChangedResponseObject, error)
	// GetOperationalIntentDetails Retrieve the specified operational intent details from a USS.
	// (GET /uss/v1/operational_intents/{entityid})
	GetOperationalIntentDetails(ctx context.Context, request GetOperationalIntentDetailsRequestObject) (GetOperationalIntentDetailsResponseObject, error)
	// GetOperationalIntentTelemetry Query detailed information on the position of an off-nominal operational intent from a USS.
	// (GET /uss/v1/operational_intents/{entityid}/telemetry)
	GetOperationalIntentTelemetry(ctx context.Context, request GetOperationalIntentTelemetryRequestObject) (GetOperationalIntentTelemetryResponseObject, error)
	// MakeUssReport Notify USS of an error encountered that might otherwise go unnoticed.
	// (POST /uss/v1/reports)
	MakeUssReport(ctx context.Context, request MakeUssReportRequestObject) (MakeUssReportResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// NotifyConstraintDetailsChanged operation middleware
func (sh *strictHandler) NotifyConstraintDetailsChanged(w http.ResponseWriter, r *http.Request) {
	var request NotifyConstraintDetailsChangedRequestObject

	var body NotifyConstraintDetailsChangedJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NotifyConstraintDetailsChanged(ctx, request.(NotifyConstraintDetailsChangedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NotifyConstraintDetailsChanged")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NotifyConstraintDetailsChangedResponseObject); ok {
		if err := validResponse.VisitNotifyConstraintDetailsChangedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetConstraintDetails operation middleware
func (sh *strictHandler) GetConstraintDetails(w http.ResponseWriter, r *http.Request, entityid EntityID) {
	var request GetConstraintDetailsRequestObject

	request.Entityid = entityid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetConstraintDetails(ctx, request.(GetConstraintDetailsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetConstraintDetails")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetConstraintDetailsResponseObject); ok {
		if err := validResponse.VisitGetConstraintDetailsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetLogSet operation middleware
func (sh *strictHandler) GetLogSet(w http.ResponseWriter, r *http.Request, logSetId string) {
	var request GetLogSetRequestObject

	request.LogSetId = logSetId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetLogSet(ctx, request.(GetLogSetRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetLogSet")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetLogSetResponseObject); ok {
		if err := validResponse.VisitGetLogSetResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// NotifyOperationalIntentDetailsChanged operation middleware
func (sh *strictHandler) NotifyOperationalIntentDetailsChanged(w http.ResponseWriter, r *http.Request) {
	var request NotifyOperationalIntentDetailsChangedRequestObject

	var body NotifyOperationalIntentDetailsChangedJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NotifyOperationalIntentDetailsChanged(ctx, request.(NotifyOperationalIntentDetailsChangedRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NotifyOperationalIntentDetailsChanged")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NotifyOperationalIntentDetailsChangedResponseObject); ok {
		if err := validResponse.VisitNotifyOperationalIntentDetailsChangedResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperationalIntentDetails operation middleware
func (sh *strictHandler) GetOperationalIntentDetails(w http.ResponseWriter, r *http.Request, entityid EntityID, params GetOperationalIntentDetailsParams) {
	var request GetOperationalIntentDetailsRequestObject

	request.Entityid = entityid
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperationalIntentDetails(ctx, request.(GetOperationalIntentDetailsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperationalIntentDetails")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationalIntentDetailsResponseObject); ok {
		if err := validResponse.VisitGetOperationalIntentDetailsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetOperationalIntentTelemetry operation middleware
func (sh *strictHandler) GetOperationalIntentTelemetry(w http.ResponseWriter, r *http.Request, entityid EntityID) {
	var request GetOperationalIntentTelemetryRequestObject

	request.Entityid = entityid

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetOperationalIntentTelemetry(ctx, request.(GetOperationalIntentTelemetryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOperationalIntentTelemetry")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetOperationalIntentTelemetryResponseObject); ok {
		if err := validResponse.VisitGetOperationalIntentTelemetryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// MakeUssReport operation middleware
func (sh *strictHandler) MakeUssReport(w http.ResponseWriter, r *http.Request) {
	var request MakeUssReportRequestObject

	var body MakeUssReportJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.MakeUssReport(ctx, request.(MakeUssReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "MakeUssReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(MakeUssReportResponseObject); ok {
		if err := validResponse.VisitMakeUssReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
