// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package timeseries

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BroadcastTrack struct {
	UasID        string      `json:"uas_id"`
	CapturedAt   time.Time   `json:"captured_at"`
	Ts           time.Time   `json:"ts"`
	RxTs         time.Time   `json:"rx_ts"`
	Geom         interface{} `json:"geom"`
	AltPressureM *float64    `json:"alt_pressure_m"`
	AltWgs84M    *float64    `json:"alt_wgs84_m"`
	HeightM      *float64    `json:"height_m"`
	HeightRef    *string     `json:"height_ref"`
	SpeedMs      *float64    `json:"speed_ms"`
	TrackDeg     *float64    `json:"track_deg"`
	VspeedMs     *float64    `json:"vspeed_ms"`
	Trust        string      `json:"trust"`
	ReceiverID   string      `json:"receiver_id"`
	Cell5        string      `json:"cell5"`
}

type ConformanceSample struct {
	FlightID         pgtype.UUID `json:"flight_id"`
	CapturedAt       time.Time   `json:"captured_at"`
	State            string      `json:"state"`
	DistanceOutsideM *float64    `json:"distance_outside_m"`
	HeightOverM      *float64    `json:"height_over_m"`
	MsgID            *string     `json:"msg_id"`
}

type EconspicuityTrack struct {
	Icao24       string      `json:"icao24"`
	Callsign     *string     `json:"callsign"`
	CapturedAt   time.Time   `json:"captured_at"`
	Ts           *time.Time  `json:"ts"`
	RxTs         time.Time   `json:"rx_ts"`
	Geom         interface{} `json:"geom"`
	AltPressureM *float64    `json:"alt_pressure_m"`
	AltWgs84M    *float64    `json:"alt_wgs84_m"`
	GsMs         *float64    `json:"gs_ms"`
	TrackDeg     *float64    `json:"track_deg"`
	VrateMs      *float64    `json:"vrate_ms"`
	Emergency    *string     `json:"emergency"`
	SourceClass  string      `json:"source_class"`
	Quality      *string     `json:"quality"`
	AdapterID    string      `json:"adapter_id"`
	Trust        string      `json:"trust"`
	ReceiverID   string      `json:"receiver_id"`
	Cell5        string      `json:"cell5"`
	MsgID        *string     `json:"msg_id"`
}

type MannedTrack struct {
	Icao24       string      `json:"icao24"`
	Callsign     *string     `json:"callsign"`
	CapturedAt   time.Time   `json:"captured_at"`
	Ts           *time.Time  `json:"ts"`
	RxTs         time.Time   `json:"rx_ts"`
	Geom         interface{} `json:"geom"`
	AltPressureM *float64    `json:"alt_pressure_m"`
	AltWgs84M    *float64    `json:"alt_wgs84_m"`
	GsMs         *float64    `json:"gs_ms"`
	TrackDeg     *float64    `json:"track_deg"`
	VrateMs      *float64    `json:"vrate_ms"`
	Emergency    *string     `json:"emergency"`
	SourceClass  string      `json:"source_class"`
	Quality      *string     `json:"quality"`
	AdapterID    string      `json:"adapter_id"`
	Trust        string      `json:"trust"`
	Cell5        string      `json:"cell5"`
	MsgID        *string     `json:"msg_id"`
}

type PeerFlight struct {
	PeerUss     string    `json:"peer_uss"`
	RidFlightID string    `json:"rid_flight_id"`
	RxTs        time.Time `json:"rx_ts"`
	State       []byte    `json:"state"`
	Details     []byte    `json:"details"`
	IsaID       *string   `json:"isa_id"`
	Cell5       *string   `json:"cell5"`
	MsgID       *string   `json:"msg_id"`
}

type Telemetry struct {
	FlightID           pgtype.UUID `json:"flight_id"`
	CapturedAt         time.Time   `json:"captured_at"`
	Ts                 *time.Time  `json:"ts"`
	RxTs               time.Time   `json:"rx_ts"`
	Backlog            bool        `json:"backlog"`
	TimeSource         string      `json:"time_source"`
	Geom               interface{} `json:"geom"`
	AltWgs84M          *float64    `json:"alt_wgs84_m"`
	AltAmslM           *float64    `json:"alt_amsl_m"`
	UndulationM        *float64    `json:"undulation_m"`
	AltPressureM       *float64    `json:"alt_pressure_m"`
	HeightM            *float64    `json:"height_m"`
	HeightRef          *string     `json:"height_ref"`
	SpeedMs            *float64    `json:"speed_ms"`
	TrackDeg           *float64    `json:"track_deg"`
	VspeedMs           *float64    `json:"vspeed_ms"`
	Status             *string     `json:"status"`
	Emergency          bool        `json:"emergency"`
	OperatorPosition   interface{} `json:"operator_position"`
	AccuracyH          *string     `json:"accuracy_h"`
	AccuracyV          *string     `json:"accuracy_v"`
	TimestampAccuracyS *float64    `json:"timestamp_accuracy_s"`
	SourceClientID     *string     `json:"source_client_id"`
	Cell5              string      `json:"cell5"`
	MsgID              *string     `json:"msg_id"`
	AccuracyHM         *float64    `json:"accuracy_h_m"`
	AccuracyVM         *float64    `json:"accuracy_v_m"`
}

type TrafficProduct struct {
	ClientID      string      `json:"client_id"`
	At            time.Time   `json:"at"`
	IntentID      pgtype.UUID `json:"intent_id"`
	Bbox          interface{} `json:"bbox"`
	TracksShown   []byte      `json:"tracks_shown"`
	Degraded      []string    `json:"degraded"`
	PolicyVersion int64       `json:"policy_version"`
	MsgID         *string     `json:"msg_id"`
}

type WriterGap struct {
	DedupeKey string     `json:"dedupe_key"`
	Stream    string     `json:"stream"`
	Subject   string     `json:"subject"`
	FromSeq   int64      `json:"from_seq"`
	ToSeq     int64      `json:"to_seq"`
	Cause     string     `json:"cause"`
	Count     int64      `json:"count"`
	CountUnit string     `json:"count_unit"`
	AfterAt   *time.Time `json:"after_at"`
	BeforeAt  *time.Time `json:"before_at"`
	Detail    string     `json:"detail"`
	At        time.Time  `json:"at"`
}

type WriterPosition struct {
	Stream string    `json:"stream"`
	Seq    int64     `json:"seq"`
	At     time.Time `json:"at"`
}
