/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description 200 while the process runs. Says nothing about dependencies.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Runs every dependency check of the process and reports each with
         *     its state, since when, how long ago it was last seen up, and why
         *     it is not up. 503 while a required dependency is down or has not
         *     been checked; 200 otherwise, with every dependency that is not up
         *     listed in degraded. A check that did not run is "unknown", never
         *     "up".
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The ecosystem-wide error body (RFC 9457), the shape of
         *     uspace-lab schemas/common/problem/v1, mirrored here until that
         *     schema is published (reconciliation M28).
         */
        Problem: {
            /**
             * Format: uri
             * @description https://schemas.uspace.ge/problems/<slug>, the slug being the counter or refusal name.
             * @example https://schemas.uspace.ge/problems/not_found
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description The request path. */
            instance?: string;
            /** @description Field problems, at most 100; truncated says when more existed. */
            errors?: components["schemas"]["FieldProblem"][];
            truncated?: boolean;
        };
        FieldProblem: {
            /** @description The JSON path or parameter name at fault. */
            field: string;
            reason: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Readiness: {
            /**
             * @description not_ready while a required dependency is down or unknown; degraded while any dependency is not up.
             * @enum {string}
             */
            status: "ready" | "degraded" | "not_ready";
            /** Format: date-time */
            checked_at: string;
            /** @description Every dependency of the process, by name (postgres, timescaledb, nats). */
            dependencies: {
                [key: string]: components["schemas"]["Dependency"];
            };
            /** @description The names of the dependencies that are not up, sorted. */
            degraded: string[];
        };
        Dependency: {
            /** @enum {string} */
            state: "up" | "degraded" | "down" | "unknown";
            /** @description Whether the process is not ready while this dependency is down or unknown. */
            required: boolean;
            /**
             * Format: date-time
             * @description When the dependency entered its current state.
             */
            since: string;
            /**
             * Format: double
             * @description Seconds since the dependency was last seen up; 0 while it is up, absent when it never was.
             */
            age_s?: number;
            /** @description Why the dependency is not up; absent while it is. */
            detail?: string;
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready; degraded lists what is not up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Not ready; a required dependency is down or unknown. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
}
