/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description 200 while the process runs. Says nothing about dependencies.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Runs every dependency check of the process and reports each with
         *     its state, since when, how long ago it was last seen up, and why
         *     it is not up. 503 while a required dependency is down or has not
         *     been checked; 200 otherwise, with every dependency that is not up
         *     listed in degraded. A check that did not run is "unknown", never
         *     "up".
         */
        get: operations["getReadyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cis/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Receive a CIS change notification (F3 push)
         * @description The receiver of every subscriber in the ecosystem (M1): the CISP
         *     POSTs here the callback it registered, and the ANSP posts here
         *     on its degraded direct path while the CISP is down (M5). The body
         *     is a compact JWS (application/jose) whose payload is {iss, aud,
         *     sub, iat, jti, body}: iss one of USSP_CIS_NOTIFY_ISSUERS (each
         *     verified against its JWKS), aud this host (M19), sub the
         *     subscription (the restriction id from the ANSP), jti the
         *     delivery id, iat at most 5 minutes old, and body the
         *     cis/change/v1 record of the CISP's pinned schema. There is no
         *     bearer: the signature authenticates the sender.
         *
         *     A delivery id seen before is acknowledged 204 and not acted on
         *     (it is remembered in the database on every replica). The
         *     reasons subscription_test and republished, and any reason this
         *     USSP does not know, are acknowledged 204 without a pull (M16).
         *     Every other reason is logged and triggers a pull of the dataset:
         *     from pull_url when its host is the issuer's configured base host
         *     (and the issuer is the CISP), otherwise from the configured CISP
         *     base URL, the mismatch counted (the SSRF guard). The answer does
         *     not wait for the pull.
         */
        post: operations["receiveCISNotification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Validity of an operator, a UAS and a remote pilot (F8, cached)
         * @description The authority's F8 answer through this USSP's cache, status only:
         *     `valid`, `suspended`, `revoked` or `unknown` per key asked, with
         *     the end of validity, the class label and MTOM band of a UAS and
         *     the competency set of a pilot, never a name, address, phone or
         *     e-mail (spec 02 F8, 06 §5). An answer cached within the policy's
         *     TTL (`registry_positive_ttl_s`, `registry_negative_ttl_s`) carries
         *     its `cache_age_s`; otherwise the authority is asked and the answer
         *     cached. When the authority cannot answer, a key without a cached
         *     answer is `unknown` with `reason: registry_unavailable` (or
         *     `registry_answer_refused` when its answer was refused), never an
         *     error and never `valid`. `operator` is compared on its public part
         *     (a secret part is neither sent, stored nor echoed); `serial` as
         *     given, trimmed. Every call is an `events` row
         *     (`registry_validated`) with the client and the purpose.
         */
        get: operations["validateRegistry"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/intents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The operator's intents, newest first
         * @description At most 500; from and to keep the intents whose window overlaps them; state filters.
         */
        get: operations["listIntents"];
        put?: never;
        /**
         * File an operational intent and get the authorisation decision
         * @description Decides an intent/request/v1 (2021/664 Art. 6(4), 10) in the order of brief WP-7: the registry (F8, purpose authorisation), the CIS cache (stale or known outdated refuses; U-space airspace and its Art. 3(4) constraints; zones and ANSP restrictions, Art. 10(7)), strategic deconfliction against the authorised intents of this USSP and the peers' intents (priority, then first come first served, Art. 10(8), (9)), then the DSS, the deviation thresholds and the authorisation number (Art. 10(11)). A missing, stale or untrusted input refuses or holds; it never authorises. An open A1 flight with a C0 or privately built UA below 250 g is accepted voluntarily without a number (Art. 1(3)). A refusal is a decision (201) whose conflicts[] name the Annex IV item, zone, airspace, restriction, intent or registry key; a request that does not carry the items is 400 annex_iv_invalid. Idempotent on (client, client_ref): the same body answers the decision as it stands (200), another body 409. The UAS serial must be bound to the client and operator_reg must be the client's operator (403). 503 names the dependency that is missing (geoid_unavailable, database_unavailable, projection_unavailable).
         */
        post: operations["createIntent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/intents/{intent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intent_id: components["parameters"]["IntentID"];
            };
            cookie?: never;
        };
        /**
         * One of the operator's intents: its decision and state
         * @description Another operator's intent is 404, never 403.
         */
        get: operations["getIntent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Activate, modify or end an intent
         * @description activate: an accepted intent from time_start - policy.activation_lead_s to time_end, on the database clock, confirmed in the response (Art. 10(5)); modify: an accepted intent's new volumes decided as a new version that keeps the id and, when still authorised, the authorisation number (Art. 6(6)); a modification that is not authorised leaves the intent in its new decision's state without a number; end: any open intent. A transition the state does not allow is 409.
         */
        patch: operations["changeIntent"];
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Client credentials grant for operator machine clients
         * @description RFC 6749 §4.4 client credentials at this USSP's own issuer (D9).
         *     The client authenticates with HTTP Basic (`client_secret_basic`)
         *     or with `client_id` and `client_secret` in the body
         *     (`client_secret_post`), never both; the secret is checked with
         *     argon2id in constant time, and during a rotation the previous
         *     secret is accepted until its overlap ends
         *     (`policy.client_secret_overlap_s`). Parameters in the query
         *     string are refused. `scope` names operator scopes (`ussp.intents`,
         *     `ussp.telemetry`, `ussp.traffic`, `ussp.geo`); an unknown scope is
         *     refused; the token grants the requested scopes that the client
         *     holds (all of them when `scope` is absent). `audience`, when
         *     given, must be this USSP's host: `aud` is always this USSP's host
         *     (M18). The TTL is `policy.operator_token_ttl_s` (at most 3600 s).
         *     Issuance is rate-limited per client and per client address (429
         *     with `Retry-After`). Every issuance and refusal is an `events`
         *     row. Errors carry the RFC 6749 §5.2 `error` beside the problem
         *     members.
         */
        post: operations["requestToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The issuer's public keys
         * @description The RS256 keys of this USSP's issuer (`use: sig`, `kid` = the RFC
         *     7638 SHA-256 thumbprint): the current key and, during a rotation,
         *     the previous one (`USSP_ISSUER_PREVIOUS_KEY_FILE`). Operator
         *     tokens and session tokens are signed by the current key.
         */
        get: operations["getJWKS"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a portal or console session
         * @description Checks a username and password (argon2id) in the realm `portal`
         *     (operator users) or `console` (staff); a staff `admin` also sends
         *     a TOTP code. An unknown user, a wrong password and a wrong code
         *     are one answer. Ten consecutive failures for one username lock it
         *     for 15 minutes (the lock is in the database and holds across
         *     replicas; 429 with `Retry-After`); attempts are also limited per
         *     client address. On success the answer carries the session JWT
         *     (`iss` = this issuer, `aud` = this host, `sub` = the account id,
         *     `scope = "session"`, `roles`, `realm`, `jti` = the session id,
         *     `exp` at most 12 h, idle end after 30 min) and sets the cookies
         *     `uspace_session` and `uspace_csrf` (`HttpOnly; Secure;
         *     SameSite=Strict`). A request authenticated by the cookie sends the
         *     `uspace_csrf` value as `X-CSRF-Token` on every method that is not
         *     GET, HEAD or OPTIONS. Every attempt is an `events` row.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End the caller's session
         * @description Revokes the session (its `jti`) and clears both cookies.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's account and session */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Self-registration of a UAS operator
         * @description Creates the USSP's customer record of an operator registered with
         *     the authority, and its first portal user with the role
         *     `operator_admin`. The registration number is checked with the
         *     authority's registry (F8): the operator is `active` once the
         *     registry says `valid`, `pending_validation` while it says
         *     `unknown` or cannot be asked, and refused when it says anything
         *     else. No client may be created and no token issued before the
         *     operator is `active`. Rate-limited per client address.
         */
        post: operations["registerOperator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/operators/{operator_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
            };
            cookie?: never;
        };
        /**
         * The caller's operator
         * @description Portal session of an `operator_admin` of this operator.
         */
        get: operations["getOperator"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change the operator's record
         * @description Changes the display name and the contact email. An operator still
         *     `pending_validation` is checked with the registry again.
         */
        patch: operations["updateOperator"];
        trace?: never;
    };
    "/v1/accounts/operators/{operator_id}/clients": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a machine client of the operator
         * @description A client-credentials client with operator scopes, for an `active`
         *     operator. The secret is in this answer only; it is stored as an
         *     argon2id hash. The creation is an `events` row, which is the
         *     operator's notification for now (06 T3).
         */
        post: operations["createClient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/operators/{operator_id}/clients/{client_id}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
                client_id: components["parameters"]["ClientID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a client's secret
         * @description A new secret, shown once. The previous one keeps working until
         *     `previous_valid_until` (`policy.client_secret_overlap_s` from
         *     now) and never after.
         */
        post: operations["rotateClientSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/operators/{operator_id}/clients/{client_id}/serials": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
                client_id: components["parameters"]["ClientID"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bind a UAS serial number to a client
         * @description A client sends telemetry only for its bound serials (06 T3). The
         *     serial is validated by uspace-core `serial.ValidateForClass` with
         *     `class_label` and compared by `serial.FoldKey`; a serial bound to
         *     another client is refused (409). The binding is projected to KV `client_bindings`
         *     in the same transaction; when the projection cannot take it,
         *     nothing changes (503).
         */
        post: operations["bindSerial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/accounts/operators/{operator_id}/clients/{client_id}/serials/{serial}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
                client_id: components["parameters"]["ClientID"];
                serial: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unbind a serial from a client */
        delete: operations["unbindSerial"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The ecosystem-wide error body (RFC 9457), the shape of
         *     uspace-lab schemas/common/problem/v1, mirrored here until that
         *     schema is published (reconciliation M28).
         */
        Problem: {
            /**
             * Format: uri
             * @description https://schemas.uspace.ge/problems/<slug>, the slug being the counter or refusal name.
             * @example https://schemas.uspace.ge/problems/not_found
             */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description The request path. */
            instance?: string;
            /** @description Field problems, at most 100; truncated says when more existed. */
            errors?: components["schemas"]["FieldProblem"][];
            truncated?: boolean;
        };
        FieldProblem: {
            /** @description The JSON path or parameter name at fault. */
            field: string;
            reason: string;
        };
        /**
         * @description Why the lookup is made; recorded on every call here and at the authority (spec 02 F8).
         * @enum {string}
         */
        RegistryPurpose: "authorisation" | "identification";
        /** @enum {string} */
        RegistryStatus: "valid" | "suspended" | "revoked" | "unknown";
        RegistryCompetency: {
            competency: string;
            /** Format: date-time */
            valid_until: string;
        };
        /** @description One entity's answer, status only. */
        RegistryAnswer: {
            /** @description The key as answered (an operator number's public part, the serial, the pilot id). */
            key: string;
            status: components["schemas"]["RegistryStatus"];
            /**
             * @description Why the status is unknown without the registry having said so; absent when it did.
             * @enum {string}
             */
            reason?: "registry_unavailable" | "registry_answer_refused";
            /**
             * Format: date-time
             * @description The registration's end of validity (an operator's), as the authority answers it.
             */
            valid_until?: string;
            class_label?: string;
            mtom_band?: string;
            competencies?: components["schemas"]["RegistryCompetency"][];
            /**
             * Format: double
             * @description The age of the answer in seconds (0 when the authority was just asked); absent when there is no answer.
             */
            cache_age_s?: number;
        };
        /** @description One part per key asked. */
        RegistryValidation: {
            operator?: components["schemas"]["RegistryAnswer"];
            uas?: components["schemas"]["RegistryAnswer"];
            pilot?: components["schemas"]["RegistryAnswer"];
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        Readiness: {
            /**
             * @description not_ready while a required dependency is down or unknown; degraded while any dependency is not up.
             * @enum {string}
             */
            status: "ready" | "degraded" | "not_ready";
            /** Format: date-time */
            checked_at: string;
            /** @description Every dependency of the process, by name (postgres, timescaledb, nats). */
            dependencies: {
                [key: string]: components["schemas"]["Dependency"];
            };
            /** @description The names of the dependencies that are not up, sorted. */
            degraded: string[];
        };
        Dependency: {
            /** @enum {string} */
            state: "up" | "degraded" | "down" | "unknown";
            /** @description Whether the process is not ready while this dependency is down or unknown. */
            required: boolean;
            /**
             * Format: date-time
             * @description When the dependency entered its current state.
             */
            since: string;
            /**
             * Format: double
             * @description Seconds since the dependency was last seen up; 0 while it is up, absent when it never was.
             */
            age_s?: number;
            /** @description Why the dependency is not up; absent while it is. */
            detail?: string;
        };
        /**
         * @description A problem (M28) that also carries the RFC 6749 §5.2 members, so an
         *     OAuth2 client library reads `error` and a uspace client reads the
         *     problem.
         */
        OAuthProblem: components["schemas"]["Problem"] & {
            /** @enum {string} */
            error: "invalid_request" | "invalid_client" | "invalid_scope" | "invalid_target" | "unauthorized_client" | "unsupported_grant_type" | "temporarily_unavailable";
            error_description?: string;
        };
        TokenRequest: {
            /** @enum {string} */
            grant_type: "client_credentials";
            client_id?: string;
            client_secret?: string;
            /** @description Space-separated operator scopes. */
            scope?: string;
            /** @description When given, this USSP's host (M18). */
            audience?: string;
        };
        TokenResponse: {
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Seconds until exp. */
            expires_in: number;
            scope: string;
        };
        JWKS: {
            keys: {
                [key: string]: unknown;
            }[];
        };
        /**
         * @description portal for operator users, console for staff (M20).
         * @enum {string}
         */
        Realm: "portal" | "console";
        LoginRequest: {
            realm: components["schemas"]["Realm"];
            username: string;
            password: string;
            /** @description Six digits; required for a staff admin. */
            totp_code?: string;
        };
        Session: {
            /** @description The session JWT, also set as the uspace_session cookie; the BFF carries it as a bearer. */
            token: string;
            /** @description The uspace_csrf value, sent as X-CSRF-Token with a cookie-authenticated request. */
            csrf_token: string;
            account_id: string;
            realm: components["schemas"]["Realm"];
            roles: string[];
            /** @description The operator of a portal account. */
            operator_id?: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            idle_expires_at: string;
        };
        Me: {
            account_id: string;
            username: string;
            realm: components["schemas"]["Realm"];
            roles: string[];
            operator_id?: string;
            /** Format: date-time */
            session_expires_at: string;
        };
        /** @enum {string} */
        OperatorStatus: "pending_validation" | "active" | "refused";
        OperatorRegistration: {
            /** @description The operator registration number the authority issued. */
            registration_number: string;
            display_name: string;
            contact_email: string;
            admin_username: string;
            admin_password: string;
        };
        OperatorUpdate: {
            display_name?: string;
            contact_email?: string;
        };
        Operator: {
            id: string;
            registration_number: string;
            display_name: string;
            contact_email: string;
            status: components["schemas"]["OperatorStatus"];
            /** @description The registry's last answer (valid, unknown, or the refusal). */
            validation_status?: string;
            /** Format: date-time */
            validated_at?: string;
            /** Format: date-time */
            created_at: string;
        };
        /** @enum {string} */
        OperatorScope: "ussp.intents" | "ussp.telemetry" | "ussp.traffic" | "ussp.geo";
        ClientRequest: {
            scopes: components["schemas"]["OperatorScope"][];
        };
        ClientSecret: {
            client_id: string;
            /** @description Shown once; never stored in clear and never retrievable again. */
            client_secret: string;
            scopes: components["schemas"]["OperatorScope"][];
            status: string;
            /**
             * Format: date-time
             * @description Set by a rotation; the previous secret works until then.
             */
            previous_valid_until?: string;
        };
        SerialBindingRequest: {
            /** @description The UAS serial number (ANSI/CTA-2063-A). */
            serial: string;
            /**
             * @description The aircraft's class (2019/945). C1, C2, C3, C5 and C6 need a
             *     valid CTA-2063-A serial; C0, C4 and an unlabelled aircraft (no
             *     class_label) only a serial that is not empty (LESSONS G-06).
             * @enum {string}
             */
            class_label?: "C0" | "C1" | "C2" | "C3" | "C4" | "C5" | "C6";
        };
        SerialBinding: {
            client_id: string;
            serial: string;
            /** @description uspace-core serial.FoldKey of the serial. */
            serial_fold: string;
            /** Format: date-time */
            bound_at: string;
        };
        /** @description intent/request/v1 (schemas/intent/request/v1/schema.json, the source of truth): the ten Annex IV items numbered as in the Annex, the contingency measures, the emergency contact reference and the idempotency reference. */
        IntentRequest: {
            /** @description Idempotency reference, unique per client: the same body under it answers the same decision, another body is refused with 409. */
            client_ref: string;
            /** @description (1) Serial number of the UA or of its add-on (ANSI/CTA-2063-A where the class requires it). */
            uas_serial: string;
            /**
             * @description (2) Mode of operation.
             * @enum {unknown}
             */
            mode: "VLOS" | "BVLOS";
            /**
             * @description (3) Type of flight: a special operation per SERA Art. 4, or normal.
             * @enum {unknown}
             */
            flight_type: "normal" | "special_operation";
            /** @description (3) F3548 priority; when given it must equal the derived one: 0 for normal, the policy's special_operation_priority for special_operation. */
            priority?: number;
            /**
             * @description (4) Category of the operation.
             * @enum {unknown}
             */
            category: "open" | "specific" | "certified";
            /**
             * @description (4) Open subcategory.
             * @enum {unknown}
             */
            subcategory?: "A1" | "A2" | "A3";
            /**
             * @description (4) Class label of the UA.
             * @enum {unknown}
             */
            class_label?: "C0" | "C1" | "C2" | "C3" | "C4" | "C5" | "C6";
            /** @description (4) Type certificate (certified category). */
            type_certificate?: string;
            /** @description (4) The UA is privately built (Art. 1(3) with mtom_kg). */
            privately_built?: boolean;
            /** @description (4) Declared maximum take-off mass in kilograms. */
            mtom_kg?: number;
            /** @description (5) The 4D trajectory: F3548 Volume4D, every one with both times and both altitudes. */
            volumes: components["schemas"]["IntentVolume4D"][];
            /**
             * @description (6) Identification technology.
             * @enum {unknown}
             */
            identification_technology: "network" | "direct" | "both";
            /** @description (7) Connectivity methods. */
            connectivity_methods: string[];
            /** @description (8) Endurance in seconds; it must cover the window of the volumes. */
            endurance_s: number;
            /** @description (9) Procedure on loss of the command and control link. */
            loss_of_c2_procedure: string;
            /** @description (10) Operator registration number, public part only. */
            operator_reg: string;
            /** @description (10) UA registration number when applicable (required in the certified category). */
            ua_registration?: string;
            /** @description Remote pilot identifier for the registry check. */
            pilot_ref?: string;
            takeoff?: components["schemas"]["IntentPoint"];
            landing?: components["schemas"]["IntentPoint"];
            /** @description Contingency measures (Art. 6(8)). */
            contingency: {
                procedure: string;
                landing_sites?: components["schemas"]["IntentPoint"][];
            };
            /** @description Reference to the emergency contact (never the contact itself). */
            emergency_contact_ref: string;
            /** @description A specific-category authorisation from the authority: a zone requiring an authorisation becomes a condition instead of pending_authority. */
            authorisation_ref?: string;
        };
        IntentPoint: {
            lat: number;
            lng: number;
        };
        IntentTime: {
            /** Format: date-time */
            value: string;
            /** @constant */
            format: "RFC3339";
        };
        IntentAltitude: {
            value: number;
            /** @constant */
            reference: "W84";
            /** @constant */
            units: "M";
        };
        IntentVolume4D: {
            volume: {
                outline_polygon?: {
                    vertices: components["schemas"]["IntentPoint"][];
                };
                outline_circle?: {
                    center: components["schemas"]["IntentPoint"];
                    radius: {
                        value: number;
                        /** @constant */
                        units: "M";
                    };
                };
                altitude_lower: components["schemas"]["IntentAltitude"];
                altitude_upper: components["schemas"]["IntentAltitude"];
            } & (unknown | unknown);
            time_start: components["schemas"]["IntentTime"];
            time_end: components["schemas"]["IntentTime"];
        };
        /** @description intent/decision/v1 (schemas/intent/decision/v1/schema.json, the source of truth). */
        IntentDecision: {
            /** @description UUID, also the DSS entity id. */
            intent_id: string;
            version: number;
            client_ref: string;
            /** @enum {unknown} */
            decision: "authorised" | "accepted_voluntary" | "rejected" | "pending_validation" | "pending_authority" | "pending_dss";
            /** @enum {unknown} */
            state: "pending_validation" | "pending_dss" | "pending_authority" | "accepted" | "activated" | "nonconforming" | "contingent" | "ended" | "rejected" | "withdrawn";
            /**
             * @description F3548 state of the intent, null when it is not one the DSS holds.
             * @enum {unknown}
             */
            dss_state: "Accepted" | "Activated" | "Nonconforming" | "Contingent" | null;
            /** @description <USSP code>-<operator registration public part>-<ULID> (spec 03 §6); null unless authorised. */
            authorisation_number: string | null;
            exempt_art_1_3: boolean;
            in_uspace_airspace: boolean;
            uspace_airspace_ids: string[];
            priority: number;
            deviation_thresholds: null | {
                h_m: number;
                v_m: number;
                t_s: number;
            };
            /** @description Art. 10(4) proposal; none in v1. */
            alternative: null;
            conflicts: components["schemas"]["IntentConflict"][];
            conditions: {
                code: string;
                ref?: string;
                detail: string;
            }[];
            volumes_amsl: {
                lower_amsl_m: number;
                upper_amsl_m: number;
                undulation_m: number;
                lower_w84_m: number;
                upper_w84_m: number;
            }[];
            /** Format: date-time */
            valid_from: string;
            /** Format: date-time */
            valid_to: string;
            /** @description The CIS versions the decision rests on, one label per ED-318 dataset; null when the CIS was not consulted. */
            cis_version_checked: string | null;
            cis_age_s: number | null;
            /** Format: date-time */
            registry_checked_at: string | null;
            policy_version: number;
            /** @description Art. 10(3); null until weather (WP-16). */
            weather_checked_ref: string | null;
            change_reason: string | null;
            /** Format: date-time */
            decided_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        IntentConflict: {
            /** @enum {unknown} */
            kind: "annex_iv" | "registry" | "cis" | "airspace" | "zone" | "restriction" | "intent" | "policy" | "dss";
            reason: string;
            /** @enum {unknown} */
            effect: "rejects" | "holds" | "flags_other";
            ref?: string;
            /** @description The Annex IV item number, null when the conflict is not about one. */
            item: number | null;
            /** @description Index of our volume. */
            volume: number | null;
            overlap: null | {
                /** @description Horizontal separation, 0 when the outlines meet; null when not judged. */
                h_m: number | null;
                /** @description Vertical overlap in AMSL; null when a limit is not AMSL. */
                v_m: number | null;
                /** @description Common time in seconds. */
                t_s: number | null;
            };
            detail: string;
        };
        /** @description activate (confirmed in the response, Art. 10(5)), modify (new volumes re-decided as a new version, Art. 6(6)) or end. */
        IntentPatch: {
            /** @enum {unknown} */
            action: "activate" | "modify" | "end";
            /** @description Required for modify, refused otherwise. */
            volumes?: components["schemas"]["IntentVolume4D"][];
            change_reason?: string;
        };
        IntentList: {
            intents: components["schemas"]["IntentDecision"][];
        };
    };
    responses: {
        /** @description An error, as RFC 9457 problem details. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A refused token request (RFC 6749 §5.2 inside a problem). */
        OAuthError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["OAuthProblem"];
            };
        };
    };
    parameters: {
        OperatorID: string;
        ClientID: string;
        IntentID: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The process is running. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    getReadyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready; degraded lists what is not up. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /** @description Not ready; a required dependency is down or unknown. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    receiveCISNotification: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/jose": string;
            };
        };
        responses: {
            /** @description Accepted, acknowledged or a replay; nothing to return. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            415: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    validateRegistry: {
        parameters: {
            query: {
                purpose: components["schemas"]["RegistryPurpose"];
                operator?: string;
                serial?: string;
                pilot?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One part per key asked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegistryValidation"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    listIntents: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                state?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The intents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentList"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createIntent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentRequest"];
            };
        };
        responses: {
            /** @description The decision of an earlier request with the same client_ref and body. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentDecision"];
                };
            };
            /** @description Decided: authorised, accepted_voluntary, rejected or pending_*. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentDecision"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intent_id: components["parameters"]["IntentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The decision as it stands. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentDecision"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    changeIntent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                intent_id: components["parameters"]["IntentID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntentPatch"];
            };
        };
        responses: {
            /** @description The new version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntentDecision"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    requestToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description An operator machine token (cross-plan Appendix A). */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            400: components["responses"]["OAuthError"];
            401: components["responses"]["OAuthError"];
            /** @description The client's or the address's issuance budget is spent. */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["OAuthProblem"];
                };
            };
            503: components["responses"]["OAuthError"];
            default: components["responses"]["Problem"];
        };
    };
    getJWKS: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The JWKS. */
            200: {
                headers: {
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JWKS"];
                };
            };
            /** @description No issuer key is configured. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The session. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            /** @description The username is locked or the address's budget is spent. */
            429: {
                headers: {
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Problem"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The session is ended. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account behind the session. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            401: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    registerOperator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorRegistration"];
            };
        };
        responses: {
            /** @description The operator. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operator"];
                };
            };
            400: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    getOperator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The operator. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operator"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    updateOperator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorUpdate"];
            };
        };
        responses: {
            /** @description The operator. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operator"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    createClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientRequest"];
            };
        };
        responses: {
            /** @description The client and its secret, shown once. */
            201: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientSecret"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    rotateClientSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
                client_id: components["parameters"]["ClientID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The new secret. */
            200: {
                headers: {
                    "Cache-Control"?: "no-store";
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientSecret"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    bindSerial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
                client_id: components["parameters"]["ClientID"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SerialBindingRequest"];
            };
        };
        responses: {
            /** @description The binding. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SerialBinding"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
    unbindSerial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operator_id: components["parameters"]["OperatorID"];
                client_id: components["parameters"]["ClientID"];
                serial: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The serial is no longer bound to the client. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
            default: components["responses"]["Problem"];
        };
    };
}
