// Package authclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package authclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Defines values for OccurrenceCategory.
const (
	Airprox                    OccurrenceCategory = "airprox"
	Emergency                  OccurrenceCategory = "emergency"
	LostLinkInUspace           OccurrenceCategory = "lost_link_in_uspace"
	NonconformanceInProhibited OccurrenceCategory = "nonconformance_in_prohibited"
	Other                      OccurrenceCategory = "other"
)

// Valid indicates whether the value is a known member of the OccurrenceCategory enum.
func (e OccurrenceCategory) Valid() bool {
	switch e {
	case Airprox:
		return true
	case Emergency:
		return true
	case LostLinkInUspace:
		return true
	case NonconformanceInProhibited:
		return true
	case Other:
		return true
	default:
		return false
	}
}

// Defines values for OccurrenceChannel.
const (
	Mandatory OccurrenceChannel = "mandatory"
	Voluntary OccurrenceChannel = "voluntary"
)

// Valid indicates whether the value is a known member of the OccurrenceChannel enum.
func (e OccurrenceChannel) Valid() bool {
	switch e {
	case Mandatory:
		return true
	case Voluntary:
		return true
	default:
		return false
	}
}

// Defines values for OccurrenceReportSchema.
const (
	Occurrencev1 OccurrenceReportSchema = "occurrence/v1"
)

// Valid indicates whether the value is a known member of the OccurrenceReportSchema enum.
func (e OccurrenceReportSchema) Valid() bool {
	switch e {
	case Occurrencev1:
		return true
	default:
		return false
	}
}

// Defines values for OccurrenceState.
const (
	Analysed   OccurrenceState = "analysed"
	Classified OccurrenceState = "classified"
	Closed     OccurrenceState = "closed"
	Received   OccurrenceState = "received"
)

// Valid indicates whether the value is a known member of the OccurrenceState enum.
func (e OccurrenceState) Valid() bool {
	switch e {
	case Analysed:
		return true
	case Classified:
		return true
	case Closed:
		return true
	case Received:
		return true
	default:
		return false
	}
}

// Defines values for SourceType.
const (
	AnspFeed   SourceType = "ansp_feed"
	DirectRid  SourceType = "direct_rid"
	NetworkRid SourceType = "network_rid"
)

// Valid indicates whether the value is a known member of the SourceType enum.
func (e SourceType) Valid() bool {
	switch e {
	case AnspFeed:
		return true
	case DirectRid:
		return true
	case NetworkRid:
		return true
	default:
		return false
	}
}

// CertificateID defines model for CertificateID.
type CertificateID = string

// FieldProblem defines model for FieldProblem.
type FieldProblem struct {
	// Field JSON path or parameter name, as core.FieldError writes it.
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

// OccurrenceAircraftInput One UAS of the report. An operator registration's secret part is dropped, never stored.
type OccurrenceAircraftInput struct {
	AuthorisationNumber *string `json:"authorisation_number,omitempty"`
	FlightId            *string `json:"flight_id,omitempty"`
	OperatorReg         *string `json:"operator_reg,omitempty"`
	Serial              *string `json:"serial,omitempty"`
}

// OccurrenceCategory The 376/2014 Art. 4(1) class of the report (spec 04 §3.3; the UAS classes of 2015/1018 are unverified, Q9).
type OccurrenceCategory string

// OccurrenceChannel mandatory (376 Art. 4) or voluntary (Art. 5); an operator's report (2019/947 Art. 19(2)) is mandatory.
type OccurrenceChannel string

// OccurrenceManned One manned aircraft of the report.
type OccurrenceManned struct {
	Callsign *string `json:"callsign,omitempty"`
	Icao24   *string `json:"icao24,omitempty"`
}

// OccurrenceReceipt The acknowledgement of a report. It holds no reporter identity.
type OccurrenceReceipt struct {
	// OccurrenceId The authority's id of the report (ULID).
	OccurrenceId string `json:"occurrence_id"`

	// ReceivedAt The authority's database clock at intake.
	ReceivedAt time.Time `json:"received_at"`

	// Replayed True when this answers a report received before.
	Replayed  bool            `json:"replayed"`
	ReportRef string          `json:"report_ref"`
	State     OccurrenceState `json:"state"`

	// Within72h Received within the reporting deadline after became_aware_at; false: late, accepted and flagged.
	Within72h bool `json:"within_72h"`
}

// OccurrenceReport `occurrence/v1` (spec 04 §3.3), the request body of POST
// /v1/occurrences; schemas/occurrence/v1.json is the same shape
// with examples. Members this version does not know are ignored
// (02 §1).
type OccurrenceReport struct {
	Aircraft *[]OccurrenceAircraftInput `json:"aircraft,omitempty"`

	// BecameAwareAt When the reporter became aware; the 72 h of 376 Art. 4(7)-(8) run from it.
	BecameAwareAt time.Time `json:"became_aware_at"`

	// Category The 376/2014 Art. 4(1) class of the report (spec 04 §3.3; the UAS classes of 2015/1018 are unverified, Q9).
	Category OccurrenceCategory `json:"category"`

	// Channel mandatory (376 Art. 4) or voluntary (Art. 5); an operator's report (2019/947 Art. 19(2)) is mandatory.
	Channel      OccurrenceChannel   `json:"channel"`
	EvidenceUrls *[]string           `json:"evidence_urls,omitempty"`
	IntentRefs   *[]string           `json:"intent_refs,omitempty"`
	Manned       *[]OccurrenceManned `json:"manned,omitempty"`

	// MinSeparation The minimum separation observed, in metres (horizontal, vertical) and when.
	MinSeparation *OccurrenceSeparation `json:"min_separation,omitempty"`

	// Narrative At most 20000 bytes of UTF-8.
	Narrative  *string   `json:"narrative,omitempty"`
	OccurredAt time.Time `json:"occurred_at"`

	// ReportRef The sender's reference: with the sender, the idempotency key.
	ReportRef string `json:"report_ref"`

	// ReportedAt When the sender recorded the report.
	ReportedAt *time.Time `json:"reported_at,omitempty"`

	// Reporter Who reports. `org` is informational: the authority records the
	// token's `sub`. `person_ref` is the reporter's opaque reference
	// in the sender's system, sent in clear over TLS (M13) and sealed
	// at rest here; it is shown to incident officers only and never
	// exported (376 Art. 16).
	Reporter *OccurrenceReporterInput `json:"reporter,omitempty"`
	Schema   OccurrenceReportSchema   `json:"schema"`
}

// OccurrenceReportSchema defines model for OccurrenceReport.Schema.
type OccurrenceReportSchema string

// OccurrenceReporterInput Who reports. `org` is informational: the authority records the
// token's `sub`. `person_ref` is the reporter's opaque reference
// in the sender's system, sent in clear over TLS (M13) and sealed
// at rest here; it is shown to incident officers only and never
// exported (376 Art. 16).
type OccurrenceReporterInput struct {
	Org       *string `json:"org,omitempty"`
	PersonRef *string `json:"person_ref,omitempty"`
}

// OccurrenceSeparation The minimum separation observed, in metres (horizontal, vertical) and when.
type OccurrenceSeparation struct {
	At *time.Time `json:"at,omitempty"`
	HM *float64   `json:"h_m,omitempty"`
	VM *float64   `json:"v_m,omitempty"`
}

// OccurrenceState defines model for OccurrenceState.
type OccurrenceState string

// Problem RFC 9457 problem details with the field-error extension of
// decision M28; the shape of uspace-lab `schemas/common/problem/v1`.
// `errors` is capped at 100 entries; `truncated` is true when it
// was cut.
type Problem struct {
	Detail    *string        `json:"detail,omitempty"`
	Errors    []FieldProblem `json:"errors"`
	Instance  *string        `json:"instance,omitempty"`
	Status    int            `json:"status"`
	Title     string         `json:"title"`
	Truncated *bool          `json:"truncated,omitempty"`

	// Type `https://schemas.uspace.ge/problems/<slug>`, slug = the counter or refusal name.
	Type string `json:"type"`
}

// SourceType The adapter type (04 §2 `source`), one per adapter process.
type SourceType string

// CreateOccurrenceJSONRequestBody defines body for CreateOccurrence for application/json ContentType.
type CreateOccurrenceJSONRequestBody = OccurrenceReport

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// CreateOccurrenceWithBody Report an occurrence (occurrence/v1; USSPs, the ANSP)
	//
	// The body is `occurrence/v1` (schemas/occurrence/v1.json, owned
	// here, M14). The sender is the token's `sub`, recorded as
	// `reporter_org` (a `reporter.org` that differs is ignored and
	// counted). Idempotent on (`reporter_org`, `report_ref`): the same
	// report again answers 200 with the id given first; another
	// report under the same reference is 409 `report_ref_conflict`.
	// A report received more than the reporting deadline (72 h,
	// `OCCURRENCES_REPORT_DEADLINE_S`) after `became_aware_at` is
	// accepted with `within_72h: false`, never refused. A
	// `became_aware_at` ahead of the database clock by more than the
	// allowed skew, or before `occurred_at`, is 400. A
	// `reporter.person_ref` is stored sealed under the occurrence key;
	// without that key configured such a report is 503
	// `occurrence_key_unavailable` (retry later), never stored in
	// clear. Operator aircraft keep the registration number's public
	// part only. Recorded with an `occurrence_received` events row
	// that holds no reporter identity.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/occurrences (the `CreateOccurrence` operationId).
	CreateOccurrenceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateOccurrence Report an occurrence (occurrence/v1; USSPs, the ANSP)
	//
	// The body is `occurrence/v1` (schemas/occurrence/v1.json, owned
	// here, M14). The sender is the token's `sub`, recorded as
	// `reporter_org` (a `reporter.org` that differs is ignored and
	// counted). Idempotent on (`reporter_org`, `report_ref`): the same
	// report again answers 200 with the id given first; another
	// report under the same reference is 409 `report_ref_conflict`.
	// A report received more than the reporting deadline (72 h,
	// `OCCURRENCES_REPORT_DEADLINE_S`) after `became_aware_at` is
	// accepted with `within_72h: false`, never refused. A
	// `became_aware_at` ahead of the database clock by more than the
	// allowed skew, or before `occurred_at`, is 400. A
	// `reporter.person_ref` is stored sealed under the occurrence key;
	// without that key configured such a report is 503
	// `occurrence_key_unavailable` (retry later), never stored in
	// clear. Operator aircraft keep the registration number's public
	// part only. Recorded with an `occurrence_received` events row
	// that holds no reporter identity.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/occurrences (the `CreateOccurrence` operationId).
	CreateOccurrence(ctx context.Context, body CreateOccurrenceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// CreateOccurrenceWithBody Report an occurrence (occurrence/v1; USSPs, the ANSP)
//
// The body is `occurrence/v1` (schemas/occurrence/v1.json, owned
// here, M14). The sender is the token's `sub`, recorded as
// `reporter_org` (a `reporter.org` that differs is ignored and
// counted). Idempotent on (`reporter_org`, `report_ref`): the same
// report again answers 200 with the id given first; another
// report under the same reference is 409 `report_ref_conflict`.
// A report received more than the reporting deadline (72 h,
// `OCCURRENCES_REPORT_DEADLINE_S`) after `became_aware_at` is
// accepted with `within_72h: false`, never refused. A
// `became_aware_at` ahead of the database clock by more than the
// allowed skew, or before `occurred_at`, is 400. A
// `reporter.person_ref` is stored sealed under the occurrence key;
// without that key configured such a report is 503
// `occurrence_key_unavailable` (retry later), never stored in
// clear. Operator aircraft keep the registration number's public
// part only. Recorded with an `occurrence_received` events row
// that holds no reporter identity.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/occurrences (the `CreateOccurrence` operationId).
func (c *Client) CreateOccurrenceWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOccurrenceRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateOccurrence Report an occurrence (occurrence/v1; USSPs, the ANSP)
//
// The body is `occurrence/v1` (schemas/occurrence/v1.json, owned
// here, M14). The sender is the token's `sub`, recorded as
// `reporter_org` (a `reporter.org` that differs is ignored and
// counted). Idempotent on (`reporter_org`, `report_ref`): the same
// report again answers 200 with the id given first; another
// report under the same reference is 409 `report_ref_conflict`.
// A report received more than the reporting deadline (72 h,
// `OCCURRENCES_REPORT_DEADLINE_S`) after `became_aware_at` is
// accepted with `within_72h: false`, never refused. A
// `became_aware_at` ahead of the database clock by more than the
// allowed skew, or before `occurred_at`, is 400. A
// `reporter.person_ref` is stored sealed under the occurrence key;
// without that key configured such a report is 503
// `occurrence_key_unavailable` (retry later), never stored in
// clear. Operator aircraft keep the registration number's public
// part only. Recorded with an `occurrence_received` events row
// that holds no reporter identity.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/occurrences (the `CreateOccurrence` operationId).
func (c *Client) CreateOccurrence(ctx context.Context, body CreateOccurrenceJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateOccurrenceRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateOccurrenceRequest calls the generic CreateOccurrence builder with application/json body
func NewCreateOccurrenceRequest(server string, body CreateOccurrenceJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateOccurrenceRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateOccurrenceRequestWithBody constructs an http.Request for the CreateOccurrence method, with any body, and a specified content type
func NewCreateOccurrenceRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/occurrences")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// CreateOccurrenceWithBodyWithResponse Report an occurrence (occurrence/v1; USSPs, the ANSP)
	//
	// The body is `occurrence/v1` (schemas/occurrence/v1.json, owned
	// here, M14). The sender is the token's `sub`, recorded as
	// `reporter_org` (a `reporter.org` that differs is ignored and
	// counted). Idempotent on (`reporter_org`, `report_ref`): the same
	// report again answers 200 with the id given first; another
	// report under the same reference is 409 `report_ref_conflict`.
	// A report received more than the reporting deadline (72 h,
	// `OCCURRENCES_REPORT_DEADLINE_S`) after `became_aware_at` is
	// accepted with `within_72h: false`, never refused. A
	// `became_aware_at` ahead of the database clock by more than the
	// allowed skew, or before `occurred_at`, is 400. A
	// `reporter.person_ref` is stored sealed under the occurrence key;
	// without that key configured such a report is 503
	// `occurrence_key_unavailable` (retry later), never stored in
	// clear. Operator aircraft keep the registration number's public
	// part only. Recorded with an `occurrence_received` events row
	// that holds no reporter identity.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/occurrences (the `CreateOccurrence` operationId).
	CreateOccurrenceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOccurrenceResponse, error)

	// CreateOccurrenceWithResponse Report an occurrence (occurrence/v1; USSPs, the ANSP)
	//
	// The body is `occurrence/v1` (schemas/occurrence/v1.json, owned
	// here, M14). The sender is the token's `sub`, recorded as
	// `reporter_org` (a `reporter.org` that differs is ignored and
	// counted). Idempotent on (`reporter_org`, `report_ref`): the same
	// report again answers 200 with the id given first; another
	// report under the same reference is 409 `report_ref_conflict`.
	// A report received more than the reporting deadline (72 h,
	// `OCCURRENCES_REPORT_DEADLINE_S`) after `became_aware_at` is
	// accepted with `within_72h: false`, never refused. A
	// `became_aware_at` ahead of the database clock by more than the
	// allowed skew, or before `occurred_at`, is 400. A
	// `reporter.person_ref` is stored sealed under the occurrence key;
	// without that key configured such a report is 503
	// `occurrence_key_unavailable` (retry later), never stored in
	// clear. Operator aircraft keep the registration number's public
	// part only. Recorded with an `occurrence_received` events row
	// that holds no reporter identity.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/occurrences (the `CreateOccurrence` operationId).
	CreateOccurrenceWithResponse(ctx context.Context, body CreateOccurrenceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOccurrenceResponse, error)
}

type CreateOccurrenceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *OccurrenceReceipt
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *OccurrenceReceipt
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Problem
	// ApplicationproblemJSON409 the response for an HTTP 409 `application/problem+json` response
	ApplicationproblemJSON409 *Problem
	// ApplicationproblemJSON413 the response for an HTTP 413 `application/problem+json` response
	ApplicationproblemJSON413 *Problem
	// ApplicationproblemJSON503 the response for an HTTP 503 `application/problem+json` response
	ApplicationproblemJSON503 *Problem
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateOccurrenceResponse) GetJSON200() *OccurrenceReceipt {
	return r.JSON200
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreateOccurrenceResponse) GetJSON201() *OccurrenceReceipt {
	return r.JSON201
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r CreateOccurrenceResponse) GetApplicationproblemJSON400() *Problem {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON409 returns the response for an HTTP 409 `application/problem+json` response
func (r CreateOccurrenceResponse) GetApplicationproblemJSON409() *Problem {
	return r.ApplicationproblemJSON409
}

// GetApplicationproblemJSON413 returns the response for an HTTP 413 `application/problem+json` response
func (r CreateOccurrenceResponse) GetApplicationproblemJSON413() *Problem {
	return r.ApplicationproblemJSON413
}

// GetApplicationproblemJSON503 returns the response for an HTTP 503 `application/problem+json` response
func (r CreateOccurrenceResponse) GetApplicationproblemJSON503() *Problem {
	return r.ApplicationproblemJSON503
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r CreateOccurrenceResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r CreateOccurrenceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateOccurrenceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateOccurrenceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateOccurrenceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateOccurrenceWithBodyWithResponse Report an occurrence (occurrence/v1; USSPs, the ANSP)
//
// The body is `occurrence/v1` (schemas/occurrence/v1.json, owned
// here, M14). The sender is the token's `sub`, recorded as
// `reporter_org` (a `reporter.org` that differs is ignored and
// counted). Idempotent on (`reporter_org`, `report_ref`): the same
// report again answers 200 with the id given first; another
// report under the same reference is 409 `report_ref_conflict`.
// A report received more than the reporting deadline (72 h,
// `OCCURRENCES_REPORT_DEADLINE_S`) after `became_aware_at` is
// accepted with `within_72h: false`, never refused. A
// `became_aware_at` ahead of the database clock by more than the
// allowed skew, or before `occurred_at`, is 400. A
// `reporter.person_ref` is stored sealed under the occurrence key;
// without that key configured such a report is 503
// `occurrence_key_unavailable` (retry later), never stored in
// clear. Operator aircraft keep the registration number's public
// part only. Recorded with an `occurrence_received` events row
// that holds no reporter identity.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/occurrences (the `CreateOccurrence` operationId).
func (c *ClientWithResponses) CreateOccurrenceWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateOccurrenceResponse, error) {
	rsp, err := c.CreateOccurrenceWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOccurrenceResponse(rsp)
}

// CreateOccurrenceWithResponse Report an occurrence (occurrence/v1; USSPs, the ANSP)
//
// The body is `occurrence/v1` (schemas/occurrence/v1.json, owned
// here, M14). The sender is the token's `sub`, recorded as
// `reporter_org` (a `reporter.org` that differs is ignored and
// counted). Idempotent on (`reporter_org`, `report_ref`): the same
// report again answers 200 with the id given first; another
// report under the same reference is 409 `report_ref_conflict`.
// A report received more than the reporting deadline (72 h,
// `OCCURRENCES_REPORT_DEADLINE_S`) after `became_aware_at` is
// accepted with `within_72h: false`, never refused. A
// `became_aware_at` ahead of the database clock by more than the
// allowed skew, or before `occurred_at`, is 400. A
// `reporter.person_ref` is stored sealed under the occurrence key;
// without that key configured such a report is 503
// `occurrence_key_unavailable` (retry later), never stored in
// clear. Operator aircraft keep the registration number's public
// part only. Recorded with an `occurrence_received` events row
// that holds no reporter identity.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/occurrences (the `CreateOccurrence` operationId).
func (c *ClientWithResponses) CreateOccurrenceWithResponse(ctx context.Context, body CreateOccurrenceJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateOccurrenceResponse, error) {
	rsp, err := c.CreateOccurrence(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateOccurrenceResponse(rsp)
}

// ParseCreateOccurrenceResponse parses an HTTP response from a CreateOccurrenceWithResponse call
func ParseCreateOccurrenceResponse(rsp *http.Response) (*CreateOccurrenceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateOccurrenceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OccurrenceReceipt
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest OccurrenceReceipt
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON503 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
