// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLockout = `-- name: ClearLockout :exec
DELETE FROM login_lockouts WHERE realm = $1 AND username = $2
`

type ClearLockoutParams struct {
	Realm    string `json:"realm"`
	Username string `json:"username"`
}

func (q *Queries) ClearLockout(ctx context.Context, arg ClearLockoutParams) error {
	_, err := q.db.Exec(ctx, clearLockout, arg.Realm, arg.Username)
	return err
}

const clientByID = `-- name: ClientByID :one
SELECT client_id, operator_id, secret_hash, scopes, status, created_at, rotated_at, previous_secret_hash, previous_valid_until FROM oauth_clients WHERE client_id = $1
`

func (q *Queries) ClientByID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, clientByID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.OperatorID,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.PreviousSecretHash,
		&i.PreviousValidUntil,
	)
	return i, err
}

const clientForToken = `-- name: ClientForToken :one
SELECT c.client_id, c.operator_id, c.secret_hash, c.previous_secret_hash, c.previous_valid_until, c.scopes,
       c.status AS client_status, o.status AS operator_status
FROM oauth_clients c JOIN operator_accounts o ON o.id = c.operator_id
WHERE c.client_id = $1
`

type ClientForTokenRow struct {
	ClientID           string      `json:"client_id"`
	OperatorID         pgtype.UUID `json:"operator_id"`
	SecretHash         string      `json:"secret_hash"`
	PreviousSecretHash *string     `json:"previous_secret_hash"`
	PreviousValidUntil *time.Time  `json:"previous_valid_until"`
	Scopes             []string    `json:"scopes"`
	ClientStatus       string      `json:"client_status"`
	OperatorStatus     string      `json:"operator_status"`
}

func (q *Queries) ClientForToken(ctx context.Context, clientID string) (ClientForTokenRow, error) {
	row := q.db.QueryRow(ctx, clientForToken, clientID)
	var i ClientForTokenRow
	err := row.Scan(
		&i.ClientID,
		&i.OperatorID,
		&i.SecretHash,
		&i.PreviousSecretHash,
		&i.PreviousValidUntil,
		&i.Scopes,
		&i.ClientStatus,
		&i.OperatorStatus,
	)
	return i, err
}

const clientForUpdate = `-- name: ClientForUpdate :one
SELECT client_id, operator_id, secret_hash, scopes, status, created_at, rotated_at, previous_secret_hash, previous_valid_until FROM oauth_clients WHERE client_id = $1 FOR UPDATE
`

func (q *Queries) ClientForUpdate(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, clientForUpdate, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.OperatorID,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.PreviousSecretHash,
		&i.PreviousValidUntil,
	)
	return i, err
}

const clientsOfOperator = `-- name: ClientsOfOperator :many
SELECT client_id, scopes, status, created_at, rotated_at, previous_valid_until
FROM oauth_clients
WHERE operator_id = $1
ORDER BY created_at, client_id
LIMIT $2
`

type ClientsOfOperatorParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	MaxRows    int32       `json:"max_rows"`
}

type ClientsOfOperatorRow struct {
	ClientID           string     `json:"client_id"`
	Scopes             []string   `json:"scopes"`
	Status             string     `json:"status"`
	CreatedAt          time.Time  `json:"created_at"`
	RotatedAt          *time.Time `json:"rotated_at"`
	PreviousValidUntil *time.Time `json:"previous_valid_until"`
}

// The operator's clients for its portal (WP-17), oldest first, at most
// max_rows; never a secret or its hash.
func (q *Queries) ClientsOfOperator(ctx context.Context, arg ClientsOfOperatorParams) ([]ClientsOfOperatorRow, error) {
	rows, err := q.db.Query(ctx, clientsOfOperator, arg.OperatorID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClientsOfOperatorRow
	for rows.Next() {
		var i ClientsOfOperatorRow
		if err := rows.Scan(
			&i.ClientID,
			&i.Scopes,
			&i.Status,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.PreviousValidUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureLockout = `-- name: EnsureLockout :exec
INSERT INTO login_lockouts (realm, username) VALUES ($1, $2)
ON CONFLICT (realm, username) DO NOTHING
`

type EnsureLockoutParams struct {
	Realm    string `json:"realm"`
	Username string `json:"username"`
}

func (q *Queries) EnsureLockout(ctx context.Context, arg EnsureLockoutParams) error {
	_, err := q.db.Exec(ctx, ensureLockout, arg.Realm, arg.Username)
	return err
}

const insertBinding = `-- name: InsertBinding :one
INSERT INTO client_serial_bindings (client_id, serial, serial_fold, bound_at)
VALUES ($1, $2, $3, $4)
RETURNING id, client_id, serial, serial_fold, bound_at, unbound_at
`

type InsertBindingParams struct {
	ClientID   string    `json:"client_id"`
	Serial     string    `json:"serial"`
	SerialFold string    `json:"serial_fold"`
	BoundAt    time.Time `json:"bound_at"`
}

// bound_at comes from the same clock as unbound_at, so the CHECK
// unbound_at >= bound_at cannot trip on a skew between api and the
// database.
func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) (ClientSerialBinding, error) {
	row := q.db.QueryRow(ctx, insertBinding,
		arg.ClientID,
		arg.Serial,
		arg.SerialFold,
		arg.BoundAt,
	)
	var i ClientSerialBinding
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Serial,
		&i.SerialFold,
		&i.BoundAt,
		&i.UnboundAt,
	)
	return i, err
}

const insertClient = `-- name: InsertClient :one
INSERT INTO oauth_clients (client_id, operator_id, secret_hash, scopes, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING client_id, operator_id, secret_hash, scopes, status, created_at, rotated_at, previous_secret_hash, previous_valid_until
`

type InsertClientParams struct {
	ClientID   string      `json:"client_id"`
	OperatorID pgtype.UUID `json:"operator_id"`
	SecretHash string      `json:"secret_hash"`
	Scopes     []string    `json:"scopes"`
	Status     string      `json:"status"`
}

func (q *Queries) InsertClient(ctx context.Context, arg InsertClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, insertClient,
		arg.ClientID,
		arg.OperatorID,
		arg.SecretHash,
		arg.Scopes,
		arg.Status,
	)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.OperatorID,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.PreviousSecretHash,
		&i.PreviousValidUntil,
	)
	return i, err
}

const insertOperator = `-- name: InsertOperator :one

INSERT INTO operator_accounts (authority_registration_number, display_name, contact_email, status, validation_status, validated_at)
VALUES ($1, $2, $3, $4,
        $5, $6)
RETURNING id, authority_registration_number, display_name, contact_email, status, validated_at, validation_status, created_at
`

type InsertOperatorParams struct {
	RegistrationNumber string     `json:"registration_number"`
	DisplayName        string     `json:"display_name"`
	ContactEmail       string     `json:"contact_email"`
	Status             string     `json:"status"`
	ValidationStatus   *string    `json:"validation_status"`
	ValidatedAt        *time.Time `json:"validated_at"`
}

// Accounts, clients, serial bindings, sign-in lockouts and sessions
// (WP-2). internal/accounts is the only caller.
func (q *Queries) InsertOperator(ctx context.Context, arg InsertOperatorParams) (OperatorAccount, error) {
	row := q.db.QueryRow(ctx, insertOperator,
		arg.RegistrationNumber,
		arg.DisplayName,
		arg.ContactEmail,
		arg.Status,
		arg.ValidationStatus,
		arg.ValidatedAt,
	)
	var i OperatorAccount
	err := row.Scan(
		&i.ID,
		&i.AuthorityRegistrationNumber,
		&i.DisplayName,
		&i.ContactEmail,
		&i.Status,
		&i.ValidatedAt,
		&i.ValidationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const insertPortalUser = `-- name: InsertPortalUser :one
INSERT INTO portal_users (operator_id, username, password_hash, role, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, operator_id, username, password_hash, role, status, created_at
`

type InsertPortalUserParams struct {
	OperatorID   pgtype.UUID `json:"operator_id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	Status       string      `json:"status"`
}

func (q *Queries) InsertPortalUser(ctx context.Context, arg InsertPortalUserParams) (PortalUser, error) {
	row := q.db.QueryRow(ctx, insertPortalUser,
		arg.OperatorID,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
	)
	var i PortalUser
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sessions (jti, realm, account_id, roles, issued_at, expires_at, last_seen_at, remote_ip)
VALUES ($1, $2, $3, $4, $5, $6,
        $5, $7)
`

type InsertSessionParams struct {
	Jti       string      `json:"jti"`
	Realm     string      `json:"realm"`
	AccountID pgtype.UUID `json:"account_id"`
	Roles     []string    `json:"roles"`
	IssuedAt  time.Time   `json:"issued_at"`
	ExpiresAt time.Time   `json:"expires_at"`
	RemoteIp  string      `json:"remote_ip"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.Jti,
		arg.Realm,
		arg.AccountID,
		arg.Roles,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.RemoteIp,
	)
	return err
}

const insertStaff = `-- name: InsertStaff :one
INSERT INTO staff_accounts (username, password_hash, role, mfa_secret_ref, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, username, password_hash, role, mfa_secret_ref, status, created_at, mfa_last_step
`

type InsertStaffParams struct {
	Username     string  `json:"username"`
	PasswordHash string  `json:"password_hash"`
	Role         string  `json:"role"`
	MfaSecretRef *string `json:"mfa_secret_ref"`
	Status       string  `json:"status"`
}

func (q *Queries) InsertStaff(ctx context.Context, arg InsertStaffParams) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, insertStaff,
		arg.Username,
		arg.PasswordHash,
		arg.Role,
		arg.MfaSecretRef,
		arg.Status,
	)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.MfaSecretRef,
		&i.Status,
		&i.CreatedAt,
		&i.MfaLastStep,
	)
	return i, err
}

const liveBindingByFold = `-- name: LiveBindingByFold :one
SELECT id, client_id, serial, serial_fold, bound_at, unbound_at FROM client_serial_bindings WHERE serial_fold = $1 AND unbound_at IS NULL
`

func (q *Queries) LiveBindingByFold(ctx context.Context, serialFold string) (ClientSerialBinding, error) {
	row := q.db.QueryRow(ctx, liveBindingByFold, serialFold)
	var i ClientSerialBinding
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.Serial,
		&i.SerialFold,
		&i.BoundAt,
		&i.UnboundAt,
	)
	return i, err
}

const liveBindingsOfClients = `-- name: LiveBindingsOfClients :many
SELECT client_id, serial, bound_at
FROM (SELECT b.client_id, b.serial, b.bound_at,
             row_number() OVER (PARTITION BY b.client_id ORDER BY b.bound_at, b.serial) AS n
      FROM client_serial_bindings b
      WHERE b.client_id = ANY ($1::text[]) AND b.unbound_at IS NULL) live
WHERE live.n <= $2::bigint
ORDER BY client_id, bound_at, serial
`

type LiveBindingsOfClientsParams struct {
	ClientIds []string `json:"client_ids"`
	PerClient int64    `json:"per_client"`
}

type LiveBindingsOfClientsRow struct {
	ClientID string    `json:"client_id"`
	Serial   string    `json:"serial"`
	BoundAt  time.Time `json:"bound_at"`
}

// The live serial bindings of the clients, at most per_client of each
// (oldest first), for the portal's client list (WP-17).
func (q *Queries) LiveBindingsOfClients(ctx context.Context, arg LiveBindingsOfClientsParams) ([]LiveBindingsOfClientsRow, error) {
	rows, err := q.db.Query(ctx, liveBindingsOfClients, arg.ClientIds, arg.PerClient)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LiveBindingsOfClientsRow
	for rows.Next() {
		var i LiveBindingsOfClientsRow
		if err := rows.Scan(&i.ClientID, &i.Serial, &i.BoundAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const liveFoldsOfClient = `-- name: LiveFoldsOfClient :many
SELECT serial_fold FROM client_serial_bindings
WHERE client_id = $1 AND unbound_at IS NULL
ORDER BY serial_fold
`

func (q *Queries) LiveFoldsOfClient(ctx context.Context, clientID string) ([]string, error) {
	rows, err := q.db.Query(ctx, liveFoldsOfClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var serial_fold string
		if err := rows.Scan(&serial_fold); err != nil {
			return nil, err
		}
		items = append(items, serial_fold)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockClientBindings = `-- name: LockClientBindings :exec
SELECT pg_advisory_xact_lock(hashtextextended('client_bindings:' || $1::text, 0))
`

func (q *Queries) LockClientBindings(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, lockClientBindings, clientID)
	return err
}

const lockoutByUsername = `-- name: LockoutByUsername :one
SELECT realm, username, failures, locked_until, updated_at FROM login_lockouts WHERE realm = $1 AND username = $2
`

type LockoutByUsernameParams struct {
	Realm    string `json:"realm"`
	Username string `json:"username"`
}

func (q *Queries) LockoutByUsername(ctx context.Context, arg LockoutByUsernameParams) (LoginLockout, error) {
	row := q.db.QueryRow(ctx, lockoutByUsername, arg.Realm, arg.Username)
	var i LoginLockout
	err := row.Scan(
		&i.Realm,
		&i.Username,
		&i.Failures,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const lockoutForUpdate = `-- name: LockoutForUpdate :one
SELECT realm, username, failures, locked_until, updated_at FROM login_lockouts WHERE realm = $1 AND username = $2 FOR UPDATE
`

type LockoutForUpdateParams struct {
	Realm    string `json:"realm"`
	Username string `json:"username"`
}

func (q *Queries) LockoutForUpdate(ctx context.Context, arg LockoutForUpdateParams) (LoginLockout, error) {
	row := q.db.QueryRow(ctx, lockoutForUpdate, arg.Realm, arg.Username)
	var i LoginLockout
	err := row.Scan(
		&i.Realm,
		&i.Username,
		&i.Failures,
		&i.LockedUntil,
		&i.UpdatedAt,
	)
	return i, err
}

const operatorByID = `-- name: OperatorByID :one
SELECT id, authority_registration_number, display_name, contact_email, status, validated_at, validation_status, created_at FROM operator_accounts WHERE id = $1
`

func (q *Queries) OperatorByID(ctx context.Context, id pgtype.UUID) (OperatorAccount, error) {
	row := q.db.QueryRow(ctx, operatorByID, id)
	var i OperatorAccount
	err := row.Scan(
		&i.ID,
		&i.AuthorityRegistrationNumber,
		&i.DisplayName,
		&i.ContactEmail,
		&i.Status,
		&i.ValidatedAt,
		&i.ValidationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const operatorByRegistration = `-- name: OperatorByRegistration :one
SELECT id, authority_registration_number, display_name, contact_email, status, validated_at, validation_status, created_at FROM operator_accounts WHERE authority_registration_number = $1
`

func (q *Queries) OperatorByRegistration(ctx context.Context, registrationNumber string) (OperatorAccount, error) {
	row := q.db.QueryRow(ctx, operatorByRegistration, registrationNumber)
	var i OperatorAccount
	err := row.Scan(
		&i.ID,
		&i.AuthorityRegistrationNumber,
		&i.DisplayName,
		&i.ContactEmail,
		&i.Status,
		&i.ValidatedAt,
		&i.ValidationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const portalUserByID = `-- name: PortalUserByID :one
SELECT id, operator_id, username, password_hash, role, status, created_at FROM portal_users WHERE id = $1
`

func (q *Queries) PortalUserByID(ctx context.Context, id pgtype.UUID) (PortalUser, error) {
	row := q.db.QueryRow(ctx, portalUserByID, id)
	var i PortalUser
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const portalUserByUsername = `-- name: PortalUserByUsername :one
SELECT id, operator_id, username, password_hash, role, status, created_at FROM portal_users WHERE username = $1
`

func (q *Queries) PortalUserByUsername(ctx context.Context, username string) (PortalUser, error) {
	row := q.db.QueryRow(ctx, portalUserByUsername, username)
	var i PortalUser
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = $1, revoke_reason = $2
WHERE jti = $3 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	At     *time.Time `json:"at"`
	Reason *string    `json:"reason"`
	Jti    string     `json:"jti"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.At, arg.Reason, arg.Jti)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateClientSecret = `-- name: RotateClientSecret :one
UPDATE oauth_clients
SET secret_hash = $1, previous_secret_hash = $2,
    previous_valid_until = $3, rotated_at = $4
WHERE client_id = $5
RETURNING client_id, operator_id, secret_hash, scopes, status, created_at, rotated_at, previous_secret_hash, previous_valid_until
`

type RotateClientSecretParams struct {
	SecretHash         string     `json:"secret_hash"`
	PreviousSecretHash *string    `json:"previous_secret_hash"`
	PreviousValidUntil *time.Time `json:"previous_valid_until"`
	RotatedAt          *time.Time `json:"rotated_at"`
	ClientID           string     `json:"client_id"`
}

func (q *Queries) RotateClientSecret(ctx context.Context, arg RotateClientSecretParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, rotateClientSecret,
		arg.SecretHash,
		arg.PreviousSecretHash,
		arg.PreviousValidUntil,
		arg.RotatedAt,
		arg.ClientID,
	)
	var i OauthClient
	err := row.Scan(
		&i.ClientID,
		&i.OperatorID,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.PreviousSecretHash,
		&i.PreviousValidUntil,
	)
	return i, err
}

const sessionByJTI = `-- name: SessionByJTI :one
SELECT jti, realm, account_id, roles, issued_at, expires_at, last_seen_at, revoked_at, revoke_reason, remote_ip FROM sessions WHERE jti = $1
`

func (q *Queries) SessionByJTI(ctx context.Context, jti string) (Session, error) {
	row := q.db.QueryRow(ctx, sessionByJTI, jti)
	var i Session
	err := row.Scan(
		&i.Jti,
		&i.Realm,
		&i.AccountID,
		&i.Roles,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.RevokeReason,
		&i.RemoteIp,
	)
	return i, err
}

const setLockout = `-- name: SetLockout :exec
UPDATE login_lockouts SET failures = $1, locked_until = $2, updated_at = $3
WHERE realm = $4 AND username = $5
`

type SetLockoutParams struct {
	Failures    int32      `json:"failures"`
	LockedUntil *time.Time `json:"locked_until"`
	At          time.Time  `json:"at"`
	Realm       string     `json:"realm"`
	Username    string     `json:"username"`
}

func (q *Queries) SetLockout(ctx context.Context, arg SetLockoutParams) error {
	_, err := q.db.Exec(ctx, setLockout,
		arg.Failures,
		arg.LockedUntil,
		arg.At,
		arg.Realm,
		arg.Username,
	)
	return err
}

const setOperatorValidation = `-- name: SetOperatorValidation :one
UPDATE operator_accounts
SET status = $1, validation_status = $2, validated_at = $3
WHERE id = $4
RETURNING id, authority_registration_number, display_name, contact_email, status, validated_at, validation_status, created_at
`

type SetOperatorValidationParams struct {
	Status           string      `json:"status"`
	ValidationStatus *string     `json:"validation_status"`
	ValidatedAt      *time.Time  `json:"validated_at"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) SetOperatorValidation(ctx context.Context, arg SetOperatorValidationParams) (OperatorAccount, error) {
	row := q.db.QueryRow(ctx, setOperatorValidation,
		arg.Status,
		arg.ValidationStatus,
		arg.ValidatedAt,
		arg.ID,
	)
	var i OperatorAccount
	err := row.Scan(
		&i.ID,
		&i.AuthorityRegistrationNumber,
		&i.DisplayName,
		&i.ContactEmail,
		&i.Status,
		&i.ValidatedAt,
		&i.ValidationStatus,
		&i.CreatedAt,
	)
	return i, err
}

const setStaffMFAStep = `-- name: SetStaffMFAStep :exec
UPDATE staff_accounts SET mfa_last_step = $1 WHERE id = $2
`

type SetStaffMFAStepParams struct {
	Step int64       `json:"step"`
	ID   pgtype.UUID `json:"id"`
}

func (q *Queries) SetStaffMFAStep(ctx context.Context, arg SetStaffMFAStepParams) error {
	_, err := q.db.Exec(ctx, setStaffMFAStep, arg.Step, arg.ID)
	return err
}

const staffByID = `-- name: StaffByID :one
SELECT id, username, password_hash, role, mfa_secret_ref, status, created_at, mfa_last_step FROM staff_accounts WHERE id = $1
`

func (q *Queries) StaffByID(ctx context.Context, id pgtype.UUID) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, staffByID, id)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.MfaSecretRef,
		&i.Status,
		&i.CreatedAt,
		&i.MfaLastStep,
	)
	return i, err
}

const staffByUsername = `-- name: StaffByUsername :one
SELECT id, username, password_hash, role, mfa_secret_ref, status, created_at, mfa_last_step FROM staff_accounts WHERE username = $1
`

func (q *Queries) StaffByUsername(ctx context.Context, username string) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, staffByUsername, username)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.MfaSecretRef,
		&i.Status,
		&i.CreatedAt,
		&i.MfaLastStep,
	)
	return i, err
}

const staffForUpdate = `-- name: StaffForUpdate :one
SELECT id, username, password_hash, role, mfa_secret_ref, status, created_at, mfa_last_step FROM staff_accounts WHERE id = $1 FOR UPDATE
`

func (q *Queries) StaffForUpdate(ctx context.Context, id pgtype.UUID) (StaffAccount, error) {
	row := q.db.QueryRow(ctx, staffForUpdate, id)
	var i StaffAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Role,
		&i.MfaSecretRef,
		&i.Status,
		&i.CreatedAt,
		&i.MfaLastStep,
	)
	return i, err
}

const sweepLockouts = `-- name: SweepLockouts :execrows
DELETE FROM login_lockouts
WHERE updated_at < $1 AND (locked_until IS NULL OR locked_until < $2)
`

type SweepLockoutsParams struct {
	Before time.Time  `json:"before"`
	Now    *time.Time `json:"now"`
}

func (q *Queries) SweepLockouts(ctx context.Context, arg SweepLockoutsParams) (int64, error) {
	result, err := q.db.Exec(ctx, sweepLockouts, arg.Before, arg.Now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sweepSessions = `-- name: SweepSessions :execrows
DELETE FROM sessions WHERE expires_at < $1
`

func (q *Queries) SweepSessions(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, sweepSessions, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $1 WHERE jti = $2 AND revoked_at IS NULL
`

type TouchSessionParams struct {
	At  time.Time `json:"at"`
	Jti string    `json:"jti"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.At, arg.Jti)
	return err
}

const unbindSerial = `-- name: UnbindSerial :execrows
UPDATE client_serial_bindings SET unbound_at = $1
WHERE client_id = $2 AND serial_fold = $3 AND unbound_at IS NULL
`

type UnbindSerialParams struct {
	At         *time.Time `json:"at"`
	ClientID   string     `json:"client_id"`
	SerialFold string     `json:"serial_fold"`
}

func (q *Queries) UnbindSerial(ctx context.Context, arg UnbindSerialParams) (int64, error) {
	result, err := q.db.Exec(ctx, unbindSerial, arg.At, arg.ClientID, arg.SerialFold)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateOperatorContact = `-- name: UpdateOperatorContact :one
UPDATE operator_accounts
SET display_name  = COALESCE($1, display_name),
    contact_email = COALESCE($2, contact_email)
WHERE id = $3
RETURNING id, authority_registration_number, display_name, contact_email, status, validated_at, validation_status, created_at
`

type UpdateOperatorContactParams struct {
	DisplayName  *string     `json:"display_name"`
	ContactEmail *string     `json:"contact_email"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateOperatorContact(ctx context.Context, arg UpdateOperatorContactParams) (OperatorAccount, error) {
	row := q.db.QueryRow(ctx, updateOperatorContact, arg.DisplayName, arg.ContactEmail, arg.ID)
	var i OperatorAccount
	err := row.Scan(
		&i.ID,
		&i.AuthorityRegistrationNumber,
		&i.DisplayName,
		&i.ContactEmail,
		&i.Status,
		&i.ValidatedAt,
		&i.ValidationStatus,
		&i.CreatedAt,
	)
	return i, err
}
