// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminActiveFlights = `-- name: AdminActiveFlights :many

SELECT f.id, f.intent_id, f.authorisation_number, f.uas_serial, f.operator_reg, f.client_id, f.started_at, f.last_state, f.emergency,
       oi.local_state AS intent_state, oi.dss_state,
       cs.state AS conformance_state, cs.at AS conformance_at, cs.reason AS conformance_reason,
       EXISTS (SELECT 1 FROM emergency_cases ec WHERE ec.flight_id = f.id AND ec.closed_at IS NULL) AS case_open
FROM flights f
LEFT JOIN operational_intents oi ON oi.id = f.intent_id
LEFT JOIN conformance_states cs ON cs.id = (
    SELECT c.id FROM conformance_states c WHERE c.flight_id = f.id ORDER BY c.at DESC, c.id DESC LIMIT 1
)
WHERE f.ended_at IS NULL
ORDER BY f.started_at DESC, f.id
LIMIT $1
`

type AdminActiveFlightsRow struct {
	ID                  pgtype.UUID `json:"id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	UasSerial           string      `json:"uas_serial"`
	OperatorReg         *string     `json:"operator_reg"`
	ClientID            *string     `json:"client_id"`
	StartedAt           time.Time   `json:"started_at"`
	LastState           *string     `json:"last_state"`
	Emergency           bool        `json:"emergency"`
	IntentState         *string     `json:"intent_state"`
	DssState            *string     `json:"dss_state"`
	ConformanceState    *string     `json:"conformance_state"`
	ConformanceAt       *time.Time  `json:"conformance_at"`
	ConformanceReason   *string     `json:"conformance_reason"`
	CaseOpen            bool        `json:"case_open"`
}

// The USSP console (internal/admin, WP-18): the reads of the console
// pages and the console's own facts on alerts and emergency cases. Every
// time written is the database clock; every write goes with its events
// row in the caller's transaction (internal/store Audit).
// The flights not ended, newest first, at most max_rows, with their
// intent's states, the newest conformance state recorded and whether an
// emergency case is open.
func (q *Queries) AdminActiveFlights(ctx context.Context, maxRows int32) ([]AdminActiveFlightsRow, error) {
	rows, err := q.db.Query(ctx, adminActiveFlights, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminActiveFlightsRow
	for rows.Next() {
		var i AdminActiveFlightsRow
		if err := rows.Scan(
			&i.ID,
			&i.IntentID,
			&i.AuthorisationNumber,
			&i.UasSerial,
			&i.OperatorReg,
			&i.ClientID,
			&i.StartedAt,
			&i.LastState,
			&i.Emergency,
			&i.IntentState,
			&i.DssState,
			&i.ConformanceState,
			&i.ConformanceAt,
			&i.ConformanceReason,
			&i.CaseOpen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminAddNote = `-- name: AdminAddNote :one
INSERT INTO emergency_notes (case_id, author, step, text)
VALUES ($1::uuid, $2, $3, $4)
RETURNING at
`

type AdminAddNoteParams struct {
	CaseID pgtype.UUID `json:"case_id"`
	Author string      `json:"author"`
	Step   *string     `json:"step"`
	Text   string      `json:"text"`
}

func (q *Queries) AdminAddNote(ctx context.Context, arg AdminAddNoteParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, adminAddNote,
		arg.CaseID,
		arg.Author,
		arg.Step,
		arg.Text,
	)
	var at time.Time
	err := row.Scan(&at)
	return at, err
}

const adminAlertForUpdate = `-- name: AdminAlertForUpdate :one
SELECT id, kind, flight_id, intent_id, authorisation_number, severity, state, raised_at, updated_at, cleared_at, clear_reason,
       detail, captured_at, policy_version, acked_at, acked_by, escalated_at, escalated_by, escalation_reason, closed_at, closed_by,
       close_reason, messages_recorded, cell5
FROM alerts
WHERE id = $1::uuid
FOR UPDATE
`

type AdminAlertForUpdateRow struct {
	ID                  pgtype.UUID `json:"id"`
	Kind                string      `json:"kind"`
	FlightID            pgtype.UUID `json:"flight_id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	Severity            string      `json:"severity"`
	State               string      `json:"state"`
	RaisedAt            time.Time   `json:"raised_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ClearedAt           *time.Time  `json:"cleared_at"`
	ClearReason         *string     `json:"clear_reason"`
	Detail              []byte      `json:"detail"`
	CapturedAt          *time.Time  `json:"captured_at"`
	PolicyVersion       int64       `json:"policy_version"`
	AckedAt             *time.Time  `json:"acked_at"`
	AckedBy             *string     `json:"acked_by"`
	EscalatedAt         *time.Time  `json:"escalated_at"`
	EscalatedBy         *string     `json:"escalated_by"`
	EscalationReason    *string     `json:"escalation_reason"`
	ClosedAt            *time.Time  `json:"closed_at"`
	ClosedBy            *string     `json:"closed_by"`
	CloseReason         *string     `json:"close_reason"`
	MessagesRecorded    int64       `json:"messages_recorded"`
	Cell5               *string     `json:"cell5"`
}

// One alert, locked for the console's write in this transaction.
func (q *Queries) AdminAlertForUpdate(ctx context.Context, id pgtype.UUID) (AdminAlertForUpdateRow, error) {
	row := q.db.QueryRow(ctx, adminAlertForUpdate, id)
	var i AdminAlertForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FlightID,
		&i.IntentID,
		&i.AuthorisationNumber,
		&i.Severity,
		&i.State,
		&i.RaisedAt,
		&i.UpdatedAt,
		&i.ClearedAt,
		&i.ClearReason,
		&i.Detail,
		&i.CapturedAt,
		&i.PolicyVersion,
		&i.AckedAt,
		&i.AckedBy,
		&i.EscalatedAt,
		&i.EscalatedBy,
		&i.EscalationReason,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.CloseReason,
		&i.MessagesRecorded,
		&i.Cell5,
	)
	return i, err
}

const adminAlerts = `-- name: AdminAlerts :many
SELECT id, kind, flight_id, intent_id, authorisation_number, severity, state, raised_at, updated_at, cleared_at, clear_reason,
       detail, policy_version, acked_at, acked_by, escalated_at, escalated_by, escalation_reason, closed_at, closed_by,
       close_reason, messages_recorded
FROM alerts
WHERE cleared_at IS NULL
   OR ($1::bool AND cleared_at > now() - make_interval(secs => $2::double precision))
ORDER BY raised_at DESC, id
LIMIT $3
`

type AdminAlertsParams struct {
	Recent  bool    `json:"recent"`
	RecentS float64 `json:"recent_s"`
	MaxRows int32   `json:"max_rows"`
}

type AdminAlertsRow struct {
	ID                  pgtype.UUID `json:"id"`
	Kind                string      `json:"kind"`
	FlightID            pgtype.UUID `json:"flight_id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	Severity            string      `json:"severity"`
	State               string      `json:"state"`
	RaisedAt            time.Time   `json:"raised_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ClearedAt           *time.Time  `json:"cleared_at"`
	ClearReason         *string     `json:"clear_reason"`
	Detail              []byte      `json:"detail"`
	PolicyVersion       int64       `json:"policy_version"`
	AckedAt             *time.Time  `json:"acked_at"`
	AckedBy             *string     `json:"acked_by"`
	EscalatedAt         *time.Time  `json:"escalated_at"`
	EscalatedBy         *string     `json:"escalated_by"`
	EscalationReason    *string     `json:"escalation_reason"`
	ClosedAt            *time.Time  `json:"closed_at"`
	ClosedBy            *string     `json:"closed_by"`
	CloseReason         *string     `json:"close_reason"`
	MessagesRecorded    int64       `json:"messages_recorded"`
}

// The alerts not cleared, and with recent those cleared in the last
// recent_s, newest first, at most max_rows.
func (q *Queries) AdminAlerts(ctx context.Context, arg AdminAlertsParams) ([]AdminAlertsRow, error) {
	rows, err := q.db.Query(ctx, adminAlerts, arg.Recent, arg.RecentS, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminAlertsRow
	for rows.Next() {
		var i AdminAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FlightID,
			&i.IntentID,
			&i.AuthorisationNumber,
			&i.Severity,
			&i.State,
			&i.RaisedAt,
			&i.UpdatedAt,
			&i.ClearedAt,
			&i.ClearReason,
			&i.Detail,
			&i.PolicyVersion,
			&i.AckedAt,
			&i.AckedBy,
			&i.EscalatedAt,
			&i.EscalatedBy,
			&i.EscalationReason,
			&i.ClosedAt,
			&i.ClosedBy,
			&i.CloseReason,
			&i.MessagesRecorded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCaseNotes = `-- name: AdminCaseNotes :many
SELECT case_id, at, author, step, text
FROM emergency_notes
WHERE case_id = ANY ($1::uuid[])
ORDER BY at, id
LIMIT $2
`

type AdminCaseNotesParams struct {
	CaseIds []pgtype.UUID `json:"case_ids"`
	MaxRows int32         `json:"max_rows"`
}

type AdminCaseNotesRow struct {
	CaseID pgtype.UUID `json:"case_id"`
	At     time.Time   `json:"at"`
	Author string      `json:"author"`
	Step   *string     `json:"step"`
	Text   string      `json:"text"`
}

// The notes of the cases, oldest first, at most max_rows.
func (q *Queries) AdminCaseNotes(ctx context.Context, arg AdminCaseNotesParams) ([]AdminCaseNotesRow, error) {
	rows, err := q.db.Query(ctx, adminCaseNotes, arg.CaseIds, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminCaseNotesRow
	for rows.Next() {
		var i AdminCaseNotesRow
		if err := rows.Scan(
			&i.CaseID,
			&i.At,
			&i.Author,
			&i.Step,
			&i.Text,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCaseOfFlight = `-- name: AdminCaseOfFlight :one
SELECT c.id, c.flight_id, c.opened_at, c.opened_by, c.reason, c.closed_at, c.closed_by, c.outcome,
       f.intent_id, f.authorisation_number, f.uas_serial, oi.emergency_contact_ref
FROM emergency_cases c
JOIN flights f ON f.id = c.flight_id
LEFT JOIN operational_intents oi ON oi.id = f.intent_id
WHERE c.flight_id = $1::uuid
ORDER BY c.opened_at DESC, c.id
LIMIT 1
`

type AdminCaseOfFlightRow struct {
	ID                  pgtype.UUID `json:"id"`
	FlightID            pgtype.UUID `json:"flight_id"`
	OpenedAt            time.Time   `json:"opened_at"`
	OpenedBy            string      `json:"opened_by"`
	Reason              string      `json:"reason"`
	ClosedAt            *time.Time  `json:"closed_at"`
	ClosedBy            *string     `json:"closed_by"`
	Outcome             *string     `json:"outcome"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	UasSerial           string      `json:"uas_serial"`
	EmergencyContactRef *string     `json:"emergency_contact_ref"`
}

// The flight's newest case.
func (q *Queries) AdminCaseOfFlight(ctx context.Context, flightID pgtype.UUID) (AdminCaseOfFlightRow, error) {
	row := q.db.QueryRow(ctx, adminCaseOfFlight, flightID)
	var i AdminCaseOfFlightRow
	err := row.Scan(
		&i.ID,
		&i.FlightID,
		&i.OpenedAt,
		&i.OpenedBy,
		&i.Reason,
		&i.ClosedAt,
		&i.ClosedBy,
		&i.Outcome,
		&i.IntentID,
		&i.AuthorisationNumber,
		&i.UasSerial,
		&i.EmergencyContactRef,
	)
	return i, err
}

const adminCases = `-- name: AdminCases :many
SELECT c.id, c.flight_id, c.opened_at, c.opened_by, c.reason, c.closed_at, c.closed_by, c.outcome,
       f.intent_id, f.authorisation_number, f.uas_serial, oi.emergency_contact_ref
FROM emergency_cases c
JOIN flights f ON f.id = c.flight_id
LEFT JOIN operational_intents oi ON oi.id = f.intent_id
WHERE c.closed_at IS NULL OR c.closed_at > now() - make_interval(secs => $1::double precision)
ORDER BY (c.closed_at IS NULL) DESC, c.opened_at DESC, c.id
LIMIT $2
`

type AdminCasesParams struct {
	ClosedS float64 `json:"closed_s"`
	MaxRows int32   `json:"max_rows"`
}

type AdminCasesRow struct {
	ID                  pgtype.UUID `json:"id"`
	FlightID            pgtype.UUID `json:"flight_id"`
	OpenedAt            time.Time   `json:"opened_at"`
	OpenedBy            string      `json:"opened_by"`
	Reason              string      `json:"reason"`
	ClosedAt            *time.Time  `json:"closed_at"`
	ClosedBy            *string     `json:"closed_by"`
	Outcome             *string     `json:"outcome"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	UasSerial           string      `json:"uas_serial"`
	EmergencyContactRef *string     `json:"emergency_contact_ref"`
}

// The open cases and those closed in the last closed_s, open first,
// newest first, at most max_rows.
func (q *Queries) AdminCases(ctx context.Context, arg AdminCasesParams) ([]AdminCasesRow, error) {
	rows, err := q.db.Query(ctx, adminCases, arg.ClosedS, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminCasesRow
	for rows.Next() {
		var i AdminCasesRow
		if err := rows.Scan(
			&i.ID,
			&i.FlightID,
			&i.OpenedAt,
			&i.OpenedBy,
			&i.Reason,
			&i.ClosedAt,
			&i.ClosedBy,
			&i.Outcome,
			&i.IntentID,
			&i.AuthorisationNumber,
			&i.UasSerial,
			&i.EmergencyContactRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminCloseAlert = `-- name: AdminCloseAlert :one
UPDATE alerts
SET closed_at = now(), closed_by = $1::text, close_reason = $2::text
WHERE id = $3::uuid AND closed_at IS NULL
RETURNING closed_at
`

type AdminCloseAlertParams struct {
	StaffID string      `json:"staff_id"`
	Reason  string      `json:"reason"`
	ID      pgtype.UUID `json:"id"`
}

// The console's close of an alert not closed yet; no row when it was.
func (q *Queries) AdminCloseAlert(ctx context.Context, arg AdminCloseAlertParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, adminCloseAlert, arg.StaffID, arg.Reason, arg.ID)
	var closed_at *time.Time
	err := row.Scan(&closed_at)
	return closed_at, err
}

const adminCloseCase = `-- name: AdminCloseCase :one
UPDATE emergency_cases
SET closed_at = now(), closed_by = $1::text, outcome = $2::text
WHERE id = $3::uuid AND closed_at IS NULL
RETURNING closed_at
`

type AdminCloseCaseParams struct {
	ClosedBy string      `json:"closed_by"`
	Outcome  string      `json:"outcome"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) AdminCloseCase(ctx context.Context, arg AdminCloseCaseParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, adminCloseCase, arg.ClosedBy, arg.Outcome, arg.ID)
	var closed_at *time.Time
	err := row.Scan(&closed_at)
	return closed_at, err
}

const adminEscalateAlert = `-- name: AdminEscalateAlert :one
UPDATE alerts
SET escalated_at = now(), escalated_by = $1::text, escalation_reason = $2::text
WHERE id = $3::uuid AND escalated_at IS NULL
RETURNING escalated_at
`

type AdminEscalateAlertParams struct {
	StaffID string      `json:"staff_id"`
	Reason  string      `json:"reason"`
	ID      pgtype.UUID `json:"id"`
}

// A supervisor's escalation of an alert not escalated yet; no row when
// it was (the caller answers it unchanged).
func (q *Queries) AdminEscalateAlert(ctx context.Context, arg AdminEscalateAlertParams) (*time.Time, error) {
	row := q.db.QueryRow(ctx, adminEscalateAlert, arg.StaffID, arg.Reason, arg.ID)
	var escalated_at *time.Time
	err := row.Scan(&escalated_at)
	return escalated_at, err
}

const adminEscalations = `-- name: AdminEscalations :many
SELECT id, kind, flight_id, intent_id, authorisation_number, severity, state, raised_at, updated_at, cleared_at, clear_reason,
       detail, policy_version, acked_at, acked_by, escalated_at, escalated_by, escalation_reason, closed_at, closed_by,
       close_reason, messages_recorded
FROM alerts
WHERE escalated_at IS NOT NULL AND closed_at IS NULL
ORDER BY escalated_at, id
LIMIT $1
`

type AdminEscalationsRow struct {
	ID                  pgtype.UUID `json:"id"`
	Kind                string      `json:"kind"`
	FlightID            pgtype.UUID `json:"flight_id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	Severity            string      `json:"severity"`
	State               string      `json:"state"`
	RaisedAt            time.Time   `json:"raised_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ClearedAt           *time.Time  `json:"cleared_at"`
	ClearReason         *string     `json:"clear_reason"`
	Detail              []byte      `json:"detail"`
	PolicyVersion       int64       `json:"policy_version"`
	AckedAt             *time.Time  `json:"acked_at"`
	AckedBy             *string     `json:"acked_by"`
	EscalatedAt         *time.Time  `json:"escalated_at"`
	EscalatedBy         *string     `json:"escalated_by"`
	EscalationReason    *string     `json:"escalation_reason"`
	ClosedAt            *time.Time  `json:"closed_at"`
	ClosedBy            *string     `json:"closed_by"`
	CloseReason         *string     `json:"close_reason"`
	MessagesRecorded    int64       `json:"messages_recorded"`
}

// The alerts escalated and not closed on the console, oldest escalation
// first, at most max_rows.
func (q *Queries) AdminEscalations(ctx context.Context, maxRows int32) ([]AdminEscalationsRow, error) {
	rows, err := q.db.Query(ctx, adminEscalations, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminEscalationsRow
	for rows.Next() {
		var i AdminEscalationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FlightID,
			&i.IntentID,
			&i.AuthorisationNumber,
			&i.Severity,
			&i.State,
			&i.RaisedAt,
			&i.UpdatedAt,
			&i.ClearedAt,
			&i.ClearReason,
			&i.Detail,
			&i.PolicyVersion,
			&i.AckedAt,
			&i.AckedBy,
			&i.EscalatedAt,
			&i.EscalatedBy,
			&i.EscalationReason,
			&i.ClosedAt,
			&i.ClosedBy,
			&i.CloseReason,
			&i.MessagesRecorded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminEvents = `-- name: AdminEvents :many
SELECT id, ts, actor_type, actor_id, entity_type, entity_id, event_type, payload
FROM events
WHERE entity_type = $1 AND entity_id = $2::text
ORDER BY ts, id
LIMIT $3
`

type AdminEventsParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	MaxRows    int32  `json:"max_rows"`
}

type AdminEventsRow struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	ActorType  string    `json:"actor_type"`
	ActorID    string    `json:"actor_id"`
	EntityType string    `json:"entity_type"`
	EntityID   *string   `json:"entity_id"`
	EventType  string    `json:"event_type"`
	Payload    []byte    `json:"payload"`
}

// The events rows of one console entity, oldest first, at most max_rows.
func (q *Queries) AdminEvents(ctx context.Context, arg AdminEventsParams) ([]AdminEventsRow, error) {
	rows, err := q.db.Query(ctx, adminEvents, arg.EntityType, arg.EntityID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminEventsRow
	for rows.Next() {
		var i AdminEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.EntityType,
			&i.EntityID,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminFlightForCase = `-- name: AdminFlightForCase :one
SELECT f.id, f.intent_id, f.authorisation_number, f.uas_serial, oi.emergency_contact_ref
FROM flights f
LEFT JOIN operational_intents oi ON oi.id = f.intent_id
WHERE f.id = $1::uuid
`

type AdminFlightForCaseRow struct {
	ID                  pgtype.UUID `json:"id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	UasSerial           string      `json:"uas_serial"`
	EmergencyContactRef *string     `json:"emergency_contact_ref"`
}

// A flight and its intent's emergency contact reference, for a case.
func (q *Queries) AdminFlightForCase(ctx context.Context, id pgtype.UUID) (AdminFlightForCaseRow, error) {
	row := q.db.QueryRow(ctx, adminFlightForCase, id)
	var i AdminFlightForCaseRow
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.AuthorisationNumber,
		&i.UasSerial,
		&i.EmergencyContactRef,
	)
	return i, err
}

const adminOpenCase = `-- name: AdminOpenCase :one
INSERT INTO emergency_cases (flight_id, opened_by, reason)
VALUES ($1::uuid, $2, $3)
ON CONFLICT (flight_id) WHERE closed_at IS NULL DO NOTHING
RETURNING id
`

type AdminOpenCaseParams struct {
	FlightID pgtype.UUID `json:"flight_id"`
	OpenedBy string      `json:"opened_by"`
	Reason   string      `json:"reason"`
}

// A new open case; no row while one is open for the flight.
func (q *Queries) AdminOpenCase(ctx context.Context, arg AdminOpenCaseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, adminOpenCase, arg.FlightID, arg.OpenedBy, arg.Reason)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const adminOpenCaseOfFlight = `-- name: AdminOpenCaseOfFlight :one
SELECT id FROM emergency_cases WHERE flight_id = $1::uuid AND closed_at IS NULL FOR UPDATE
`

// The flight's open case, locked for a note or the close.
func (q *Queries) AdminOpenCaseOfFlight(ctx context.Context, flightID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, adminOpenCaseOfFlight, flightID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const adminOutboxDepth = `-- name: AdminOutboxDepth :many
SELECT kind, count(*)::bigint AS pending, (count(*) FILTER (WHERE attempts > 0))::bigint AS retrying,
       min(created_at)::timestamptz AS oldest_created_at
FROM dss_outbox
WHERE done_at IS NULL
GROUP BY kind
ORDER BY kind
`

type AdminOutboxDepthRow struct {
	Kind            string    `json:"kind"`
	Pending         int64     `json:"pending"`
	Retrying        int64     `json:"retrying"`
	OldestCreatedAt time.Time `json:"oldest_created_at"`
}

// The outbox items not done, by kind, with the oldest and how many
// failed at least once.
func (q *Queries) AdminOutboxDepth(ctx context.Context) ([]AdminOutboxDepthRow, error) {
	rows, err := q.db.Query(ctx, adminOutboxDepth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminOutboxDepthRow
	for rows.Next() {
		var i AdminOutboxDepthRow
		if err := rows.Scan(
			&i.Kind,
			&i.Pending,
			&i.Retrying,
			&i.OldestCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminOutboxErrors = `-- name: AdminOutboxErrors :many
SELECT kind, entity_id, attempts, last_error, next_at, done_at
FROM dss_outbox
WHERE last_error IS NOT NULL
ORDER BY next_at DESC, id DESC
LIMIT $1
`

type AdminOutboxErrorsRow struct {
	Kind      string     `json:"kind"`
	EntityID  string     `json:"entity_id"`
	Attempts  int32      `json:"attempts"`
	LastError *string    `json:"last_error"`
	NextAt    time.Time  `json:"next_at"`
	DoneAt    *time.Time `json:"done_at"`
}

// The newest outbox items with an error, at most max_rows.
func (q *Queries) AdminOutboxErrors(ctx context.Context, maxRows int32) ([]AdminOutboxErrorsRow, error) {
	rows, err := q.db.Query(ctx, adminOutboxErrors, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminOutboxErrorsRow
	for rows.Next() {
		var i AdminOutboxErrorsRow
		if err := rows.Scan(
			&i.Kind,
			&i.EntityID,
			&i.Attempts,
			&i.LastError,
			&i.NextAt,
			&i.DoneAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminPolicyHistory = `-- name: AdminPolicyHistory :many
SELECT version, created_at, actor, reason, "values"
FROM policy
ORDER BY version DESC
LIMIT $1
`

// The newest policy versions, newest first, at most max_rows.
func (q *Queries) AdminPolicyHistory(ctx context.Context, maxRows int32) ([]Policy, error) {
	rows, err := q.db.Query(ctx, adminPolicyHistory, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.Version,
			&i.CreatedAt,
			&i.Actor,
			&i.Reason,
			&i.Values,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminRecordDays = `-- name: AdminRecordDays :many
SELECT date, built_at, content_hash, flights
FROM record_bundles
WHERE date >= $1::date
ORDER BY date DESC
`

type AdminRecordDaysRow struct {
	Date        pgtype.Date `json:"date"`
	BuiltAt     time.Time   `json:"built_at"`
	ContentHash string      `json:"content_hash"`
	Flights     int32       `json:"flights"`
}

// The bundles built from first_day on, newest first.
func (q *Queries) AdminRecordDays(ctx context.Context, firstDay pgtype.Date) ([]AdminRecordDaysRow, error) {
	rows, err := q.db.Query(ctx, adminRecordDays, firstDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminRecordDaysRow
	for rows.Next() {
		var i AdminRecordDaysRow
		if err := rows.Scan(
			&i.Date,
			&i.BuiltAt,
			&i.ContentHash,
			&i.Flights,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminSubscriptions = `-- name: AdminSubscriptions :many
SELECT subscription_id, kind, time_end, renewed_at, notification_index
FROM dss_subscriptions
ORDER BY time_end DESC, subscription_id
LIMIT $1
`

type AdminSubscriptionsRow struct {
	SubscriptionID    string     `json:"subscription_id"`
	Kind              string     `json:"kind"`
	TimeEnd           time.Time  `json:"time_end"`
	RenewedAt         *time.Time `json:"renewed_at"`
	NotificationIndex int32      `json:"notification_index"`
}

func (q *Queries) AdminSubscriptions(ctx context.Context, maxRows int32) ([]AdminSubscriptionsRow, error) {
	rows, err := q.db.Query(ctx, adminSubscriptions, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdminSubscriptionsRow
	for rows.Next() {
		var i AdminSubscriptionsRow
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.Kind,
			&i.TimeEnd,
			&i.RenewedAt,
			&i.NotificationIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
