// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alerts.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const ackAlert = `-- name: AckAlert :one
UPDATE alerts a
SET acked_at = COALESCE(a.acked_at, now()),
    acked_by = COALESCE(a.acked_by, $1::text),
    delivery = jsonb_set(a.delivery, ARRAY[$1::text],
                         COALESCE(a.delivery -> $1::text, '{}'::jsonb)
                         || jsonb_build_object('acked_at', to_jsonb(COALESCE(a.acked_at, now()))))
FROM flights f
JOIN oauth_clients owner ON owner.client_id = f.client_id
JOIN oauth_clients caller ON caller.client_id = $1::text AND caller.operator_id = owner.operator_id
WHERE a.id = $2::uuid AND f.id = a.flight_id
RETURNING a.id, a.kind, a.flight_id, a.intent_id, a.authorisation_number, a.severity, a.state, a.raised_at, a.updated_at,
          a.cleared_at, a.clear_reason, a.detail, a.captured_at, a.policy_version, a.acked_at, a.acked_by, a.escalated_at, a.cell5
`

type AckAlertParams struct {
	ClientID string      `json:"client_id"`
	ID       pgtype.UUID `json:"id"`
}

type AckAlertRow struct {
	ID                  pgtype.UUID `json:"id"`
	Kind                string      `json:"kind"`
	FlightID            pgtype.UUID `json:"flight_id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	Severity            string      `json:"severity"`
	State               string      `json:"state"`
	RaisedAt            time.Time   `json:"raised_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ClearedAt           *time.Time  `json:"cleared_at"`
	ClearReason         *string     `json:"clear_reason"`
	Detail              []byte      `json:"detail"`
	CapturedAt          *time.Time  `json:"captured_at"`
	PolicyVersion       int64       `json:"policy_version"`
	AckedAt             *time.Time  `json:"acked_at"`
	AckedBy             *string     `json:"acked_by"`
	EscalatedAt         *time.Time  `json:"escalated_at"`
	Cell5               *string     `json:"cell5"`
}

// The acknowledgement of an alert of one of the caller's operator's
// flights, on the database clock; a repeat keeps the first. No row:
// not this operator's alert, or no such alert.
func (q *Queries) AckAlert(ctx context.Context, arg AckAlertParams) (AckAlertRow, error) {
	row := q.db.QueryRow(ctx, ackAlert, arg.ClientID, arg.ID)
	var i AckAlertRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FlightID,
		&i.IntentID,
		&i.AuthorisationNumber,
		&i.Severity,
		&i.State,
		&i.RaisedAt,
		&i.UpdatedAt,
		&i.ClearedAt,
		&i.ClearReason,
		&i.Detail,
		&i.CapturedAt,
		&i.PolicyVersion,
		&i.AckedAt,
		&i.AckedBy,
		&i.EscalatedAt,
		&i.Cell5,
	)
	return i, err
}

const escalateAlerts = `-- name: EscalateAlerts :many
UPDATE alerts a
SET escalated_at = now()
WHERE a.id IN (
    SELECT e.id FROM alerts e
    WHERE e.severity = 'critical' AND e.cleared_at IS NULL AND e.acked_at IS NULL AND e.escalated_at IS NULL
      AND LEAST(e.raised_at, e.recorded_at) <= now() - make_interval(secs => $1::double precision)
    ORDER BY e.raised_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING a.id, a.kind, a.flight_id, a.intent_id, a.authorisation_number, a.severity, a.state, a.raised_at, a.updated_at,
          a.cleared_at, a.clear_reason, a.detail, a.captured_at, a.policy_version, a.acked_at, a.acked_by, a.escalated_at, a.cell5
`

type EscalateAlertsParams struct {
	AfterS  float64 `json:"after_s"`
	MaxRows int32   `json:"max_rows"`
}

type EscalateAlertsRow struct {
	ID                  pgtype.UUID `json:"id"`
	Kind                string      `json:"kind"`
	FlightID            pgtype.UUID `json:"flight_id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	Severity            string      `json:"severity"`
	State               string      `json:"state"`
	RaisedAt            time.Time   `json:"raised_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ClearedAt           *time.Time  `json:"cleared_at"`
	ClearReason         *string     `json:"clear_reason"`
	Detail              []byte      `json:"detail"`
	CapturedAt          *time.Time  `json:"captured_at"`
	PolicyVersion       int64       `json:"policy_version"`
	AckedAt             *time.Time  `json:"acked_at"`
	AckedBy             *string     `json:"acked_by"`
	EscalatedAt         *time.Time  `json:"escalated_at"`
	Cell5               *string     `json:"cell5"`
}

// Marks, on the database clock, every critical alert still open and
// unacknowledged escalation_after_s after the earlier of its raise and
// its first record, oldest first, at most max_rows.
func (q *Queries) EscalateAlerts(ctx context.Context, arg EscalateAlertsParams) ([]EscalateAlertsRow, error) {
	rows, err := q.db.Query(ctx, escalateAlerts, arg.AfterS, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EscalateAlertsRow
	for rows.Next() {
		var i EscalateAlertsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FlightID,
			&i.IntentID,
			&i.AuthorisationNumber,
			&i.Severity,
			&i.State,
			&i.RaisedAt,
			&i.UpdatedAt,
			&i.ClearedAt,
			&i.ClearReason,
			&i.Detail,
			&i.CapturedAt,
			&i.PolicyVersion,
			&i.AckedAt,
			&i.AckedBy,
			&i.EscalatedAt,
			&i.Cell5,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlert = `-- name: GetAlert :one
SELECT id, kind, flight_id, intent_id, authorisation_number, peer_ref, severity, state, raised_at, updated_at, cleared_at,
       clear_reason, detail, captured_at, policy_version, acked_at, acked_by, escalated_at, delivery, cell5, recorded_at
FROM alerts
WHERE id = $1::uuid
`

func (q *Queries) GetAlert(ctx context.Context, id pgtype.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FlightID,
		&i.IntentID,
		&i.AuthorisationNumber,
		&i.PeerRef,
		&i.Severity,
		&i.State,
		&i.RaisedAt,
		&i.UpdatedAt,
		&i.ClearedAt,
		&i.ClearReason,
		&i.Detail,
		&i.CapturedAt,
		&i.PolicyVersion,
		&i.AckedAt,
		&i.AckedBy,
		&i.EscalatedAt,
		&i.Delivery,
		&i.Cell5,
		&i.RecordedAt,
	)
	return i, err
}

const recordAlert = `-- name: RecordAlert :one

WITH f AS (
    SELECT id FROM flights WHERE id = $1::uuid
), ins AS (
    INSERT INTO alerts (id, kind, flight_id, intent_id, authorisation_number, peer_ref, severity, state, raised_at, updated_at,
                        cleared_at, clear_reason, detail, captured_at, policy_version, cell5)
    SELECT $2::uuid, $3, f.id,
           (SELECT oi.id FROM operational_intents oi WHERE oi.id = $4::uuid),
           $5, $6, $7, $8, $9,
           $10, $11, $12, $13, $14,
           $15, $16
    FROM f
    ON CONFLICT (id) DO UPDATE
    SET severity = EXCLUDED.severity,
        state = EXCLUDED.state,
        updated_at = GREATEST(alerts.updated_at, EXCLUDED.updated_at),
        cleared_at = EXCLUDED.cleared_at,
        clear_reason = EXCLUDED.clear_reason,
        detail = EXCLUDED.detail,
        captured_at = EXCLUDED.captured_at,
        policy_version = EXCLUDED.policy_version,
        authorisation_number = COALESCE(EXCLUDED.authorisation_number, alerts.authorisation_number),
        peer_ref = COALESCE(EXCLUDED.peer_ref, alerts.peer_ref),
        cell5 = COALESCE(EXCLUDED.cell5, alerts.cell5)
    WHERE alerts.cleared_at IS NULL
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM f) AS flight_known, EXISTS (SELECT 1 FROM ins) AS written
`

type RecordAlertParams struct {
	FlightID            pgtype.UUID `json:"flight_id"`
	ID                  pgtype.UUID `json:"id"`
	Kind                string      `json:"kind"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	PeerRef             *string     `json:"peer_ref"`
	Severity            string      `json:"severity"`
	State               string      `json:"state"`
	RaisedAt            time.Time   `json:"raised_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ClearedAt           *time.Time  `json:"cleared_at"`
	ClearReason         *string     `json:"clear_reason"`
	Detail              []byte      `json:"detail"`
	CapturedAt          *time.Time  `json:"captured_at"`
	PolicyVersion       int64       `json:"policy_version"`
	Cell5               *string     `json:"cell5"`
}

type RecordAlertRow struct {
	FlightKnown bool `json:"flight_known"`
	Written     bool `json:"written"`
}

// Alerts (internal/alerts, WP-11): the record of every alert/v1 the
// monitor publishes, written by api from alrt.v1 (docs/PLAN.md §3.2),
// the operator's acknowledgement and the escalation of an unacknowledged
// critical alert. A row is written only for a flight the flights table
// holds: 0 rows means the flight fact has not been recorded yet and the
// consumer tries again. A cleared row is never reopened by a later
// message (a republish that crossed the clear); acknowledgement and
// escalation are never undone by a message.
// flight_known is false when the flights table does not hold the flight
// yet (the consumer tries again); written is false for a message on a
// cleared alert, which changes nothing.
func (q *Queries) RecordAlert(ctx context.Context, arg RecordAlertParams) (RecordAlertRow, error) {
	row := q.db.QueryRow(ctx, recordAlert,
		arg.FlightID,
		arg.ID,
		arg.Kind,
		arg.IntentID,
		arg.AuthorisationNumber,
		arg.PeerRef,
		arg.Severity,
		arg.State,
		arg.RaisedAt,
		arg.UpdatedAt,
		arg.ClearedAt,
		arg.ClearReason,
		arg.Detail,
		arg.CapturedAt,
		arg.PolicyVersion,
		arg.Cell5,
	)
	var i RecordAlertRow
	err := row.Scan(&i.FlightKnown, &i.Written)
	return i, err
}

const recordAlertDelivery = `-- name: RecordAlertDelivery :execrows
UPDATE alerts
SET delivery = jsonb_set(delivery, ARRAY[$1::text],
                         COALESCE(delivery -> $1::text, '{}'::jsonb)
                         || jsonb_build_object('sent_at', to_jsonb(COALESCE((delivery -> $1::text ->> 'sent_at')::timestamptz, $2::timestamptz))))
WHERE id = $3::uuid
`

type RecordAlertDeliveryParams struct {
	ClientID string      `json:"client_id"`
	SentAt   time.Time   `json:"sent_at"`
	ID       pgtype.UUID `json:"id"`
}

// The first time an alert was sent to a client (traffic-ws); a later
// send keeps it.
func (q *Queries) RecordAlertDelivery(ctx context.Context, arg RecordAlertDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordAlertDelivery, arg.ClientID, arg.SentAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
