// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conformance.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const conformanceTimeline = `-- name: ConformanceTimeline :many
SELECT at, state, reason, distance_outside_m, height_over_m, time_outside_s, policy_version
FROM conformance_states
WHERE flight_id = $1::uuid
ORDER BY at, id
LIMIT $2
`

type ConformanceTimelineParams struct {
	FlightID pgtype.UUID `json:"flight_id"`
	MaxRows  int32       `json:"max_rows"`
}

type ConformanceTimelineRow struct {
	At               time.Time `json:"at"`
	State            string    `json:"state"`
	Reason           *string   `json:"reason"`
	DistanceOutsideM *float64  `json:"distance_outside_m"`
	HeightOverM      *float64  `json:"height_over_m"`
	TimeOutsideS     *float64  `json:"time_outside_s"`
	PolicyVersion    int64     `json:"policy_version"`
}

func (q *Queries) ConformanceTimeline(ctx context.Context, arg ConformanceTimelineParams) ([]ConformanceTimelineRow, error) {
	rows, err := q.db.Query(ctx, conformanceTimeline, arg.FlightID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConformanceTimelineRow
	for rows.Next() {
		var i ConformanceTimelineRow
		if err := rows.Scan(
			&i.At,
			&i.State,
			&i.Reason,
			&i.DistanceOutsideM,
			&i.HeightOverM,
			&i.TimeOutsideS,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConformanceState = `-- name: InsertConformanceState :execrows

INSERT INTO conformance_states (flight_id, at, state, reason, distance_outside_m, height_over_m, time_outside_s, policy_version)
SELECT f.id, $1, $2, $3,
       $4::double precision, $5::double precision,
       $6::double precision, $7
FROM flights f
WHERE f.id = $8::uuid
`

type InsertConformanceStateParams struct {
	At               time.Time   `json:"at"`
	State            string      `json:"state"`
	Reason           *string     `json:"reason"`
	DistanceOutsideM *float64    `json:"distance_outside_m"`
	HeightOverM      *float64    `json:"height_over_m"`
	TimeOutsideS     *float64    `json:"time_outside_s"`
	PolicyVersion    int64       `json:"policy_version"`
	FlightID         pgtype.UUID `json:"flight_id"`
}

// Conformance (internal/conformance, WP-10): the timeline of a flight's
// conformance states, written by api from conf.v1 (docs/PLAN.md §3.2).
// Append-only (the application role has INSERT and SELECT only). A row
// is written only for a flight the flights table holds: 0 rows means the
// flight fact has not been recorded yet and the consumer tries again.
func (q *Queries) InsertConformanceState(ctx context.Context, arg InsertConformanceStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertConformanceState,
		arg.At,
		arg.State,
		arg.Reason,
		arg.DistanceOutsideM,
		arg.HeightOverM,
		arg.TimeOutsideS,
		arg.PolicyVersion,
		arg.FlightID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
