// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coordination.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const conformanceStateAcknowledged = `-- name: ConformanceStateAcknowledged :exec
UPDATE conformance_states SET ats_ack_ref = $1
WHERE id = $2 AND ats_ack_ref IS NULL
`

type ConformanceStateAcknowledgedParams struct {
	AtsAckRef *string `json:"ats_ack_ref"`
	ID        int64   `json:"id"`
}

func (q *Queries) ConformanceStateAcknowledged(ctx context.Context, arg ConformanceStateAcknowledgedParams) error {
	_, err := q.db.Exec(ctx, conformanceStateAcknowledged, arg.AtsAckRef, arg.ID)
	return err
}

const conformanceStateNotified = `-- name: ConformanceStateNotified :exec
UPDATE conformance_states SET ats_notified_at = now()
WHERE id = $1 AND ats_notified_at IS NULL
`

func (q *Queries) ConformanceStateNotified(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, conformanceStateNotified, id)
	return err
}

const coordinationAcknowledged = `-- name: CoordinationAcknowledged :one
UPDATE coordination_notices
SET state = 'acknowledged', acknowledged_at = now(), ansp_acknowledged_at = $1,
    acknowledged_by = $2, polls = polls + 1, poll_next_at = NULL
WHERE id = $3 AND state IN ('received', 'escalated')
RETURNING conformance_state_id, ack_id, notice_ref, kind, intent_id
`

type CoordinationAcknowledgedParams struct {
	AnspAcknowledgedAt *time.Time `json:"ansp_acknowledged_at"`
	AcknowledgedBy     *string    `json:"acknowledged_by"`
	ID                 int64      `json:"id"`
}

type CoordinationAcknowledgedRow struct {
	ConformanceStateID *int64      `json:"conformance_state_id"`
	AckID              *string     `json:"ack_id"`
	NoticeRef          string      `json:"notice_ref"`
	Kind               string      `json:"kind"`
	IntentID           pgtype.UUID `json:"intent_id"`
}

func (q *Queries) CoordinationAcknowledged(ctx context.Context, arg CoordinationAcknowledgedParams) (CoordinationAcknowledgedRow, error) {
	row := q.db.QueryRow(ctx, coordinationAcknowledged, arg.AnspAcknowledgedAt, arg.AcknowledgedBy, arg.ID)
	var i CoordinationAcknowledgedRow
	err := row.Scan(
		&i.ConformanceStateID,
		&i.AckID,
		&i.NoticeRef,
		&i.Kind,
		&i.IntentID,
	)
	return i, err
}

const coordinationCandidates = `-- name: CoordinationCandidates :many
SELECT i.id, i.authorisation_number, i.local_state, i.dss_state, i.time_start, i.time_end, i.volumes,
       i.uspace_airspace_ids, (i.local_state = 'ended')::boolean AS ended
FROM operational_intents i
WHERE i.authorisation_number IS NOT NULL AND NOT i.exempt_art_1_3
  AND NOT EXISTS (SELECT 1 FROM coordination_checks c WHERE c.intent_id = i.id)
  AND (i.local_state IN ('activated', 'nonconforming', 'contingent')
       OR (i.local_state = 'ended'
           AND i.updated_at > now() - make_interval(secs => $1::double precision)
           AND EXISTS (SELECT 1 FROM intent_versions v WHERE v.intent_id = i.id
                       AND v.snapshot -> 'decision' ->> 'state' IN ('activated', 'nonconforming', 'contingent'))))
ORDER BY i.updated_at, i.id
LIMIT $2
`

type CoordinationCandidatesParams struct {
	LookbackS float64 `json:"lookback_s"`
	N         int32   `json:"n"`
}

type CoordinationCandidatesRow struct {
	ID                  pgtype.UUID `json:"id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	LocalState          string      `json:"local_state"`
	DssState            *string     `json:"dss_state"`
	TimeStart           time.Time   `json:"time_start"`
	TimeEnd             time.Time   `json:"time_end"`
	Volumes             []byte      `json:"volumes"`
	UspaceAirspaceIds   []string    `json:"uspace_airspace_ids"`
	Ended               bool        `json:"ended"`
}

// The authorised intents activated (or later) without a check: the
// active ones, and the ended ones whose versions show an activation and
// that ended within lookback.
func (q *Queries) CoordinationCandidates(ctx context.Context, arg CoordinationCandidatesParams) ([]CoordinationCandidatesRow, error) {
	rows, err := q.db.Query(ctx, coordinationCandidates, arg.LookbackS, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoordinationCandidatesRow
	for rows.Next() {
		var i CoordinationCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorisationNumber,
			&i.LocalState,
			&i.DssState,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Volumes,
			&i.UspaceAirspaceIds,
			&i.Ended,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinationClaim = `-- name: CoordinationClaim :many
UPDATE coordination_notices
SET attempts = attempts + 1,
    next_at = now() + make_interval(secs => $1::double precision)
WHERE id IN (
    SELECT n.id FROM coordination_notices n
    WHERE n.state = 'pending' AND n.next_at <= now()
      AND NOT EXISTS (SELECT 1 FROM coordination_notices e
                      WHERE e.intent_id = n.intent_id AND e.state = 'pending' AND e.id < n.id)
    ORDER BY n.next_at, n.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, notice_ref, kind, intent_id, conformance_state_id, body, attempts
`

type CoordinationClaimParams struct {
	LeaseS float64 `json:"lease_s"`
	N      int32   `json:"n"`
}

type CoordinationClaimRow struct {
	ID                 int64       `json:"id"`
	NoticeRef          string      `json:"notice_ref"`
	Kind               string      `json:"kind"`
	IntentID           pgtype.UUID `json:"intent_id"`
	ConformanceStateID *int64      `json:"conformance_state_id"`
	Body               []byte      `json:"body"`
	Attempts           int32       `json:"attempts"`
}

// Leases up to n due pending notices, each its intent's oldest pending
// one, and counts the try.
func (q *Queries) CoordinationClaim(ctx context.Context, arg CoordinationClaimParams) ([]CoordinationClaimRow, error) {
	rows, err := q.db.Query(ctx, coordinationClaim, arg.LeaseS, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoordinationClaimRow
	for rows.Next() {
		var i CoordinationClaimRow
		if err := rows.Scan(
			&i.ID,
			&i.NoticeRef,
			&i.Kind,
			&i.IntentID,
			&i.ConformanceStateID,
			&i.Body,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinationDuePolls = `-- name: CoordinationDuePolls :many
UPDATE coordination_notices
SET poll_next_at = now() + make_interval(secs => $1::double precision)
WHERE id IN (
    SELECT n.id FROM coordination_notices n
    WHERE n.ack_required AND n.state IN ('received', 'escalated') AND n.poll_next_at <= now()
    ORDER BY n.poll_next_at, n.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, notice_ref, kind, ack_id, conformance_state_id, state, received_at, polls,
          extract(epoch FROM now() - received_at)::double precision AS since_received_s
`

type CoordinationDuePollsParams struct {
	LeaseS float64 `json:"lease_s"`
	N      int32   `json:"n"`
}

type CoordinationDuePollsRow struct {
	ID                 int64      `json:"id"`
	NoticeRef          string     `json:"notice_ref"`
	Kind               string     `json:"kind"`
	AckID              *string    `json:"ack_id"`
	ConformanceStateID *int64     `json:"conformance_state_id"`
	State              string     `json:"state"`
	ReceivedAt         *time.Time `json:"received_at"`
	Polls              int32      `json:"polls"`
	SinceReceivedS     float64    `json:"since_received_s"`
}

// Leases up to n due reads of an acknowledgement for lease_s (another
// replica skips them meanwhile).
func (q *Queries) CoordinationDuePolls(ctx context.Context, arg CoordinationDuePollsParams) ([]CoordinationDuePollsRow, error) {
	rows, err := q.db.Query(ctx, coordinationDuePolls, arg.LeaseS, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoordinationDuePollsRow
	for rows.Next() {
		var i CoordinationDuePollsRow
		if err := rows.Scan(
			&i.ID,
			&i.NoticeRef,
			&i.Kind,
			&i.AckID,
			&i.ConformanceStateID,
			&i.State,
			&i.ReceivedAt,
			&i.Polls,
			&i.SinceReceivedS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinationEnded = `-- name: CoordinationEnded :many
SELECT i.id, i.authorisation_number, i.local_state, i.dss_state, i.time_start, i.time_end, i.volumes
FROM coordination_checks c
JOIN operational_intents i ON i.id = c.intent_id
WHERE c.controlled AND i.local_state = 'ended'
  AND NOT EXISTS (SELECT 1 FROM coordination_notices n WHERE n.intent_id = i.id AND n.kind = 'ended')
ORDER BY i.updated_at, i.id
LIMIT $1
`

type CoordinationEndedRow struct {
	ID                  pgtype.UUID `json:"id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	LocalState          string      `json:"local_state"`
	DssState            *string     `json:"dss_state"`
	TimeStart           time.Time   `json:"time_start"`
	TimeEnd             time.Time   `json:"time_end"`
	Volumes             []byte      `json:"volumes"`
}

// The ended intents judged controlled whose ended notice is not queued.
func (q *Queries) CoordinationEnded(ctx context.Context, n int32) ([]CoordinationEndedRow, error) {
	rows, err := q.db.Query(ctx, coordinationEnded, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoordinationEndedRow
	for rows.Next() {
		var i CoordinationEndedRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorisationNumber,
			&i.LocalState,
			&i.DssState,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Volumes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinationEscalate = `-- name: CoordinationEscalate :many
UPDATE coordination_notices
SET state = 'escalated', escalated_at = now()
WHERE ack_required AND state = 'received'
  AND received_at <= now() - make_interval(secs => $1::double precision)
RETURNING id, notice_ref, kind, intent_id, flight_id, state, created_at, attempts, last_error, ack_id, received_at,
          escalated_at, failed_at, next_at, extract(epoch FROM now() - received_at)::double precision AS age_s
`

type CoordinationEscalateRow struct {
	ID          int64       `json:"id"`
	NoticeRef   string      `json:"notice_ref"`
	Kind        string      `json:"kind"`
	IntentID    pgtype.UUID `json:"intent_id"`
	FlightID    pgtype.UUID `json:"flight_id"`
	State       string      `json:"state"`
	CreatedAt   time.Time   `json:"created_at"`
	Attempts    int32       `json:"attempts"`
	LastError   *string     `json:"last_error"`
	AckID       *string     `json:"ack_id"`
	ReceivedAt  *time.Time  `json:"received_at"`
	EscalatedAt *time.Time  `json:"escalated_at"`
	FailedAt    *time.Time  `json:"failed_at"`
	NextAt      time.Time   `json:"next_at"`
	AgeS        float64     `json:"age_s"`
}

func (q *Queries) CoordinationEscalate(ctx context.Context, afterS float64) ([]CoordinationEscalateRow, error) {
	rows, err := q.db.Query(ctx, coordinationEscalate, afterS)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoordinationEscalateRow
	for rows.Next() {
		var i CoordinationEscalateRow
		if err := rows.Scan(
			&i.ID,
			&i.NoticeRef,
			&i.Kind,
			&i.IntentID,
			&i.FlightID,
			&i.State,
			&i.CreatedAt,
			&i.Attempts,
			&i.LastError,
			&i.AckID,
			&i.ReceivedAt,
			&i.EscalatedAt,
			&i.FailedAt,
			&i.NextAt,
			&i.AgeS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinationFail = `-- name: CoordinationFail :one
UPDATE coordination_notices
SET state = 'failed', failed_at = now(), last_error = $1, poll_next_at = NULL
WHERE id = $2 AND state = 'pending'
RETURNING notice_ref, kind, intent_id
`

type CoordinationFailParams struct {
	LastError *string `json:"last_error"`
	ID        int64   `json:"id"`
}

type CoordinationFailRow struct {
	NoticeRef string      `json:"notice_ref"`
	Kind      string      `json:"kind"`
	IntentID  pgtype.UUID `json:"intent_id"`
}

func (q *Queries) CoordinationFail(ctx context.Context, arg CoordinationFailParams) (CoordinationFailRow, error) {
	row := q.db.QueryRow(ctx, coordinationFail, arg.LastError, arg.ID)
	var i CoordinationFailRow
	err := row.Scan(&i.NoticeRef, &i.Kind, &i.IntentID)
	return i, err
}

const coordinationInsertCheck = `-- name: CoordinationInsertCheck :execrows
INSERT INTO coordination_checks (intent_id, controlled, airspace_ids, unstated_ids, cis_version)
VALUES ($1::uuid, $2, $3::text[], $4::text[],
        $5)
ON CONFLICT (intent_id) DO NOTHING
`

type CoordinationInsertCheckParams struct {
	IntentID    pgtype.UUID `json:"intent_id"`
	Controlled  bool        `json:"controlled"`
	AirspaceIds []string    `json:"airspace_ids"`
	UnstatedIds []string    `json:"unstated_ids"`
	CisVersion  *string     `json:"cis_version"`
}

func (q *Queries) CoordinationInsertCheck(ctx context.Context, arg CoordinationInsertCheckParams) (int64, error) {
	result, err := q.db.Exec(ctx, coordinationInsertCheck,
		arg.IntentID,
		arg.Controlled,
		arg.AirspaceIds,
		arg.UnstatedIds,
		arg.CisVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const coordinationInsertNotice = `-- name: CoordinationInsertNotice :one
INSERT INTO coordination_notices (notice_ref, kind, intent_id, flight_id, conformance_state_id, payload, body, ack_required,
                                  state, failed_at, last_error)
VALUES ($1, $2, $3::uuid, $4::uuid,
        $5::bigint, $6, $7, $8,
        CASE WHEN $9::text IS NULL THEN 'pending' ELSE 'failed' END,
        CASE WHEN $9::text IS NULL THEN NULL ELSE now() END,
        $9::text)
ON CONFLICT (notice_ref) DO NOTHING
RETURNING id
`

type CoordinationInsertNoticeParams struct {
	NoticeRef          string      `json:"notice_ref"`
	Kind               string      `json:"kind"`
	IntentID           pgtype.UUID `json:"intent_id"`
	FlightID           pgtype.UUID `json:"flight_id"`
	ConformanceStateID *int64      `json:"conformance_state_id"`
	Payload            []byte      `json:"payload"`
	Body               []byte      `json:"body"`
	AckRequired        bool        `json:"ack_required"`
	FailReason         *string     `json:"fail_reason"`
}

// Idempotent by notice_ref: a notice queued before is left as it is
// (no row). A notice that could not be built is queued failed.
func (q *Queries) CoordinationInsertNotice(ctx context.Context, arg CoordinationInsertNoticeParams) (int64, error) {
	row := q.db.QueryRow(ctx, coordinationInsertNotice,
		arg.NoticeRef,
		arg.Kind,
		arg.IntentID,
		arg.FlightID,
		arg.ConformanceStateID,
		arg.Payload,
		arg.Body,
		arg.AckRequired,
		arg.FailReason,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const coordinationOpen = `-- name: CoordinationOpen :many
SELECT id, notice_ref, kind, intent_id, flight_id, state, created_at, attempts, last_error, ack_id, received_at,
       escalated_at, failed_at, next_at,
       extract(epoch FROM now() - coalesce(CASE WHEN state = 'escalated' THEN received_at END, created_at))::double precision AS age_s
FROM coordination_notices
WHERE state IN ('pending', 'escalated', 'failed')
ORDER BY created_at, id
LIMIT $1
`

type CoordinationOpenRow struct {
	ID          int64       `json:"id"`
	NoticeRef   string      `json:"notice_ref"`
	Kind        string      `json:"kind"`
	IntentID    pgtype.UUID `json:"intent_id"`
	FlightID    pgtype.UUID `json:"flight_id"`
	State       string      `json:"state"`
	CreatedAt   time.Time   `json:"created_at"`
	Attempts    int32       `json:"attempts"`
	LastError   *string     `json:"last_error"`
	AckID       *string     `json:"ack_id"`
	ReceivedAt  *time.Time  `json:"received_at"`
	EscalatedAt *time.Time  `json:"escalated_at"`
	FailedAt    *time.Time  `json:"failed_at"`
	NextAt      time.Time   `json:"next_at"`
	AgeS        float64     `json:"age_s"`
}

// The notices the console must see, oldest first. The age of an
// escalated notice runs from its receipt, of the others from their
// queueing.
func (q *Queries) CoordinationOpen(ctx context.Context, n int32) ([]CoordinationOpenRow, error) {
	rows, err := q.db.Query(ctx, coordinationOpen, n)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoordinationOpenRow
	for rows.Next() {
		var i CoordinationOpenRow
		if err := rows.Scan(
			&i.ID,
			&i.NoticeRef,
			&i.Kind,
			&i.IntentID,
			&i.FlightID,
			&i.State,
			&i.CreatedAt,
			&i.Attempts,
			&i.LastError,
			&i.AckID,
			&i.ReceivedAt,
			&i.EscalatedAt,
			&i.FailedAt,
			&i.NextAt,
			&i.AgeS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const coordinationPolled = `-- name: CoordinationPolled :execrows
UPDATE coordination_notices
SET polls = polls + 1,
    poll_next_at = CASE WHEN $1::double precision > 0
                        THEN now() + make_interval(secs => $1::double precision) END
WHERE id = $2 AND state IN ('received', 'escalated')
`

type CoordinationPolledParams struct {
	NextS float64 `json:"next_s"`
	ID    int64   `json:"id"`
}

func (q *Queries) CoordinationPolled(ctx context.Context, arg CoordinationPolledParams) (int64, error) {
	result, err := q.db.Exec(ctx, coordinationPolled, arg.NextS, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const coordinationReceived = `-- name: CoordinationReceived :one
UPDATE coordination_notices
SET state = 'received', ack_id = $1, received_at = now(), ansp_received_at = $2,
    last_error = NULL,
    poll_next_at = CASE WHEN ack_required AND $3::double precision > 0
                        THEN now() + make_interval(secs => $3::double precision) END
WHERE id = $4 AND state = 'pending'
RETURNING conformance_state_id, notice_ref, kind, intent_id
`

type CoordinationReceivedParams struct {
	AckID          *string    `json:"ack_id"`
	AnspReceivedAt *time.Time `json:"ansp_received_at"`
	PollS          float64    `json:"poll_s"`
	ID             int64      `json:"id"`
}

type CoordinationReceivedRow struct {
	ConformanceStateID *int64      `json:"conformance_state_id"`
	NoticeRef          string      `json:"notice_ref"`
	Kind               string      `json:"kind"`
	IntentID           pgtype.UUID `json:"intent_id"`
}

func (q *Queries) CoordinationReceived(ctx context.Context, arg CoordinationReceivedParams) (CoordinationReceivedRow, error) {
	row := q.db.QueryRow(ctx, coordinationReceived,
		arg.AckID,
		arg.AnspReceivedAt,
		arg.PollS,
		arg.ID,
	)
	var i CoordinationReceivedRow
	err := row.Scan(
		&i.ConformanceStateID,
		&i.NoticeRef,
		&i.Kind,
		&i.IntentID,
	)
	return i, err
}

const coordinationRetry = `-- name: CoordinationRetry :execrows
UPDATE coordination_notices
SET next_at = now() + make_interval(secs => $1::double precision), last_error = $2
WHERE id = $3 AND state = 'pending'
`

type CoordinationRetryParams struct {
	BackoffS  float64 `json:"backoff_s"`
	LastError *string `json:"last_error"`
	ID        int64   `json:"id"`
}

func (q *Queries) CoordinationRetry(ctx context.Context, arg CoordinationRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, coordinationRetry, arg.BackoffS, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const coordinationSummary = `-- name: CoordinationSummary :one
SELECT count(*) FILTER (WHERE state = 'pending')::integer AS pending,
       count(*) FILTER (WHERE state = 'pending' AND last_error IS NOT NULL)::integer AS retrying,
       coalesce(extract(epoch FROM now() - min(created_at) FILTER (WHERE state = 'pending')), 0)::double precision AS oldest_pending_s,
       count(*) FILTER (WHERE state = 'escalated' AND created_at > now() - interval '24 hours')::integer AS escalated,
       count(*) FILTER (WHERE state = 'failed' AND created_at > now() - interval '24 hours')::integer AS failed
FROM coordination_notices
WHERE state IN ('pending', 'escalated', 'failed')
`

type CoordinationSummaryRow struct {
	Pending        int32   `json:"pending"`
	Retrying       int32   `json:"retrying"`
	OldestPendingS float64 `json:"oldest_pending_s"`
	Escalated      int32   `json:"escalated"`
	Failed         int32   `json:"failed"`
}

// Escalated and failed notices count on /readyz for a day.
func (q *Queries) CoordinationSummary(ctx context.Context) (CoordinationSummaryRow, error) {
	row := q.db.QueryRow(ctx, coordinationSummary)
	var i CoordinationSummaryRow
	err := row.Scan(
		&i.Pending,
		&i.Retrying,
		&i.OldestPendingS,
		&i.Escalated,
		&i.Failed,
	)
	return i, err
}

const coordinationTransitions = `-- name: CoordinationTransitions :many

SELECT cs.id, cs.flight_id, cs.at, cs.state, cs.reason, cs.distance_outside_m, cs.height_over_m,
       cs.last_lat_deg, cs.last_lng_deg,
       i.id AS intent_id, i.authorisation_number, i.local_state, i.dss_state, i.time_start, i.time_end, i.volumes
FROM conformance_states cs
JOIN flights f ON f.id = cs.flight_id
JOIN operational_intents i ON i.id = f.intent_id
WHERE cs.state IN ('nonconforming', 'lost_link', 'contingent')
  AND cs.at > now() - make_interval(secs => $1::double precision)
  AND i.authorisation_number IS NOT NULL AND NOT i.exempt_art_1_3
  AND NOT EXISTS (SELECT 1 FROM coordination_notices n WHERE n.conformance_state_id = cs.id)
  AND (CASE WHEN cs.state = 'contingent' THEN 'contingent' ELSE 'nonconformance' END) IS DISTINCT FROM (
      SELECT CASE WHEN p.state = 'contingent' THEN 'contingent'
                  WHEN p.state IN ('nonconforming', 'lost_link') THEN 'nonconformance' END
      FROM conformance_states p
      WHERE p.flight_id = cs.flight_id AND (p.at, p.id) < (cs.at, cs.id)
      ORDER BY p.at DESC, p.id DESC
      LIMIT 1)
ORDER BY cs.at, cs.id
LIMIT $2
`

type CoordinationTransitionsParams struct {
	LookbackS float64 `json:"lookback_s"`
	N         int32   `json:"n"`
}

type CoordinationTransitionsRow struct {
	ID                  int64       `json:"id"`
	FlightID            pgtype.UUID `json:"flight_id"`
	At                  time.Time   `json:"at"`
	State               string      `json:"state"`
	Reason              *string     `json:"reason"`
	DistanceOutsideM    *float64    `json:"distance_outside_m"`
	HeightOverM         *float64    `json:"height_over_m"`
	LastLatDeg          *float64    `json:"last_lat_deg"`
	LastLngDeg          *float64    `json:"last_lng_deg"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	LocalState          string      `json:"local_state"`
	DssState            *string     `json:"dss_state"`
	TimeStart           time.Time   `json:"time_start"`
	TimeEnd             time.Time   `json:"time_end"`
	Volumes             []byte      `json:"volumes"`
}

// Annex V coordination with the ANSP (internal/coordination, WP-15):
// the checks, the notices outbox and the two facts a notice writes on
// its conformance state. Every time is the database clock.
// The conformance states recorded within lookback that enter a deviation
// kind (nonconforming or lost_link: nonconformance; contingent:
// contingent) from a state of another kind (or from none), of a flight
// of an authorised intent, without a notice yet.
func (q *Queries) CoordinationTransitions(ctx context.Context, arg CoordinationTransitionsParams) ([]CoordinationTransitionsRow, error) {
	rows, err := q.db.Query(ctx, coordinationTransitions, arg.LookbackS, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CoordinationTransitionsRow
	for rows.Next() {
		var i CoordinationTransitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.FlightID,
			&i.At,
			&i.State,
			&i.Reason,
			&i.DistanceOutsideM,
			&i.HeightOverM,
			&i.LastLatDeg,
			&i.LastLngDeg,
			&i.IntentID,
			&i.AuthorisationNumber,
			&i.LocalState,
			&i.DssState,
			&i.TimeStart,
			&i.TimeEnd,
			&i.Volumes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
