// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dss.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const constraintDelete = `-- name: ConstraintDelete :execrows
DELETE FROM constraints WHERE entity_id = $1 AND manager = $2
`

type ConstraintDeleteParams struct {
	EntityID string `json:"entity_id"`
	Manager  string `json:"manager"`
}

func (q *Queries) ConstraintDelete(ctx context.Context, arg ConstraintDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, constraintDelete, arg.EntityID, arg.Manager)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const constraintGet = `-- name: ConstraintGet :one
SELECT entity_id, manager, ovn, version, time_start, time_end, details, cis_restriction_id, uss_base_url, fetched_at
FROM constraints
WHERE entity_id = $1
`

type ConstraintGetRow struct {
	EntityID         string     `json:"entity_id"`
	Manager          string     `json:"manager"`
	Ovn              *string    `json:"ovn"`
	Version          *int64     `json:"version"`
	TimeStart        *time.Time `json:"time_start"`
	TimeEnd          *time.Time `json:"time_end"`
	Details          []byte     `json:"details"`
	CisRestrictionID *string    `json:"cis_restriction_id"`
	UssBaseUrl       *string    `json:"uss_base_url"`
	FetchedAt        time.Time  `json:"fetched_at"`
}

func (q *Queries) ConstraintGet(ctx context.Context, entityID string) (ConstraintGetRow, error) {
	row := q.db.QueryRow(ctx, constraintGet, entityID)
	var i ConstraintGetRow
	err := row.Scan(
		&i.EntityID,
		&i.Manager,
		&i.Ovn,
		&i.Version,
		&i.TimeStart,
		&i.TimeEnd,
		&i.Details,
		&i.CisRestrictionID,
		&i.UssBaseUrl,
		&i.FetchedAt,
	)
	return i, err
}

const constraintUpsert = `-- name: ConstraintUpsert :execrows
INSERT INTO constraints (entity_id, manager, ovn, version, time_start, time_end, details, cis_restriction_id,
                         uss_base_url, fetched_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, now())
ON CONFLICT (entity_id) DO UPDATE
SET manager = EXCLUDED.manager, ovn = EXCLUDED.ovn, version = EXCLUDED.version, time_start = EXCLUDED.time_start,
    time_end = EXCLUDED.time_end, details = EXCLUDED.details, cis_restriction_id = EXCLUDED.cis_restriction_id,
    uss_base_url = EXCLUDED.uss_base_url, fetched_at = now()
WHERE constraints.version IS NULL OR EXCLUDED.version >= constraints.version
`

type ConstraintUpsertParams struct {
	EntityID         string     `json:"entity_id"`
	Manager          string     `json:"manager"`
	Ovn              *string    `json:"ovn"`
	Version          *int64     `json:"version"`
	TimeStart        *time.Time `json:"time_start"`
	TimeEnd          *time.Time `json:"time_end"`
	Details          []byte     `json:"details"`
	CisRestrictionID *string    `json:"cis_restriction_id"`
	UssBaseUrl       *string    `json:"uss_base_url"`
}

func (q *Queries) ConstraintUpsert(ctx context.Context, arg ConstraintUpsertParams) (int64, error) {
	result, err := q.db.Exec(ctx, constraintUpsert,
		arg.EntityID,
		arg.Manager,
		arg.Ovn,
		arg.Version,
		arg.TimeStart,
		arg.TimeEnd,
		arg.Details,
		arg.CisRestrictionID,
		arg.UssBaseUrl,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const constraintsOverlapping = `-- name: ConstraintsOverlapping :many
SELECT entity_id, details, fetched_at
FROM constraints
WHERE fetched_at > $1::timestamptz
  AND time_start <= $2::timestamptz AND time_end >= $3::timestamptz
ORDER BY fetched_at, entity_id
LIMIT $4
`

type ConstraintsOverlappingParams struct {
	Since   time.Time `json:"since"`
	ToAt    time.Time `json:"to_at"`
	FromAt  time.Time `json:"from_at"`
	MaxRows int32     `json:"max_rows"`
}

type ConstraintsOverlappingRow struct {
	EntityID  string    `json:"entity_id"`
	Details   []byte    `json:"details"`
	FetchedAt time.Time `json:"fetched_at"`
}

// The constraints whose window overlaps [from_at, to_at] fetched after
// since, for the deconfliction of an intent written to the DSS.
func (q *Queries) ConstraintsOverlapping(ctx context.Context, arg ConstraintsOverlappingParams) ([]ConstraintsOverlappingRow, error) {
	rows, err := q.db.Query(ctx, constraintsOverlapping,
		arg.Since,
		arg.ToAt,
		arg.FromAt,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConstraintsOverlappingRow
	for rows.Next() {
		var i ConstraintsOverlappingRow
		if err := rows.Scan(&i.EntityID, &i.Details, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const constraintsPurge = `-- name: ConstraintsPurge :execrows
DELETE FROM constraints c
WHERE c.fetched_at < $1::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM operational_intents o
      WHERE o.conflicts @> jsonb_build_array(jsonb_build_object('ref', 'constraint:' || c.entity_id)))
`

func (q *Queries) ConstraintsPurge(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, constraintsPurge, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dSSStateGet = `-- name: DSSStateGet :one
SELECT uss_availability, set_by, set_at, dss_reachable_since, dss_unreachable_since
FROM dss_state WHERE singleton
`

type DSSStateGetRow struct {
	UssAvailability     *string    `json:"uss_availability"`
	SetBy               *string    `json:"set_by"`
	SetAt               *time.Time `json:"set_at"`
	DssReachableSince   *time.Time `json:"dss_reachable_since"`
	DssUnreachableSince *time.Time `json:"dss_unreachable_since"`
}

func (q *Queries) DSSStateGet(ctx context.Context) (DSSStateGetRow, error) {
	row := q.db.QueryRow(ctx, dSSStateGet)
	var i DSSStateGetRow
	err := row.Scan(
		&i.UssAvailability,
		&i.SetBy,
		&i.SetAt,
		&i.DssReachableSince,
		&i.DssUnreachableSince,
	)
	return i, err
}

const dSSStateSetAvailability = `-- name: DSSStateSetAvailability :execrows
UPDATE dss_state
SET uss_availability = $1, set_by = $2, set_at = now()
WHERE singleton AND uss_availability IS DISTINCT FROM $1
`

type DSSStateSetAvailabilityParams struct {
	Availability *string `json:"availability"`
	SetBy        *string `json:"set_by"`
}

func (q *Queries) DSSStateSetAvailability(ctx context.Context, arg DSSStateSetAvailabilityParams) (int64, error) {
	result, err := q.db.Exec(ctx, dSSStateSetAvailability, arg.Availability, arg.SetBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const dSSStateSetReachable = `-- name: DSSStateSetReachable :execrows
UPDATE dss_state
SET dss_reachable_since = CASE WHEN $1::boolean THEN COALESCE(dss_reachable_since, now()) ELSE NULL END,
    dss_unreachable_since = CASE WHEN $1::boolean THEN NULL ELSE COALESCE(dss_unreachable_since, now()) END
WHERE singleton
`

func (q *Queries) DSSStateSetReachable(ctx context.Context, up bool) (int64, error) {
	result, err := q.db.Exec(ctx, dSSStateSetReachable, up)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exchangeInsert = `-- name: ExchangeInsert :exec
INSERT INTO dss_exchanges (entity_id, recorder_role, method, url, request_body, request_time, response_code,
                           response_body, response_time, problem)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9,
        $10)
`

type ExchangeInsertParams struct {
	EntityID     *string    `json:"entity_id"`
	RecorderRole string     `json:"recorder_role"`
	Method       string     `json:"method"`
	Url          string     `json:"url"`
	RequestBody  *string    `json:"request_body"`
	RequestTime  time.Time  `json:"request_time"`
	ResponseCode *int32     `json:"response_code"`
	ResponseBody *string    `json:"response_body"`
	ResponseTime *time.Time `json:"response_time"`
	Problem      *string    `json:"problem"`
}

func (q *Queries) ExchangeInsert(ctx context.Context, arg ExchangeInsertParams) error {
	_, err := q.db.Exec(ctx, exchangeInsert,
		arg.EntityID,
		arg.RecorderRole,
		arg.Method,
		arg.Url,
		arg.RequestBody,
		arg.RequestTime,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.ResponseTime,
		arg.Problem,
	)
	return err
}

const exchangesByEntity = `-- name: ExchangesByEntity :many
SELECT id, entity_id, recorder_role, method, url, request_body, request_time, response_code, response_body,
       response_time, problem
FROM dss_exchanges
WHERE entity_id = $1
ORDER BY id
LIMIT $2
`

type ExchangesByEntityParams struct {
	EntityID *string `json:"entity_id"`
	MaxRows  int32   `json:"max_rows"`
}

type ExchangesByEntityRow struct {
	ID           int64      `json:"id"`
	EntityID     *string    `json:"entity_id"`
	RecorderRole string     `json:"recorder_role"`
	Method       string     `json:"method"`
	Url          string     `json:"url"`
	RequestBody  *string    `json:"request_body"`
	RequestTime  time.Time  `json:"request_time"`
	ResponseCode *int32     `json:"response_code"`
	ResponseBody *string    `json:"response_body"`
	ResponseTime *time.Time `json:"response_time"`
	Problem      *string    `json:"problem"`
}

func (q *Queries) ExchangesByEntity(ctx context.Context, arg ExchangesByEntityParams) ([]ExchangesByEntityRow, error) {
	rows, err := q.db.Query(ctx, exchangesByEntity, arg.EntityID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExchangesByEntityRow
	for rows.Next() {
		var i ExchangesByEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.RecorderRole,
			&i.Method,
			&i.Url,
			&i.RequestBody,
			&i.RequestTime,
			&i.ResponseCode,
			&i.ResponseBody,
			&i.ResponseTime,
			&i.Problem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const exchangesPurgeBefore = `-- name: ExchangesPurgeBefore :execrows
DELETE FROM dss_exchanges WHERE recorded_at < $1::timestamptz
`

func (q *Queries) ExchangesPurgeBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, exchangesPurgeBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const exchangesPurgeBeyond = `-- name: ExchangesPurgeBeyond :execrows
DELETE FROM dss_exchanges
WHERE id < (SELECT e.id FROM dss_exchanges e ORDER BY e.id DESC OFFSET $1::bigint LIMIT 1)
`

// Keeps the newest max_rows exchanges.
func (q *Queries) ExchangesPurgeBeyond(ctx context.Context, maxRows int64) (int64, error) {
	result, err := q.db.Exec(ctx, exchangesPurgeBeyond, maxRows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const intentClearDSSHeld = `-- name: IntentClearDSSHeld :execrows
UPDATE operational_intents
SET dss_held_state = NULL, dss_ovn = NULL, dss_reference = NULL, dss_extents = NULL,
    dss_subscription_id = NULL, dss_written_at = now(), dss_last_error = NULL
WHERE id = $1::uuid
`

// The DSS no longer holds the intent (deleted, or never held).
func (q *Queries) IntentClearDSSHeld(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, intentClearDSSHeld, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const intentDSSHeld = `-- name: IntentDSSHeld :one

SELECT id, version, local_state, dss_held_state, dss_ovn, dss_version, dss_reference, dss_extents,
       dss_subscription_id, dss_written_at, dss_last_error
FROM operational_intents
WHERE id = $1::uuid
`

type IntentDSSHeldRow struct {
	ID                pgtype.UUID `json:"id"`
	Version           int32       `json:"version"`
	LocalState        string      `json:"local_state"`
	DssHeldState      *string     `json:"dss_held_state"`
	DssOvn            *string     `json:"dss_ovn"`
	DssVersion        *int64      `json:"dss_version"`
	DssReference      []byte      `json:"dss_reference"`
	DssExtents        []byte      `json:"dss_extents"`
	DssSubscriptionID *string     `json:"dss_subscription_id"`
	DssWrittenAt      *time.Time  `json:"dss_written_at"`
	DssLastError      *string     `json:"dss_last_error"`
}

// F3548 strategic coordination through the DSS (internal/dss, brief
// WP-13): what the DSS holds of each intent, the peers' intents and
// constraints, the subscriptions, this USSP's availability, the exchange
// log and the reports. Times come from the database clock.
func (q *Queries) IntentDSSHeld(ctx context.Context, id pgtype.UUID) (IntentDSSHeldRow, error) {
	row := q.db.QueryRow(ctx, intentDSSHeld, id)
	var i IntentDSSHeldRow
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.LocalState,
		&i.DssHeldState,
		&i.DssOvn,
		&i.DssVersion,
		&i.DssReference,
		&i.DssExtents,
		&i.DssSubscriptionID,
		&i.DssWrittenAt,
		&i.DssLastError,
	)
	return i, err
}

const intentDSSIsHeld = `-- name: IntentDSSIsHeld :one
SELECT EXISTS (SELECT 1 FROM operational_intents WHERE id = $1::uuid AND dss_ovn IS NOT NULL)::boolean AS held
`

// Whether the DSS holds the intent (an OIR to delete or update).
func (q *Queries) IntentDSSIsHeld(ctx context.Context, id pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, intentDSSIsHeld, id)
	var held bool
	err := row.Scan(&held)
	return held, err
}

const intentNewestFlight = `-- name: IntentNewestFlight :one
SELECT id, started_at, ended_at
FROM flights
WHERE intent_id = $1::uuid
ORDER BY started_at DESC
LIMIT 1
`

type IntentNewestFlightRow struct {
	ID        pgtype.UUID `json:"id"`
	StartedAt time.Time   `json:"started_at"`
	EndedAt   *time.Time  `json:"ended_at"`
}

// The newest flight of an intent (the telemetry of
// GET /uss/v1/operational_intents/{id}/telemetry).
func (q *Queries) IntentNewestFlight(ctx context.Context, intentID pgtype.UUID) (IntentNewestFlightRow, error) {
	row := q.db.QueryRow(ctx, intentNewestFlight, intentID)
	var i IntentNewestFlightRow
	err := row.Scan(&i.ID, &i.StartedAt, &i.EndedAt)
	return i, err
}

const intentPreviousNumber = `-- name: IntentPreviousNumber :one
SELECT (snapshot->'decision'->>'authorisation_number')::text AS number
FROM intent_versions
WHERE intent_id = $1::uuid AND snapshot->'decision'->>'authorisation_number' IS NOT NULL
ORDER BY version DESC
LIMIT 1
`

// The newest authorisation number an earlier version of the intent
// carried (Art. 6(6): a modification keeps it).
func (q *Queries) IntentPreviousNumber(ctx context.Context, intentID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, intentPreviousNumber, intentID)
	var number string
	err := row.Scan(&number)
	return number, err
}

const intentSetDSSError = `-- name: IntentSetDSSError :exec
UPDATE operational_intents SET dss_last_error = $1
WHERE id = $2::uuid
`

type IntentSetDSSErrorParams struct {
	LastError *string     `json:"last_error"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) IntentSetDSSError(ctx context.Context, arg IntentSetDSSErrorParams) error {
	_, err := q.db.Exec(ctx, intentSetDSSError, arg.LastError, arg.ID)
	return err
}

const intentSetDSSHeld = `-- name: IntentSetDSSHeld :execrows
UPDATE operational_intents
SET dss_held_state = $1, dss_ovn = $2, dss_version = $3,
    dss_reference = $4, dss_extents = $5,
    dss_subscription_id = $6, dss_written_at = now(), dss_last_error = NULL
WHERE id = $7::uuid
`

type IntentSetDSSHeldParams struct {
	HeldState      *string     `json:"held_state"`
	Ovn            *string     `json:"ovn"`
	DssVersion     *int64      `json:"dss_version"`
	Reference      []byte      `json:"reference"`
	Extents        []byte      `json:"extents"`
	SubscriptionID *string     `json:"subscription_id"`
	ID             pgtype.UUID `json:"id"`
}

// What the DSS answered to a write of the intent: written only after the
// DSS answer, never in the decision's transaction.
func (q *Queries) IntentSetDSSHeld(ctx context.Context, arg IntentSetDSSHeldParams) (int64, error) {
	result, err := q.db.Exec(ctx, intentSetDSSHeld,
		arg.HeldState,
		arg.Ovn,
		arg.DssVersion,
		arg.Reference,
		arg.Extents,
		arg.SubscriptionID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxDoneByKey = `-- name: MarkOutboxDoneByKey :execrows
UPDATE dss_outbox SET done_at = now(), last_error = NULL
WHERE kind = $1 AND entity_id = $2 AND entity_version = $3
  AND done_at IS NULL
`

type MarkOutboxDoneByKeyParams struct {
	Kind          string `json:"kind"`
	EntityID      string `json:"entity_id"`
	EntityVersion int64  `json:"entity_version"`
}

func (q *Queries) MarkOutboxDoneByKey(ctx context.Context, arg MarkOutboxDoneByKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxDoneByKey, arg.Kind, arg.EntityID, arg.EntityVersion)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const outboxOldestDue = `-- name: OutboxOldestDue :one
SELECT count(*)::bigint AS pending,
       COALESCE(EXTRACT(EPOCH FROM now() - min(created_at)), 0)::double precision AS oldest_age_s,
       COALESCE(max(attempts), 0)::integer AS max_attempts
FROM dss_outbox
WHERE done_at IS NULL AND kind = ANY ($1::text[])
`

type OutboxOldestDueRow struct {
	Pending     int64   `json:"pending"`
	OldestAgeS  float64 `json:"oldest_age_s"`
	MaxAttempts int32   `json:"max_attempts"`
}

func (q *Queries) OutboxOldestDue(ctx context.Context, kinds []string) (OutboxOldestDueRow, error) {
	row := q.db.QueryRow(ctx, outboxOldestDue, kinds)
	var i OutboxOldestDueRow
	err := row.Scan(&i.Pending, &i.OldestAgeS, &i.MaxAttempts)
	return i, err
}

const peerIntentDelete = `-- name: PeerIntentDelete :execrows
DELETE FROM peer_intents WHERE entity_id = $1 AND manager = $2
`

type PeerIntentDeleteParams struct {
	EntityID string `json:"entity_id"`
	Manager  string `json:"manager"`
}

// A deleted reference removes the peer's intent, only its manager's.
func (q *Queries) PeerIntentDelete(ctx context.Context, arg PeerIntentDeleteParams) (int64, error) {
	result, err := q.db.Exec(ctx, peerIntentDelete, arg.EntityID, arg.Manager)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const peerIntentGet = `-- name: PeerIntentGet :one
SELECT entity_id, manager, uss_base_url, state, ovn, version, time_start, time_end, details, fetched_at,
       peer_unavailable, priority
FROM peer_intents
WHERE entity_id = $1
`

func (q *Queries) PeerIntentGet(ctx context.Context, entityID string) (PeerIntent, error) {
	row := q.db.QueryRow(ctx, peerIntentGet, entityID)
	var i PeerIntent
	err := row.Scan(
		&i.EntityID,
		&i.Manager,
		&i.UssBaseUrl,
		&i.State,
		&i.Ovn,
		&i.Version,
		&i.TimeStart,
		&i.TimeEnd,
		&i.Details,
		&i.FetchedAt,
		&i.PeerUnavailable,
		&i.Priority,
	)
	return i, err
}

const peerIntentUpsert = `-- name: PeerIntentUpsert :execrows
INSERT INTO peer_intents (entity_id, manager, uss_base_url, state, ovn, version, time_start, time_end, details,
                          priority, fetched_at, peer_unavailable)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10, now(), false)
ON CONFLICT (entity_id) DO UPDATE
SET manager = EXCLUDED.manager, uss_base_url = EXCLUDED.uss_base_url, state = EXCLUDED.state, ovn = EXCLUDED.ovn,
    version = EXCLUDED.version, time_start = EXCLUDED.time_start, time_end = EXCLUDED.time_end,
    details = EXCLUDED.details, priority = EXCLUDED.priority, fetched_at = now(), peer_unavailable = false
WHERE peer_intents.version IS NULL OR EXCLUDED.version >= peer_intents.version
`

type PeerIntentUpsertParams struct {
	EntityID   string     `json:"entity_id"`
	Manager    string     `json:"manager"`
	UssBaseUrl string     `json:"uss_base_url"`
	State      *string    `json:"state"`
	Ovn        *string    `json:"ovn"`
	Version    *int64     `json:"version"`
	TimeStart  *time.Time `json:"time_start"`
	TimeEnd    *time.Time `json:"time_end"`
	Details    []byte     `json:"details"`
	Priority   int32      `json:"priority"`
}

// A peer's intent as its manager gave it (trust: provider), newer
// versions only: an older version never replaces a newer one. fetched_at
// is the database clock; peer_unavailable is cleared by an answer.
func (q *Queries) PeerIntentUpsert(ctx context.Context, arg PeerIntentUpsertParams) (int64, error) {
	result, err := q.db.Exec(ctx, peerIntentUpsert,
		arg.EntityID,
		arg.Manager,
		arg.UssBaseUrl,
		arg.State,
		arg.Ovn,
		arg.Version,
		arg.TimeStart,
		arg.TimeEnd,
		arg.Details,
		arg.Priority,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const peerIntentsMarkUnavailable = `-- name: PeerIntentsMarkUnavailable :execrows
UPDATE peer_intents SET peer_unavailable = $1
WHERE uss_base_url = $2 AND peer_unavailable <> $1
`

type PeerIntentsMarkUnavailableParams struct {
	Unavailable bool   `json:"unavailable"`
	UssBaseUrl  string `json:"uss_base_url"`
}

// A peer that does not answer: its intents are kept (they still count
// until time_end) and marked; an answer clears the mark.
func (q *Queries) PeerIntentsMarkUnavailable(ctx context.Context, arg PeerIntentsMarkUnavailableParams) (int64, error) {
	result, err := q.db.Exec(ctx, peerIntentsMarkUnavailable, arg.Unavailable, arg.UssBaseUrl)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const peerIntentsPurge = `-- name: PeerIntentsPurge :execrows
DELETE FROM peer_intents p
WHERE p.fetched_at < $1::timestamptz
  AND NOT EXISTS (
      SELECT 1 FROM operational_intents o
      WHERE o.conflicts @> jsonb_build_array(jsonb_build_object('ref', 'peer:' || p.entity_id)))
`

// Peer data older than before (F3548 ExternalDataMaxRetentionTimeHours)
// that no decision record names: a decision copies what it relied on
// into operational_intents.conflicts (ref "peer:<entity_id>"), and a row
// it names is kept.
func (q *Queries) PeerIntentsPurge(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, peerIntentsPurge, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const peerIntentsUnavailable = `-- name: PeerIntentsUnavailable :many
SELECT entity_id, uss_base_url, time_end
FROM peer_intents
WHERE peer_unavailable AND time_end >= now()
ORDER BY entity_id
LIMIT $1
`

type PeerIntentsUnavailableRow struct {
	EntityID   string     `json:"entity_id"`
	UssBaseUrl string     `json:"uss_base_url"`
	TimeEnd    *time.Time `json:"time_end"`
}

// The peers' intents of a window, with their mark, for the peer view.
func (q *Queries) PeerIntentsUnavailable(ctx context.Context, maxRows int32) ([]PeerIntentsUnavailableRow, error) {
	rows, err := q.db.Query(ctx, peerIntentsUnavailable, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PeerIntentsUnavailableRow
	for rows.Next() {
		var i PeerIntentsUnavailableRow
		if err := rows.Scan(&i.EntityID, &i.UssBaseUrl, &i.TimeEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportInsert = `-- name: ReportInsert :exec
INSERT INTO uss_reports (report_id, reporter, exchange)
VALUES ($1::uuid, $2, $3)
`

type ReportInsertParams struct {
	ReportID pgtype.UUID `json:"report_id"`
	Reporter string      `json:"reporter"`
	Exchange []byte      `json:"exchange"`
}

func (q *Queries) ReportInsert(ctx context.Context, arg ReportInsertParams) error {
	_, err := q.db.Exec(ctx, reportInsert, arg.ReportID, arg.Reporter, arg.Exchange)
	return err
}

const reportsPurgeBefore = `-- name: ReportsPurgeBefore :execrows
DELETE FROM uss_reports WHERE received_at < $1::timestamptz
`

func (q *Queries) ReportsPurgeBefore(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, reportsPurgeBefore, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subscriptionDelete = `-- name: SubscriptionDelete :execrows
DELETE FROM dss_subscriptions WHERE subscription_id = $1 AND kind = 'utm'
`

func (q *Queries) SubscriptionDelete(ctx context.Context, subscriptionID string) (int64, error) {
	result, err := q.db.Exec(ctx, subscriptionDelete, subscriptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const subscriptionNotified = `-- name: SubscriptionNotified :one
UPDATE dss_subscriptions s
SET notification_index = GREATEST(s.notification_index, $1::integer)
FROM (SELECT d.subscription_id AS sid, d.notification_index AS previous
      FROM dss_subscriptions d
      WHERE d.subscription_id = $2
      FOR UPDATE) old
WHERE s.subscription_id = old.sid
RETURNING old.previous::integer AS previous
`

type SubscriptionNotifiedParams struct {
	Idx            int32  `json:"idx"`
	SubscriptionID string `json:"subscription_id"`
}

// The notification index of one of our subscriptions, advanced to idx;
// the index held before, and false when the subscription is not ours.
func (q *Queries) SubscriptionNotified(ctx context.Context, arg SubscriptionNotifiedParams) (int32, error) {
	row := q.db.QueryRow(ctx, subscriptionNotified, arg.Idx, arg.SubscriptionID)
	var previous int32
	err := row.Scan(&previous)
	return previous, err
}

const subscriptionUpsert = `-- name: SubscriptionUpsert :exec
INSERT INTO dss_subscriptions (subscription_id, kind, area, version, notification_index, time_end, uss_base_url, renewed_at)
VALUES ($1, 'utm', $2, $3, $4,
        $5, $6, now())
ON CONFLICT (subscription_id) DO UPDATE
SET area = EXCLUDED.area, version = EXCLUDED.version,
    notification_index = GREATEST(dss_subscriptions.notification_index, EXCLUDED.notification_index),
    time_end = EXCLUDED.time_end, uss_base_url = EXCLUDED.uss_base_url, renewed_at = now()
`

type SubscriptionUpsertParams struct {
	SubscriptionID    string    `json:"subscription_id"`
	Area              []byte    `json:"area"`
	Version           *string   `json:"version"`
	NotificationIndex int32     `json:"notification_index"`
	TimeEnd           time.Time `json:"time_end"`
	UssBaseUrl        string    `json:"uss_base_url"`
}

func (q *Queries) SubscriptionUpsert(ctx context.Context, arg SubscriptionUpsertParams) error {
	_, err := q.db.Exec(ctx, subscriptionUpsert,
		arg.SubscriptionID,
		arg.Area,
		arg.Version,
		arg.NotificationIndex,
		arg.TimeEnd,
		arg.UssBaseUrl,
	)
	return err
}

const subscriptionsUTM = `-- name: SubscriptionsUTM :many
SELECT subscription_id, kind, area, version, notification_index, time_end, uss_base_url, renewed_at
FROM dss_subscriptions
WHERE kind = 'utm'
ORDER BY subscription_id
LIMIT $1
`

func (q *Queries) SubscriptionsUTM(ctx context.Context, maxRows int32) ([]DssSubscription, error) {
	rows, err := q.db.Query(ctx, subscriptionsUTM, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DssSubscription
	for rows.Next() {
		var i DssSubscription
		if err := rows.Scan(
			&i.SubscriptionID,
			&i.Kind,
			&i.Area,
			&i.Version,
			&i.NotificationIndex,
			&i.TimeEnd,
			&i.UssBaseUrl,
			&i.RenewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
