// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package relational

import (
	"context"
	"time"
)

const ensureEventsPartition = `-- name: EnsureEventsPartition :one

SELECT events_ensure_partition(now())::text AS partition_name
`

// The audit log. internal/store Audit is the only caller of
// InsertEvent (a test greps for it).
func (q *Queries) EnsureEventsPartition(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, ensureEventsPartition)
	var partition_name string
	err := row.Scan(&partition_name)
	return partition_name, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO events (actor_type, actor_id, purpose, entity_type, entity_id, event_type, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, ts
`

type InsertEventParams struct {
	ActorType  string  `json:"actor_type"`
	ActorID    string  `json:"actor_id"`
	Purpose    *string `json:"purpose"`
	EntityType string  `json:"entity_type"`
	EntityID   *string `json:"entity_id"`
	EventType  string  `json:"event_type"`
	Payload    []byte  `json:"payload"`
}

type InsertEventRow struct {
	ID int64     `json:"id"`
	Ts time.Time `json:"ts"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (InsertEventRow, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ActorType,
		arg.ActorID,
		arg.Purpose,
		arg.EntityType,
		arg.EntityID,
		arg.EventType,
		arg.Payload,
	)
	var i InsertEventRow
	err := row.Scan(&i.ID, &i.Ts)
	return i, err
}

const listEventsByEntity = `-- name: ListEventsByEntity :many
SELECT id, ts, actor_type, actor_id, purpose, entity_type, entity_id, event_type, payload
FROM events
WHERE entity_type = $1 AND entity_id = $2::text
ORDER BY ts, id
`

type ListEventsByEntityParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) ListEventsByEntity(ctx context.Context, arg ListEventsByEntityParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByEntity, arg.EntityType, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Ts,
			&i.ActorType,
			&i.ActorID,
			&i.Purpose,
			&i.EntityType,
			&i.EntityID,
			&i.EventType,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
