// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: flights.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getFlight = `-- name: GetFlight :one
SELECT id, intent_id, authorisation_number, uas_serial, operator_reg, client_id, started_at, ended_at, end_reason, last_state
FROM flights
WHERE id = $1::uuid
`

type GetFlightRow struct {
	ID                  pgtype.UUID `json:"id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	UasSerial           string      `json:"uas_serial"`
	OperatorReg         *string     `json:"operator_reg"`
	ClientID            *string     `json:"client_id"`
	StartedAt           time.Time   `json:"started_at"`
	EndedAt             *time.Time  `json:"ended_at"`
	EndReason           *string     `json:"end_reason"`
	LastState           *string     `json:"last_state"`
}

func (q *Queries) GetFlight(ctx context.Context, id pgtype.UUID) (GetFlightRow, error) {
	row := q.db.QueryRow(ctx, getFlight, id)
	var i GetFlightRow
	err := row.Scan(
		&i.ID,
		&i.IntentID,
		&i.AuthorisationNumber,
		&i.UasSerial,
		&i.OperatorReg,
		&i.ClientID,
		&i.StartedAt,
		&i.EndedAt,
		&i.EndReason,
		&i.LastState,
	)
	return i, err
}

const recordFlightEvent = `-- name: RecordFlightEvent :exec

INSERT INTO flights (id, intent_id, authorisation_number, uas_serial, operator_reg, client_id, started_at, ended_at, end_reason, last_state)
VALUES (
    $1::uuid,
    (SELECT oi.id FROM operational_intents oi WHERE oi.id = $2::uuid),
    $3,
    $4,
    $5,
    (SELECT c.client_id FROM oauth_clients c WHERE c.client_id = $6::text),
    $7,
    CASE WHEN $8::timestamptz IS NULL THEN NULL
         ELSE GREATEST($8::timestamptz, $7::timestamptz) END,
    $9,
    $10
)
ON CONFLICT (id) DO UPDATE
SET ended_at = COALESCE(flights.ended_at, EXCLUDED.ended_at),
    end_reason = COALESCE(flights.end_reason, EXCLUDED.end_reason),
    last_state = CASE WHEN flights.ended_at IS NULL THEN EXCLUDED.last_state ELSE flights.last_state END
`

type RecordFlightEventParams struct {
	ID                  pgtype.UUID `json:"id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	UasSerial           string      `json:"uas_serial"`
	OperatorReg         *string     `json:"operator_reg"`
	ClientID            string      `json:"client_id"`
	StartedAt           time.Time   `json:"started_at"`
	EndedAt             *time.Time  `json:"ended_at"`
	EndReason           *string     `json:"end_reason"`
	LastState           *string     `json:"last_state"`
}

// Flights (internal/flights): the facts telemetry-ingest publishes on
// flight.v1, recorded by api (docs/PLAN.md §3.2). Every event carries the
// whole flight, so any one of them creates the row; a later one never
// reopens an ended flight. A client or an intent this database does not
// hold is recorded as NULL, never refused: the flight happened.
func (q *Queries) RecordFlightEvent(ctx context.Context, arg RecordFlightEventParams) error {
	_, err := q.db.Exec(ctx, recordFlightEvent,
		arg.ID,
		arg.IntentID,
		arg.AuthorisationNumber,
		arg.UasSerial,
		arg.OperatorReg,
		arg.ClientID,
		arg.StartedAt,
		arg.EndedAt,
		arg.EndReason,
		arg.LastState,
	)
	return err
}
