// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intents.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const intentByClientRef = `-- name: IntentByClientRef :one
SELECT id, operator_id, client_id, client_ref, request_hash, request, decision_body, version, local_state,
       exempt_art_1_3, priority, time_start, time_end, filed_at, created_at, volumes_amsl, cell_set,
       update_required
  FROM operational_intents
 WHERE client_id = $1 AND client_ref = $2
`

type IntentByClientRefParams struct {
	ClientID  string  `json:"client_id"`
	ClientRef *string `json:"client_ref"`
}

type IntentByClientRefRow struct {
	ID             pgtype.UUID `json:"id"`
	OperatorID     pgtype.UUID `json:"operator_id"`
	ClientID       string      `json:"client_id"`
	ClientRef      *string     `json:"client_ref"`
	RequestHash    *string     `json:"request_hash"`
	Request        []byte      `json:"request"`
	DecisionBody   []byte      `json:"decision_body"`
	Version        int32       `json:"version"`
	LocalState     string      `json:"local_state"`
	ExemptArt13    bool        `json:"exempt_art_1_3"`
	Priority       int32       `json:"priority"`
	TimeStart      time.Time   `json:"time_start"`
	TimeEnd        time.Time   `json:"time_end"`
	FiledAt        time.Time   `json:"filed_at"`
	CreatedAt      time.Time   `json:"created_at"`
	VolumesAmsl    []byte      `json:"volumes_amsl"`
	CellSet        []string    `json:"cell_set"`
	UpdateRequired []byte      `json:"update_required"`
}

func (q *Queries) IntentByClientRef(ctx context.Context, arg IntentByClientRefParams) (IntentByClientRefRow, error) {
	row := q.db.QueryRow(ctx, intentByClientRef, arg.ClientID, arg.ClientRef)
	var i IntentByClientRefRow
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ClientID,
		&i.ClientRef,
		&i.RequestHash,
		&i.Request,
		&i.DecisionBody,
		&i.Version,
		&i.LocalState,
		&i.ExemptArt13,
		&i.Priority,
		&i.TimeStart,
		&i.TimeEnd,
		&i.FiledAt,
		&i.CreatedAt,
		&i.VolumesAmsl,
		&i.CellSet,
		&i.UpdateRequired,
	)
	return i, err
}

const intentByID = `-- name: IntentByID :one
SELECT id, operator_id, client_id, client_ref, request_hash, request, decision_body, version, local_state,
       exempt_art_1_3, priority, time_start, time_end, filed_at, created_at, volumes_amsl, cell_set,
       update_required
  FROM operational_intents
 WHERE id = $1
`

type IntentByIDRow struct {
	ID             pgtype.UUID `json:"id"`
	OperatorID     pgtype.UUID `json:"operator_id"`
	ClientID       string      `json:"client_id"`
	ClientRef      *string     `json:"client_ref"`
	RequestHash    *string     `json:"request_hash"`
	Request        []byte      `json:"request"`
	DecisionBody   []byte      `json:"decision_body"`
	Version        int32       `json:"version"`
	LocalState     string      `json:"local_state"`
	ExemptArt13    bool        `json:"exempt_art_1_3"`
	Priority       int32       `json:"priority"`
	TimeStart      time.Time   `json:"time_start"`
	TimeEnd        time.Time   `json:"time_end"`
	FiledAt        time.Time   `json:"filed_at"`
	CreatedAt      time.Time   `json:"created_at"`
	VolumesAmsl    []byte      `json:"volumes_amsl"`
	CellSet        []string    `json:"cell_set"`
	UpdateRequired []byte      `json:"update_required"`
}

func (q *Queries) IntentByID(ctx context.Context, id pgtype.UUID) (IntentByIDRow, error) {
	row := q.db.QueryRow(ctx, intentByID, id)
	var i IntentByIDRow
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ClientID,
		&i.ClientRef,
		&i.RequestHash,
		&i.Request,
		&i.DecisionBody,
		&i.Version,
		&i.LocalState,
		&i.ExemptArt13,
		&i.Priority,
		&i.TimeStart,
		&i.TimeEnd,
		&i.FiledAt,
		&i.CreatedAt,
		&i.VolumesAmsl,
		&i.CellSet,
		&i.UpdateRequired,
	)
	return i, err
}

const intentCountOpen = `-- name: IntentCountOpen :one
SELECT count(*)::int AS open
  FROM operational_intents
 WHERE operator_id = $1
   AND local_state IN ('pending_validation', 'pending_dss', 'pending_authority', 'accepted', 'activated', 'nonconforming', 'contingent')
`

func (q *Queries) IntentCountOpen(ctx context.Context, operatorID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, intentCountOpen, operatorID)
	var open int32
	err := row.Scan(&open)
	return open, err
}

const intentDueToEnd = `-- name: IntentDueToEnd :many
SELECT id, operator_id, client_id, client_ref, request_hash, request, decision_body, version, local_state,
       exempt_art_1_3, priority, time_start, time_end, filed_at, created_at, volumes_amsl, cell_set,
       update_required
  FROM operational_intents
 WHERE time_end < $1::timestamptz
   AND local_state IN ('pending_validation', 'pending_dss', 'pending_authority', 'accepted', 'activated', 'nonconforming', 'contingent')
 ORDER BY time_end, id
 LIMIT $2
   FOR UPDATE SKIP LOCKED
`

type IntentDueToEndParams struct {
	NowAt   time.Time `json:"now_at"`
	MaxRows int32     `json:"max_rows"`
}

type IntentDueToEndRow struct {
	ID             pgtype.UUID `json:"id"`
	OperatorID     pgtype.UUID `json:"operator_id"`
	ClientID       string      `json:"client_id"`
	ClientRef      *string     `json:"client_ref"`
	RequestHash    *string     `json:"request_hash"`
	Request        []byte      `json:"request"`
	DecisionBody   []byte      `json:"decision_body"`
	Version        int32       `json:"version"`
	LocalState     string      `json:"local_state"`
	ExemptArt13    bool        `json:"exempt_art_1_3"`
	Priority       int32       `json:"priority"`
	TimeStart      time.Time   `json:"time_start"`
	TimeEnd        time.Time   `json:"time_end"`
	FiledAt        time.Time   `json:"filed_at"`
	CreatedAt      time.Time   `json:"created_at"`
	VolumesAmsl    []byte      `json:"volumes_amsl"`
	CellSet        []string    `json:"cell_set"`
	UpdateRequired []byte      `json:"update_required"`
}

// The open intents whose time_end has passed, oldest first, locked.
func (q *Queries) IntentDueToEnd(ctx context.Context, arg IntentDueToEndParams) ([]IntentDueToEndRow, error) {
	rows, err := q.db.Query(ctx, intentDueToEnd, arg.NowAt, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntentDueToEndRow
	for rows.Next() {
		var i IntentDueToEndRow
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.ClientID,
			&i.ClientRef,
			&i.RequestHash,
			&i.Request,
			&i.DecisionBody,
			&i.Version,
			&i.LocalState,
			&i.ExemptArt13,
			&i.Priority,
			&i.TimeStart,
			&i.TimeEnd,
			&i.FiledAt,
			&i.CreatedAt,
			&i.VolumesAmsl,
			&i.CellSet,
			&i.UpdateRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const intentFlagUpdate = `-- name: IntentFlagUpdate :execrows
UPDATE operational_intents
   SET update_required = $1
 WHERE id = ANY ($2::uuid[])
   AND local_state IN ('accepted', 'activated', 'nonconforming', 'contingent')
`

type IntentFlagUpdateParams struct {
	UpdateRequired []byte        `json:"update_required"`
	Ids            []pgtype.UUID `json:"ids"`
}

// Records that a later intent with precedence overlaps these
// authorisations (Art. 10(10)); WP-12 updates or withdraws them.
func (q *Queries) IntentFlagUpdate(ctx context.Context, arg IntentFlagUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, intentFlagUpdate, arg.UpdateRequired, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const intentForUpdate = `-- name: IntentForUpdate :one
SELECT id, operator_id, client_id, client_ref, request_hash, request, decision_body, version, local_state,
       exempt_art_1_3, priority, time_start, time_end, filed_at, created_at, volumes_amsl, cell_set,
       update_required
  FROM operational_intents
 WHERE id = $1
   FOR UPDATE
`

type IntentForUpdateRow struct {
	ID             pgtype.UUID `json:"id"`
	OperatorID     pgtype.UUID `json:"operator_id"`
	ClientID       string      `json:"client_id"`
	ClientRef      *string     `json:"client_ref"`
	RequestHash    *string     `json:"request_hash"`
	Request        []byte      `json:"request"`
	DecisionBody   []byte      `json:"decision_body"`
	Version        int32       `json:"version"`
	LocalState     string      `json:"local_state"`
	ExemptArt13    bool        `json:"exempt_art_1_3"`
	Priority       int32       `json:"priority"`
	TimeStart      time.Time   `json:"time_start"`
	TimeEnd        time.Time   `json:"time_end"`
	FiledAt        time.Time   `json:"filed_at"`
	CreatedAt      time.Time   `json:"created_at"`
	VolumesAmsl    []byte      `json:"volumes_amsl"`
	CellSet        []string    `json:"cell_set"`
	UpdateRequired []byte      `json:"update_required"`
}

func (q *Queries) IntentForUpdate(ctx context.Context, id pgtype.UUID) (IntentForUpdateRow, error) {
	row := q.db.QueryRow(ctx, intentForUpdate, id)
	var i IntentForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.ClientID,
		&i.ClientRef,
		&i.RequestHash,
		&i.Request,
		&i.DecisionBody,
		&i.Version,
		&i.LocalState,
		&i.ExemptArt13,
		&i.Priority,
		&i.TimeStart,
		&i.TimeEnd,
		&i.FiledAt,
		&i.CreatedAt,
		&i.VolumesAmsl,
		&i.CellSet,
		&i.UpdateRequired,
	)
	return i, err
}

const intentInsert = `-- name: IntentInsert :exec
INSERT INTO operational_intents (
    id, operator_id, client_id, uas_serial, pilot_ref, priority, dss_state, local_state, volumes, volumes_amsl,
    envelope_geom, time_start, time_end, mode, flight_type, category, subcategory, class_label, type_certificate,
    privately_built, mtom_kg, identification_technology, connectivity_methods, endurance_s, loss_of_c2_procedure,
    operator_reg, ua_registration, contingency, emergency_contact_ref, authorisation_ref, client_ref,
    in_uspace_airspace, uspace_airspace_ids, exempt_art_1_3, decision, authorisation_number, deviation_thresholds,
    alternative, conflicts, conditions, cis_version_checked, registry_checked_at, policy_version,
    version, request, request_hash, decision_body, filed_at, cell_set, created_at, updated_at)
VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    ST_GeogFromText($11::text), $12, $13, $14,
    $15, $16, $17, $18,
    $19, $20, $21, $22,
    $23, $24, $25, $26,
    $27, $28, $29, $30,
    $31, $32, $33, $34,
    $35, $36, $37, $38,
    $39, $40, $41, $42,
    $43, $44, $45, $46, $47,
    $48, $49, $50, $50)
`

type IntentInsertParams struct {
	ID                       pgtype.UUID `json:"id"`
	OperatorID               pgtype.UUID `json:"operator_id"`
	ClientID                 string      `json:"client_id"`
	UasSerial                string      `json:"uas_serial"`
	PilotRef                 *string     `json:"pilot_ref"`
	Priority                 int32       `json:"priority"`
	DssState                 *string     `json:"dss_state"`
	LocalState               string      `json:"local_state"`
	Volumes                  []byte      `json:"volumes"`
	VolumesAmsl              []byte      `json:"volumes_amsl"`
	EnvelopeWkt              string      `json:"envelope_wkt"`
	TimeStart                time.Time   `json:"time_start"`
	TimeEnd                  time.Time   `json:"time_end"`
	Mode                     *string     `json:"mode"`
	FlightType               *string     `json:"flight_type"`
	Category                 *string     `json:"category"`
	Subcategory              *string     `json:"subcategory"`
	ClassLabel               *string     `json:"class_label"`
	TypeCertificate          *string     `json:"type_certificate"`
	PrivatelyBuilt           bool        `json:"privately_built"`
	MtomKg                   *float64    `json:"mtom_kg"`
	IdentificationTechnology *string     `json:"identification_technology"`
	ConnectivityMethods      []string    `json:"connectivity_methods"`
	EnduranceS               *int32      `json:"endurance_s"`
	LossOfC2Procedure        *string     `json:"loss_of_c2_procedure"`
	OperatorReg              *string     `json:"operator_reg"`
	UaRegistration           *string     `json:"ua_registration"`
	Contingency              []byte      `json:"contingency"`
	EmergencyContactRef      *string     `json:"emergency_contact_ref"`
	AuthorisationRef         *string     `json:"authorisation_ref"`
	ClientRef                *string     `json:"client_ref"`
	InUspaceAirspace         *bool       `json:"in_uspace_airspace"`
	UspaceAirspaceIds        []string    `json:"uspace_airspace_ids"`
	ExemptArt13              bool        `json:"exempt_art_1_3"`
	Decision                 *string     `json:"decision"`
	AuthorisationNumber      *string     `json:"authorisation_number"`
	DeviationThresholds      []byte      `json:"deviation_thresholds"`
	Alternative              []byte      `json:"alternative"`
	Conflicts                []byte      `json:"conflicts"`
	Conditions               []string    `json:"conditions"`
	CisVersionChecked        *string     `json:"cis_version_checked"`
	RegistryCheckedAt        *time.Time  `json:"registry_checked_at"`
	PolicyVersion            *int64      `json:"policy_version"`
	Version                  int32       `json:"version"`
	Request                  []byte      `json:"request"`
	RequestHash              *string     `json:"request_hash"`
	DecisionBody             []byte      `json:"decision_body"`
	FiledAt                  time.Time   `json:"filed_at"`
	CellSet                  []string    `json:"cell_set"`
	CreatedAt                time.Time   `json:"created_at"`
}

func (q *Queries) IntentInsert(ctx context.Context, arg IntentInsertParams) error {
	_, err := q.db.Exec(ctx, intentInsert,
		arg.ID,
		arg.OperatorID,
		arg.ClientID,
		arg.UasSerial,
		arg.PilotRef,
		arg.Priority,
		arg.DssState,
		arg.LocalState,
		arg.Volumes,
		arg.VolumesAmsl,
		arg.EnvelopeWkt,
		arg.TimeStart,
		arg.TimeEnd,
		arg.Mode,
		arg.FlightType,
		arg.Category,
		arg.Subcategory,
		arg.ClassLabel,
		arg.TypeCertificate,
		arg.PrivatelyBuilt,
		arg.MtomKg,
		arg.IdentificationTechnology,
		arg.ConnectivityMethods,
		arg.EnduranceS,
		arg.LossOfC2Procedure,
		arg.OperatorReg,
		arg.UaRegistration,
		arg.Contingency,
		arg.EmergencyContactRef,
		arg.AuthorisationRef,
		arg.ClientRef,
		arg.InUspaceAirspace,
		arg.UspaceAirspaceIds,
		arg.ExemptArt13,
		arg.Decision,
		arg.AuthorisationNumber,
		arg.DeviationThresholds,
		arg.Alternative,
		arg.Conflicts,
		arg.Conditions,
		arg.CisVersionChecked,
		arg.RegistryCheckedAt,
		arg.PolicyVersion,
		arg.Version,
		arg.Request,
		arg.RequestHash,
		arg.DecisionBody,
		arg.FiledAt,
		arg.CellSet,
		arg.CreatedAt,
	)
	return err
}

const intentList = `-- name: IntentList :many
SELECT id, operator_id, client_id, client_ref, request_hash, request, decision_body, version, local_state,
       exempt_art_1_3, priority, time_start, time_end, filed_at, created_at, volumes_amsl, cell_set,
       update_required
  FROM operational_intents
 WHERE operator_id = $1
   AND ($2::timestamptz IS NULL OR time_end >= $2::timestamptz)
   AND ($3::timestamptz IS NULL OR time_start <= $3::timestamptz)
   AND ($4::text IS NULL OR local_state = $4::text)
 ORDER BY created_at DESC, id
 LIMIT $5
`

type IntentListParams struct {
	OperatorID pgtype.UUID `json:"operator_id"`
	FromAt     *time.Time  `json:"from_at"`
	ToAt       *time.Time  `json:"to_at"`
	State      *string     `json:"state"`
	MaxRows    int32       `json:"max_rows"`
}

type IntentListRow struct {
	ID             pgtype.UUID `json:"id"`
	OperatorID     pgtype.UUID `json:"operator_id"`
	ClientID       string      `json:"client_id"`
	ClientRef      *string     `json:"client_ref"`
	RequestHash    *string     `json:"request_hash"`
	Request        []byte      `json:"request"`
	DecisionBody   []byte      `json:"decision_body"`
	Version        int32       `json:"version"`
	LocalState     string      `json:"local_state"`
	ExemptArt13    bool        `json:"exempt_art_1_3"`
	Priority       int32       `json:"priority"`
	TimeStart      time.Time   `json:"time_start"`
	TimeEnd        time.Time   `json:"time_end"`
	FiledAt        time.Time   `json:"filed_at"`
	CreatedAt      time.Time   `json:"created_at"`
	VolumesAmsl    []byte      `json:"volumes_amsl"`
	CellSet        []string    `json:"cell_set"`
	UpdateRequired []byte      `json:"update_required"`
}

// An operator's intents, newest first; from and to bound the window
// (an intent is listed when its window overlaps them), state filters.
func (q *Queries) IntentList(ctx context.Context, arg IntentListParams) ([]IntentListRow, error) {
	rows, err := q.db.Query(ctx, intentList,
		arg.OperatorID,
		arg.FromAt,
		arg.ToAt,
		arg.State,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntentListRow
	for rows.Next() {
		var i IntentListRow
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.ClientID,
			&i.ClientRef,
			&i.RequestHash,
			&i.Request,
			&i.DecisionBody,
			&i.Version,
			&i.LocalState,
			&i.ExemptArt13,
			&i.Priority,
			&i.TimeStart,
			&i.TimeEnd,
			&i.FiledAt,
			&i.CreatedAt,
			&i.VolumesAmsl,
			&i.CellSet,
			&i.UpdateRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const intentLockedNow = `-- name: IntentLockedNow :one
SELECT clock_timestamp()::timestamptz AS now
`

// The database clock as it reads now, not when the transaction began:
// inside the intents lock it ranks first come, first served (a request
// that began first but locked second is second in line).
func (q *Queries) IntentLockedNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, intentLockedNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const intentNow = `-- name: IntentNow :one

SELECT now()::timestamptz AS now
`

// Operational intents (WP-7, internal/intent/pgstore). Every time a
// decision rests on is the database clock; every list is bounded.
func (q *Queries) IntentNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, intentNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const intentOverlapping = `-- name: IntentOverlapping :many
SELECT id, operator_id, client_id, client_ref, request_hash, request, decision_body, version, local_state,
       exempt_art_1_3, priority, time_start, time_end, filed_at, created_at, volumes_amsl, cell_set,
       update_required
  FROM operational_intents
 WHERE local_state IN ('accepted', 'activated', 'nonconforming', 'contingent')
   AND NOT exempt_art_1_3
   AND time_start <= $1::timestamptz AND time_end >= $2::timestamptz
   AND id <> $3::uuid
   AND ST_DWithin(envelope_geom, ST_GeogFromText($4::text), $5::float8)
 ORDER BY filed_at, id
 LIMIT $6
`

type IntentOverlappingParams struct {
	ToAt        time.Time   `json:"to_at"`
	FromAt      time.Time   `json:"from_at"`
	ExcludeID   pgtype.UUID `json:"exclude_id"`
	EnvelopeWkt string      `json:"envelope_wkt"`
	DistM       float64     `json:"dist_m"`
	MaxRows     int32       `json:"max_rows"`
}

type IntentOverlappingRow struct {
	ID             pgtype.UUID `json:"id"`
	OperatorID     pgtype.UUID `json:"operator_id"`
	ClientID       string      `json:"client_id"`
	ClientRef      *string     `json:"client_ref"`
	RequestHash    *string     `json:"request_hash"`
	Request        []byte      `json:"request"`
	DecisionBody   []byte      `json:"decision_body"`
	Version        int32       `json:"version"`
	LocalState     string      `json:"local_state"`
	ExemptArt13    bool        `json:"exempt_art_1_3"`
	Priority       int32       `json:"priority"`
	TimeStart      time.Time   `json:"time_start"`
	TimeEnd        time.Time   `json:"time_end"`
	FiledAt        time.Time   `json:"filed_at"`
	CreatedAt      time.Time   `json:"created_at"`
	VolumesAmsl    []byte      `json:"volumes_amsl"`
	CellSet        []string    `json:"cell_set"`
	UpdateRequired []byte      `json:"update_required"`
}

// The active, non-exempt intents whose envelope is within dist_m of the
// envelope given (a MULTIPOLYGON in WKT, WGS84) and whose window
// overlaps [from_at, to_at], without exclude_id: a prefilter, the
// judgement is internal/intent/deconflict's.
func (q *Queries) IntentOverlapping(ctx context.Context, arg IntentOverlappingParams) ([]IntentOverlappingRow, error) {
	rows, err := q.db.Query(ctx, intentOverlapping,
		arg.ToAt,
		arg.FromAt,
		arg.ExcludeID,
		arg.EnvelopeWkt,
		arg.DistM,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntentOverlappingRow
	for rows.Next() {
		var i IntentOverlappingRow
		if err := rows.Scan(
			&i.ID,
			&i.OperatorID,
			&i.ClientID,
			&i.ClientRef,
			&i.RequestHash,
			&i.Request,
			&i.DecisionBody,
			&i.Version,
			&i.LocalState,
			&i.ExemptArt13,
			&i.Priority,
			&i.TimeStart,
			&i.TimeEnd,
			&i.FiledAt,
			&i.CreatedAt,
			&i.VolumesAmsl,
			&i.CellSet,
			&i.UpdateRequired,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const intentOwner = `-- name: IntentOwner :one
SELECT c.client_id, c.operator_id, c.status AS client_status, o.status AS operator_status,
       o.authority_registration_number
  FROM oauth_clients c JOIN operator_accounts o ON o.id = c.operator_id
 WHERE c.client_id = $1
`

type IntentOwnerRow struct {
	ClientID                    string      `json:"client_id"`
	OperatorID                  pgtype.UUID `json:"operator_id"`
	ClientStatus                string      `json:"client_status"`
	OperatorStatus              string      `json:"operator_status"`
	AuthorityRegistrationNumber string      `json:"authority_registration_number"`
}

func (q *Queries) IntentOwner(ctx context.Context, clientID string) (IntentOwnerRow, error) {
	row := q.db.QueryRow(ctx, intentOwner, clientID)
	var i IntentOwnerRow
	err := row.Scan(
		&i.ClientID,
		&i.OperatorID,
		&i.ClientStatus,
		&i.OperatorStatus,
		&i.AuthorityRegistrationNumber,
	)
	return i, err
}

const intentPeerOverlapping = `-- name: IntentPeerOverlapping :many
SELECT entity_id, details, fetched_at
  FROM peer_intents
 WHERE fetched_at > $1::timestamptz
   AND (state IS NULL OR state IN ('Accepted', 'Activated', 'Nonconforming', 'Contingent'))
   AND time_start <= $2::timestamptz AND time_end >= $3::timestamptz
 ORDER BY fetched_at, entity_id
 LIMIT $4
`

type IntentPeerOverlappingParams struct {
	Since   time.Time `json:"since"`
	ToAt    time.Time `json:"to_at"`
	FromAt  time.Time `json:"from_at"`
	MaxRows int32     `json:"max_rows"`
}

type IntentPeerOverlappingRow struct {
	EntityID  string    `json:"entity_id"`
	Details   []byte    `json:"details"`
	FetchedAt time.Time `json:"fetched_at"`
}

// The peers' intents fetched after since in a DSS state whose window
// overlaps [from_at, to_at] (a peer marked unavailable keeps its
// intents until time_end, spec 02 F6).
func (q *Queries) IntentPeerOverlapping(ctx context.Context, arg IntentPeerOverlappingParams) ([]IntentPeerOverlappingRow, error) {
	rows, err := q.db.Query(ctx, intentPeerOverlapping,
		arg.Since,
		arg.ToAt,
		arg.FromAt,
		arg.MaxRows,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IntentPeerOverlappingRow
	for rows.Next() {
		var i IntentPeerOverlappingRow
		if err := rows.Scan(&i.EntityID, &i.Details, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const intentSerialBound = `-- name: IntentSerialBound :one
SELECT EXISTS (SELECT 1 FROM client_serial_bindings
                WHERE client_id = $1 AND serial_fold = $2 AND unbound_at IS NULL) AS bound
`

type IntentSerialBoundParams struct {
	ClientID   string `json:"client_id"`
	SerialFold string `json:"serial_fold"`
}

func (q *Queries) IntentSerialBound(ctx context.Context, arg IntentSerialBoundParams) (bool, error) {
	row := q.db.QueryRow(ctx, intentSerialBound, arg.ClientID, arg.SerialFold)
	var bound bool
	err := row.Scan(&bound)
	return bound, err
}

const intentUpdate = `-- name: IntentUpdate :execrows
UPDATE operational_intents SET
    priority = $1, dss_state = $2, local_state = $3,
    volumes = $4, volumes_amsl = $5,
    envelope_geom = ST_GeogFromText($6::text),
    time_start = $7, time_end = $8, in_uspace_airspace = $9,
    uspace_airspace_ids = $10, exempt_art_1_3 = $11,
    decision = $12, authorisation_number = $13,
    deviation_thresholds = $14, conflicts = $15,
    conditions = $16, cis_version_checked = $17,
    registry_checked_at = $18, policy_version = $19,
    version = $20, request = $21, decision_body = $22,
    filed_at = $23, cell_set = $24, updated_at = $25
 WHERE id = $26 AND version = $20 - 1
`

type IntentUpdateParams struct {
	Priority            int32       `json:"priority"`
	DssState            *string     `json:"dss_state"`
	LocalState          string      `json:"local_state"`
	Volumes             []byte      `json:"volumes"`
	VolumesAmsl         []byte      `json:"volumes_amsl"`
	EnvelopeWkt         string      `json:"envelope_wkt"`
	TimeStart           time.Time   `json:"time_start"`
	TimeEnd             time.Time   `json:"time_end"`
	InUspaceAirspace    *bool       `json:"in_uspace_airspace"`
	UspaceAirspaceIds   []string    `json:"uspace_airspace_ids"`
	ExemptArt13         bool        `json:"exempt_art_1_3"`
	Decision            *string     `json:"decision"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	DeviationThresholds []byte      `json:"deviation_thresholds"`
	Conflicts           []byte      `json:"conflicts"`
	Conditions          []string    `json:"conditions"`
	CisVersionChecked   *string     `json:"cis_version_checked"`
	RegistryCheckedAt   *time.Time  `json:"registry_checked_at"`
	PolicyVersion       *int64      `json:"policy_version"`
	Version             int32       `json:"version"`
	Request             []byte      `json:"request"`
	DecisionBody        []byte      `json:"decision_body"`
	FiledAt             time.Time   `json:"filed_at"`
	CellSet             []string    `json:"cell_set"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ID                  pgtype.UUID `json:"id"`
}

// A new version: the state, the decision and, after a modification,
// the volumes and what is derived from them.
func (q *Queries) IntentUpdate(ctx context.Context, arg IntentUpdateParams) (int64, error) {
	result, err := q.db.Exec(ctx, intentUpdate,
		arg.Priority,
		arg.DssState,
		arg.LocalState,
		arg.Volumes,
		arg.VolumesAmsl,
		arg.EnvelopeWkt,
		arg.TimeStart,
		arg.TimeEnd,
		arg.InUspaceAirspace,
		arg.UspaceAirspaceIds,
		arg.ExemptArt13,
		arg.Decision,
		arg.AuthorisationNumber,
		arg.DeviationThresholds,
		arg.Conflicts,
		arg.Conditions,
		arg.CisVersionChecked,
		arg.RegistryCheckedAt,
		arg.PolicyVersion,
		arg.Version,
		arg.Request,
		arg.DecisionBody,
		arg.FiledAt,
		arg.CellSet,
		arg.UpdatedAt,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const intentVersionInsert = `-- name: IntentVersionInsert :exec
INSERT INTO intent_versions (intent_id, version, at, actor, change_reason, snapshot)
VALUES ($1, $2, $3, $4, $5, $6)
`

type IntentVersionInsertParams struct {
	IntentID     pgtype.UUID `json:"intent_id"`
	Version      int32       `json:"version"`
	At           time.Time   `json:"at"`
	Actor        string      `json:"actor"`
	ChangeReason string      `json:"change_reason"`
	Snapshot     []byte      `json:"snapshot"`
}

func (q *Queries) IntentVersionInsert(ctx context.Context, arg IntentVersionInsertParams) error {
	_, err := q.db.Exec(ctx, intentVersionInsert,
		arg.IntentID,
		arg.Version,
		arg.At,
		arg.Actor,
		arg.ChangeReason,
		arg.Snapshot,
	)
	return err
}
