// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: isas.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimOutboxKinds = `-- name: ClaimOutboxKinds :many
UPDATE dss_outbox
SET attempts = attempts + 1,
    next_at = now() + make_interval(secs => $1::double precision)
WHERE id IN (
    SELECT o.id FROM dss_outbox o
    WHERE o.done_at IS NULL AND o.next_at <= now() AND o.kind = ANY ($2::text[])
    ORDER BY o.next_at, o.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, entity_id, entity_version, payload, attempts, next_at, created_at, done_at, last_error
`

type ClaimOutboxKindsParams struct {
	LeaseS float64  `json:"lease_s"`
	Kinds  []string `json:"kinds"`
	N      int32    `json:"n"`
}

// Claims up to n due items of the given kinds, as ClaimOutbox does
// (the ISA worker takes only isa_put and isa_delete).
func (q *Queries) ClaimOutboxKinds(ctx context.Context, arg ClaimOutboxKindsParams) ([]DssOutbox, error) {
	rows, err := q.db.Query(ctx, claimOutboxKinds, arg.LeaseS, arg.Kinds, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DssOutbox
	for rows.Next() {
		var i DssOutbox
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EntityID,
			&i.EntityVersion,
			&i.Payload,
			&i.Attempts,
			&i.NextAt,
			&i.CreatedAt,
			&i.DoneAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dBNow = `-- name: DBNow :one

SELECT now()::timestamptz AS now
`

// F3411 Identification Service Areas (internal/ridsp, brief WP-9): one
// ISA per flight in dss_isas, planned in the transaction that records
// the flight fact, written to the DSS by the ISA worker through the
// dss_outbox items isa_put and isa_delete. Times come from the
// database clock.
func (q *Queries) DBNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, dBNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const getFlightISA = `-- name: GetFlightISA :one
SELECT isa_id, flight_id, kind, version, time_start, time_end, extents, created_at, deleted_at, last_error
FROM dss_isas
WHERE flight_id = $1::uuid
ORDER BY created_at DESC
LIMIT 1
`

type GetFlightISARow struct {
	IsaID     string      `json:"isa_id"`
	FlightID  pgtype.UUID `json:"flight_id"`
	Kind      string      `json:"kind"`
	Version   *string     `json:"version"`
	TimeStart time.Time   `json:"time_start"`
	TimeEnd   time.Time   `json:"time_end"`
	Extents   []byte      `json:"extents"`
	CreatedAt time.Time   `json:"created_at"`
	DeletedAt *time.Time  `json:"deleted_at"`
	LastError *string     `json:"last_error"`
}

func (q *Queries) GetFlightISA(ctx context.Context, flightID pgtype.UUID) (GetFlightISARow, error) {
	row := q.db.QueryRow(ctx, getFlightISA, flightID)
	var i GetFlightISARow
	err := row.Scan(
		&i.IsaID,
		&i.FlightID,
		&i.Kind,
		&i.Version,
		&i.TimeStart,
		&i.TimeEnd,
		&i.Extents,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.LastError,
	)
	return i, err
}

const getISAForWrite = `-- name: GetISAForWrite :one
SELECT i.isa_id, i.flight_id, i.kind, i.version, i.time_start, i.time_end, i.extents, i.deleted_at,
       f.ended_at AS flight_ended_at
FROM dss_isas i
LEFT JOIN flights f ON f.id = i.flight_id
WHERE i.isa_id = $1
`

type GetISAForWriteRow struct {
	IsaID         string      `json:"isa_id"`
	FlightID      pgtype.UUID `json:"flight_id"`
	Kind          string      `json:"kind"`
	Version       *string     `json:"version"`
	TimeStart     time.Time   `json:"time_start"`
	TimeEnd       time.Time   `json:"time_end"`
	Extents       []byte      `json:"extents"`
	DeletedAt     *time.Time  `json:"deleted_at"`
	FlightEndedAt *time.Time  `json:"flight_ended_at"`
}

// An ISA with its flight's end, for the worker.
func (q *Queries) GetISAForWrite(ctx context.Context, isaID string) (GetISAForWriteRow, error) {
	row := q.db.QueryRow(ctx, getISAForWrite, isaID)
	var i GetISAForWriteRow
	err := row.Scan(
		&i.IsaID,
		&i.FlightID,
		&i.Kind,
		&i.Version,
		&i.TimeStart,
		&i.TimeEnd,
		&i.Extents,
		&i.DeletedAt,
		&i.FlightEndedAt,
	)
	return i, err
}

const getIntentExtent = `-- name: GetIntentExtent :one
SELECT volumes, time_start, time_end
FROM operational_intents
WHERE id = $1::uuid
`

type GetIntentExtentRow struct {
	Volumes   []byte    `json:"volumes"`
	TimeStart time.Time `json:"time_start"`
	TimeEnd   time.Time `json:"time_end"`
}

// The volumes and window of the intent a flight flies.
func (q *Queries) GetIntentExtent(ctx context.Context, id pgtype.UUID) (GetIntentExtentRow, error) {
	row := q.db.QueryRow(ctx, getIntentExtent, id)
	var i GetIntentExtentRow
	err := row.Scan(&i.Volumes, &i.TimeStart, &i.TimeEnd)
	return i, err
}

const insertISA = `-- name: InsertISA :execrows
INSERT INTO dss_isas (isa_id, flight_id, kind, time_start, time_end, extents)
VALUES ($1, $2::uuid, $3, $4, $5, $6)
ON CONFLICT (isa_id) DO NOTHING
`

type InsertISAParams struct {
	IsaID     string      `json:"isa_id"`
	FlightID  pgtype.UUID `json:"flight_id"`
	Kind      string      `json:"kind"`
	TimeStart time.Time   `json:"time_start"`
	TimeEnd   time.Time   `json:"time_end"`
	Extents   []byte      `json:"extents"`
}

func (q *Queries) InsertISA(ctx context.Context, arg InsertISAParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertISA,
		arg.IsaID,
		arg.FlightID,
		arg.Kind,
		arg.TimeStart,
		arg.TimeEnd,
		arg.Extents,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const outboxBacklog = `-- name: OutboxBacklog :one
SELECT count(*)::bigint AS pending,
       COALESCE(EXTRACT(EPOCH FROM now() - min(created_at)), 0)::double precision AS oldest_age_s
FROM dss_outbox
WHERE done_at IS NULL AND kind = ANY ($1::text[])
`

type OutboxBacklogRow struct {
	Pending    int64   `json:"pending"`
	OldestAgeS float64 `json:"oldest_age_s"`
}

// The undone items of the given kinds and the age of the oldest.
func (q *Queries) OutboxBacklog(ctx context.Context, kinds []string) (OutboxBacklogRow, error) {
	row := q.db.QueryRow(ctx, outboxBacklog, kinds)
	var i OutboxBacklogRow
	err := row.Scan(&i.Pending, &i.OldestAgeS)
	return i, err
}

const sessionISAsDue = `-- name: SessionISAsDue :many
SELECT i.isa_id, i.flight_id, i.version, i.time_end, i.extents
FROM dss_isas i
JOIN flights f ON f.id = i.flight_id
WHERE i.deleted_at IS NULL AND i.version IS NOT NULL AND f.ended_at IS NULL
  AND i.kind = 'session'
  AND NOT EXISTS (
      SELECT 1 FROM dss_outbox o
      WHERE o.kind = 'isa_put' AND o.entity_id = i.isa_id AND o.done_at IS NULL
  )
  AND i.time_end < now() + make_interval(secs => $1::double precision)
ORDER BY i.time_end
LIMIT $2
`

type SessionISAsDueParams struct {
	BeforeS float64 `json:"before_s"`
	N       int32   `json:"n"`
}

type SessionISAsDueRow struct {
	IsaID    string      `json:"isa_id"`
	FlightID pgtype.UUID `json:"flight_id"`
	Version  *string     `json:"version"`
	TimeEnd  time.Time   `json:"time_end"`
	Extents  []byte      `json:"extents"`
}

// Session ISAs of flights still going on whose time_end is within
// before_s and that no isa_put waits for: due for renewal (one item per
// ISA at a time, so a long DSS outage queues nothing more).
func (q *Queries) SessionISAsDue(ctx context.Context, arg SessionISAsDueParams) ([]SessionISAsDueRow, error) {
	rows, err := q.db.Query(ctx, sessionISAsDue, arg.BeforeS, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionISAsDueRow
	for rows.Next() {
		var i SessionISAsDueRow
		if err := rows.Scan(
			&i.IsaID,
			&i.FlightID,
			&i.Version,
			&i.TimeEnd,
			&i.Extents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFlightISA = `-- name: SetFlightISA :exec
UPDATE flights SET isa_id = $1, isa_version = $2
WHERE id = $3::uuid
`

type SetFlightISAParams struct {
	IsaID      *string     `json:"isa_id"`
	IsaVersion *string     `json:"isa_version"`
	FlightID   pgtype.UUID `json:"flight_id"`
}

func (q *Queries) SetFlightISA(ctx context.Context, arg SetFlightISAParams) error {
	_, err := q.db.Exec(ctx, setFlightISA, arg.IsaID, arg.IsaVersion, arg.FlightID)
	return err
}

const setISADeleted = `-- name: SetISADeleted :exec
UPDATE dss_isas SET deleted_at = now(), last_error = NULL
WHERE isa_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SetISADeleted(ctx context.Context, isaID string) error {
	_, err := q.db.Exec(ctx, setISADeleted, isaID)
	return err
}

const setISAError = `-- name: SetISAError :exec
UPDATE dss_isas SET last_error = $1
WHERE isa_id = $2
`

type SetISAErrorParams struct {
	LastError *string `json:"last_error"`
	IsaID     string  `json:"isa_id"`
}

func (q *Queries) SetISAError(ctx context.Context, arg SetISAErrorParams) error {
	_, err := q.db.Exec(ctx, setISAError, arg.LastError, arg.IsaID)
	return err
}

const setISAKind = `-- name: SetISAKind :exec
UPDATE dss_isas SET kind = $1 WHERE isa_id = $2
`

type SetISAKindParams struct {
	Kind  string `json:"kind"`
	IsaID string `json:"isa_id"`
}

// An ISA planned as a session one becomes its flight's intent ISA.
func (q *Queries) SetISAKind(ctx context.Context, arg SetISAKindParams) error {
	_, err := q.db.Exec(ctx, setISAKind, arg.Kind, arg.IsaID)
	return err
}

const setISAWritten = `-- name: SetISAWritten :exec
UPDATE dss_isas
SET version = $1, time_start = $2, time_end = $3,
    extents = $4, last_error = NULL
WHERE isa_id = $5
`

type SetISAWrittenParams struct {
	Version   *string   `json:"version"`
	TimeStart time.Time `json:"time_start"`
	TimeEnd   time.Time `json:"time_end"`
	Extents   []byte    `json:"extents"`
	IsaID     string    `json:"isa_id"`
}

func (q *Queries) SetISAWritten(ctx context.Context, arg SetISAWrittenParams) error {
	_, err := q.db.Exec(ctx, setISAWritten,
		arg.Version,
		arg.TimeStart,
		arg.TimeEnd,
		arg.Extents,
		arg.IsaID,
	)
	return err
}
