// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locks.sql

package relational

import (
	"context"
)

const advisoryXactLock = `-- name: AdvisoryXactLock :exec

SELECT pg_advisory_xact_lock($1::bigint)
`

// Transaction-scoped advisory locks (internal/store lock keys). Released
// at commit or rollback.
func (q *Queries) AdvisoryXactLock(ctx context.Context, key int64) error {
	_, err := q.db.Exec(ctx, advisoryXactLock, key)
	return err
}
