// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package relational

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Alert struct {
	ID                  pgtype.UUID `json:"id"`
	Kind                string      `json:"kind"`
	FlightID            pgtype.UUID `json:"flight_id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	PeerRef             *string     `json:"peer_ref"`
	Severity            string      `json:"severity"`
	State               string      `json:"state"`
	RaisedAt            time.Time   `json:"raised_at"`
	UpdatedAt           time.Time   `json:"updated_at"`
	ClearedAt           *time.Time  `json:"cleared_at"`
	ClearReason         *string     `json:"clear_reason"`
	Detail              []byte      `json:"detail"`
	CapturedAt          *time.Time  `json:"captured_at"`
	PolicyVersion       int64       `json:"policy_version"`
	AckedAt             *time.Time  `json:"acked_at"`
	AckedBy             *string     `json:"acked_by"`
	EscalatedAt         *time.Time  `json:"escalated_at"`
	Delivery            []byte      `json:"delivery"`
	Cell5               *string     `json:"cell5"`
	RecordedAt          time.Time   `json:"recorded_at"`
}

type CisDataset struct {
	Dataset     string    `json:"dataset"`
	Version     int64     `json:"version"`
	Etag        *string   `json:"etag"`
	FetchedAt   time.Time `json:"fetched_at"`
	Metadata    []byte    `json:"metadata"`
	SignatureOk bool      `json:"signature_ok"`
}

type CisFeature struct {
	Dataset   string `json:"dataset"`
	Version   int64  `json:"version"`
	FeatureID string `json:"feature_id"`
	// ED-318 feature verbatim
	Feature        []byte      `json:"feature"`
	Geom           interface{} `json:"geom"`
	LowerM         *float64    `json:"lower_m"`
	LowerRef       *string     `json:"lower_ref"`
	UpperM         *float64    `json:"upper_m"`
	UpperRef       *string     `json:"upper_ref"`
	ApplicableFrom *time.Time  `json:"applicable_from"`
	ApplicableTo   *time.Time  `json:"applicable_to"`
	ZoneType       *string     `json:"zone_type"`
}

type CisNotification struct {
	ID           int64      `json:"id"`
	ReceivedAt   time.Time  `json:"received_at"`
	Dataset      string     `json:"dataset"`
	Version      *int64     `json:"version"`
	FeatureIds   []string   `json:"feature_ids"`
	Reason       *string    `json:"reason"`
	JwsOk        bool       `json:"jws_ok"`
	PulledAt     *time.Time `json:"pulled_at"`
	Issuer       *string    `json:"issuer"`
	Jti          *string    `json:"jti"`
	Subscription *string    `json:"subscription"`
	MsgID        *string    `json:"msg_id"`
}

type CisNotificationJti struct {
	Issuer     string    `json:"issuer"`
	Jti        string    `json:"jti"`
	ReceivedAt time.Time `json:"received_at"`
	ExpiresAt  time.Time `json:"expires_at"`
}

type ClientSerialBinding struct {
	ID         int64      `json:"id"`
	ClientID   string     `json:"client_id"`
	Serial     string     `json:"serial"`
	SerialFold string     `json:"serial_fold"`
	BoundAt    time.Time  `json:"bound_at"`
	UnboundAt  *time.Time `json:"unbound_at"`
}

type ConformanceState struct {
	ID               int64       `json:"id"`
	FlightID         pgtype.UUID `json:"flight_id"`
	At               time.Time   `json:"at"`
	State            string      `json:"state"`
	Reason           *string     `json:"reason"`
	DistanceOutsideM *float64    `json:"distance_outside_m"`
	HeightOverM      *float64    `json:"height_over_m"`
	TimeOutsideS     *float64    `json:"time_outside_s"`
	PolicyVersion    int64       `json:"policy_version"`
	PeerNotifiedAt   *time.Time  `json:"peer_notified_at"`
	AtsNotifiedAt    *time.Time  `json:"ats_notified_at"`
	AtsAckRef        *string     `json:"ats_ack_ref"`
	NearbyNotified   []byte      `json:"nearby_notified"`
}

type Constraint struct {
	EntityID         string     `json:"entity_id"`
	Manager          string     `json:"manager"`
	Ovn              *string    `json:"ovn"`
	Version          *int64     `json:"version"`
	TimeStart        *time.Time `json:"time_start"`
	TimeEnd          *time.Time `json:"time_end"`
	Details          []byte     `json:"details"`
	CisRestrictionID *string    `json:"cis_restriction_id"`
	FetchedAt        time.Time  `json:"fetched_at"`
}

type DssIsa struct {
	IsaID     string      `json:"isa_id"`
	FlightID  pgtype.UUID `json:"flight_id"`
	Version   *string     `json:"version"`
	TimeStart time.Time   `json:"time_start"`
	TimeEnd   time.Time   `json:"time_end"`
	Extents   []byte      `json:"extents"`
	CreatedAt time.Time   `json:"created_at"`
	DeletedAt *time.Time  `json:"deleted_at"`
	LastError *string     `json:"last_error"`
	Kind      string      `json:"kind"`
	Refusals  int32       `json:"refusals"`
	RefusedAt *time.Time  `json:"refused_at"`
}

type DssOutbox struct {
	ID            int64      `json:"id"`
	Kind          string     `json:"kind"`
	EntityID      string     `json:"entity_id"`
	EntityVersion int64      `json:"entity_version"`
	Payload       []byte     `json:"payload"`
	Attempts      int32      `json:"attempts"`
	NextAt        time.Time  `json:"next_at"`
	CreatedAt     time.Time  `json:"created_at"`
	DoneAt        *time.Time `json:"done_at"`
	LastError     *string    `json:"last_error"`
}

type DssState struct {
	Singleton           bool       `json:"singleton"`
	UssAvailability     *string    `json:"uss_availability"`
	SetBy               *string    `json:"set_by"`
	SetAt               *time.Time `json:"set_at"`
	DssReachableSince   *time.Time `json:"dss_reachable_since"`
	DssUnreachableSince *time.Time `json:"dss_unreachable_since"`
}

type DssSubscription struct {
	SubscriptionID    string     `json:"subscription_id"`
	Kind              string     `json:"kind"`
	Area              []byte     `json:"area"`
	Version           *string    `json:"version"`
	NotificationIndex int32      `json:"notification_index"`
	TimeEnd           time.Time  `json:"time_end"`
	UssBaseUrl        string     `json:"uss_base_url"`
	RenewedAt         *time.Time `json:"renewed_at"`
}

type Event struct {
	ID         int64     `json:"id"`
	Ts         time.Time `json:"ts"`
	ActorType  string    `json:"actor_type"`
	ActorID    string    `json:"actor_id"`
	Purpose    *string   `json:"purpose"`
	EntityType string    `json:"entity_type"`
	EntityID   *string   `json:"entity_id"`
	EventType  string    `json:"event_type"`
	Payload    []byte    `json:"payload"`
}

type Flight struct {
	ID                  pgtype.UUID `json:"id"`
	IntentID            pgtype.UUID `json:"intent_id"`
	AuthorisationNumber *string     `json:"authorisation_number"`
	UasSerial           string      `json:"uas_serial"`
	OperatorReg         *string     `json:"operator_reg"`
	ClientID            *string     `json:"client_id"`
	StartedAt           time.Time   `json:"started_at"`
	EndedAt             *time.Time  `json:"ended_at"`
	EndReason           *string     `json:"end_reason"`
	RidFlightID         *string     `json:"rid_flight_id"`
	IsaID               *string     `json:"isa_id"`
	IsaVersion          *string     `json:"isa_version"`
	Emergency           bool        `json:"emergency"`
	LastState           *string     `json:"last_state"`
}

type IntentVersion struct {
	IntentID     pgtype.UUID `json:"intent_id"`
	Version      int32       `json:"version"`
	At           time.Time   `json:"at"`
	Actor        string      `json:"actor"`
	ChangeReason string      `json:"change_reason"`
	Snapshot     []byte      `json:"snapshot"`
}

type LoginLockout struct {
	Realm       string     `json:"realm"`
	Username    string     `json:"username"`
	Failures    int32      `json:"failures"`
	LockedUntil *time.Time `json:"locked_until"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type OauthClient struct {
	ClientID           string      `json:"client_id"`
	OperatorID         pgtype.UUID `json:"operator_id"`
	SecretHash         string      `json:"secret_hash"`
	Scopes             []string    `json:"scopes"`
	Status             string      `json:"status"`
	CreatedAt          time.Time   `json:"created_at"`
	RotatedAt          *time.Time  `json:"rotated_at"`
	PreviousSecretHash *string     `json:"previous_secret_hash"`
	PreviousValidUntil *time.Time  `json:"previous_valid_until"`
}

type OccurrenceReport struct {
	ID            pgtype.UUID `json:"id"`
	ReportRef     string      `json:"report_ref"`
	Kind          string      `json:"kind"`
	OccurredAt    *time.Time  `json:"occurred_at"`
	BecameAwareAt time.Time   `json:"became_aware_at"`
	DeadlineAt    time.Time   `json:"deadline_at"`
	Payload       []byte      `json:"payload"`
	SubmittedAt   *time.Time  `json:"submitted_at"`
	AuthorityRef  *string     `json:"authority_ref"`
	Attempts      int32       `json:"attempts"`
	LastError     *string     `json:"last_error"`
}

type OperatingStatusNotice struct {
	ID           pgtype.UUID `json:"id"`
	Kind         string      `json:"kind"`
	At           time.Time   `json:"at"`
	SubmittedAt  *time.Time  `json:"submitted_at"`
	AuthorityRef *string     `json:"authority_ref"`
}

type OperationalIntent struct {
	ID         pgtype.UUID `json:"id"`
	OperatorID pgtype.UUID `json:"operator_id"`
	ClientID   string      `json:"client_id"`
	UasSerial  string      `json:"uas_serial"`
	PilotRef   *string     `json:"pilot_ref"`
	Priority   int32       `json:"priority"`
	DssState   *string     `json:"dss_state"`
	LocalState string      `json:"local_state"`
	// F3548 Volume4D[] verbatim (W84 altitudes as given)
	Volumes           []byte `json:"volumes"`
	OffNominalVolumes []byte `json:"off_nominal_volumes"`
	// per volume lower_amsl_m, upper_amsl_m, undulation_m, derived from volumes
	VolumesAmsl              []byte      `json:"volumes_amsl"`
	EnvelopeGeom             interface{} `json:"envelope_geom"`
	TimeStart                time.Time   `json:"time_start"`
	TimeEnd                  time.Time   `json:"time_end"`
	Mode                     *string     `json:"mode"`
	FlightType               *string     `json:"flight_type"`
	Category                 *string     `json:"category"`
	ClassLabel               *string     `json:"class_label"`
	TypeCertificate          *string     `json:"type_certificate"`
	IdentificationTechnology *string     `json:"identification_technology"`
	ConnectivityMethods      []string    `json:"connectivity_methods"`
	EnduranceS               *int32      `json:"endurance_s"`
	LossOfC2Procedure        *string     `json:"loss_of_c2_procedure"`
	OperatorReg              *string     `json:"operator_reg"`
	UaRegistration           *string     `json:"ua_registration"`
	Contingency              []byte      `json:"contingency"`
	EmergencyContactRef      *string     `json:"emergency_contact_ref"`
	AuthorisationRef         *string     `json:"authorisation_ref"`
	ClientRef                *string     `json:"client_ref"`
	InUspaceAirspace         *bool       `json:"in_uspace_airspace"`
	UspaceAirspaceIds        []string    `json:"uspace_airspace_ids"`
	ExemptArt13              bool        `json:"exempt_art_1_3"`
	DssOvn                   *string     `json:"dss_ovn"`
	DssVersion               *int64      `json:"dss_version"`
	Decision                 *string     `json:"decision"`
	AuthorisationNumber      *string     `json:"authorisation_number"`
	// {h_m, v_m, t_s}
	DeviationThresholds []byte     `json:"deviation_thresholds"`
	Alternative         []byte     `json:"alternative"`
	Conflicts           []byte     `json:"conflicts"`
	Conditions          []string   `json:"conditions"`
	CisVersionChecked   *string    `json:"cis_version_checked"`
	RegistryCheckedAt   *time.Time `json:"registry_checked_at"`
	WeatherCheckedRef   *string    `json:"weather_checked_ref"`
	PolicyVersion       *int64     `json:"policy_version"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	Version             int32      `json:"version"`
	Request             []byte     `json:"request"`
	RequestHash         *string    `json:"request_hash"`
	DecisionBody        []byte     `json:"decision_body"`
	FiledAt             time.Time  `json:"filed_at"`
	CellSet             []string   `json:"cell_set"`
	Subcategory         *string    `json:"subcategory"`
	PrivatelyBuilt      bool       `json:"privately_built"`
	MtomKg              *float64   `json:"mtom_kg"`
	UpdateRequired      []byte     `json:"update_required"`
	ProjectedVersion    int32      `json:"projected_version"`
}

type OperatorAccount struct {
	ID                          pgtype.UUID `json:"id"`
	AuthorityRegistrationNumber string      `json:"authority_registration_number"`
	DisplayName                 string      `json:"display_name"`
	ContactEmail                string      `json:"contact_email"`
	Status                      string      `json:"status"`
	ValidatedAt                 *time.Time  `json:"validated_at"`
	ValidationStatus            *string     `json:"validation_status"`
	CreatedAt                   time.Time   `json:"created_at"`
}

type PeerIntent struct {
	EntityID        string     `json:"entity_id"`
	Manager         string     `json:"manager"`
	UssBaseUrl      string     `json:"uss_base_url"`
	State           *string    `json:"state"`
	Ovn             *string    `json:"ovn"`
	Version         *int64     `json:"version"`
	TimeStart       *time.Time `json:"time_start"`
	TimeEnd         *time.Time `json:"time_end"`
	Details         []byte     `json:"details"`
	FetchedAt       time.Time  `json:"fetched_at"`
	PeerUnavailable bool       `json:"peer_unavailable"`
}

type Policy struct {
	Version   int64     `json:"version"`
	CreatedAt time.Time `json:"created_at"`
	Actor     string    `json:"actor"`
	Reason    string    `json:"reason"`
	Values    []byte    `json:"values"`
}

type PortalUser struct {
	ID           pgtype.UUID `json:"id"`
	OperatorID   pgtype.UUID `json:"operator_id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
}

type RecordBundle struct {
	Date        pgtype.Date `json:"date"`
	BuiltAt     time.Time   `json:"built_at"`
	ContentHash string      `json:"content_hash"`
	StorageRef  string      `json:"storage_ref"`
	Flights     int32       `json:"flights"`
}

type RegistryFeed struct {
	ID       bool      `json:"id"`
	Since    int64     `json:"since"`
	Etag     *string   `json:"etag"`
	PolledAt time.Time `json:"polled_at"`
}

type RegistryInvalidation struct {
	EntityType string    `json:"entity_type"`
	KeyFold    string    `json:"key_fold"`
	Seq        int64     `json:"seq"`
	At         time.Time `json:"at"`
}

type RegistryValidity struct {
	EntityType string `json:"entity_type"`
	Key        string `json:"key"`
	Status     string `json:"status"`
	// the registration's end of validity as F8 answers it; null where F8 gives none
	ValidUntil   *time.Time `json:"valid_until"`
	ClassLabel   *string    `json:"class_label"`
	MtomBand     *string    `json:"mtom_band"`
	Competencies []byte     `json:"competencies"`
	FetchedAt    time.Time  `json:"fetched_at"`
	Negative     bool       `json:"negative"`
	KeyFold      string     `json:"key_fold"`
}

type Session struct {
	Jti          string      `json:"jti"`
	Realm        string      `json:"realm"`
	AccountID    pgtype.UUID `json:"account_id"`
	Roles        []string    `json:"roles"`
	IssuedAt     time.Time   `json:"issued_at"`
	ExpiresAt    time.Time   `json:"expires_at"`
	LastSeenAt   time.Time   `json:"last_seen_at"`
	RevokedAt    *time.Time  `json:"revoked_at"`
	RevokeReason *string     `json:"revoke_reason"`
	RemoteIp     string      `json:"remote_ip"`
}

type SourceControl struct {
	ID         int64     `json:"id"`
	SourceType string    `json:"source_type"`
	InstanceID *string   `json:"instance_id"`
	Enabled    bool      `json:"enabled"`
	Reason     string    `json:"reason"`
	Actor      string    `json:"actor"`
	ChangedAt  time.Time `json:"changed_at"`
	Version    int64     `json:"version"`
	Epoch      string    `json:"epoch"`
}

type SourceControlEpoch struct {
	Singleton bool      `json:"singleton"`
	Epoch     string    `json:"epoch"`
	CreatedAt time.Time `json:"created_at"`
}

type StaffAccount struct {
	ID           pgtype.UUID `json:"id"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	Role         string      `json:"role"`
	MfaSecretRef *string     `json:"mfa_secret_ref"`
	Status       string      `json:"status"`
	CreatedAt    time.Time   `json:"created_at"`
	MfaLastStep  int64       `json:"mfa_last_step"`
}

type WeatherProduct struct {
	ID         pgtype.UUID `json:"id"`
	Area       interface{} `json:"area"`
	ObservedAt *time.Time  `json:"observed_at"`
	ValidFrom  time.Time   `json:"valid_from"`
	ValidTo    time.Time   `json:"valid_to"`
	Source     string      `json:"source"`
	Product    []byte      `json:"product"`
	FetchedAt  time.Time   `json:"fetched_at"`
}
