// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package relational

import (
	"context"
)

const claimOutbox = `-- name: ClaimOutbox :many
UPDATE dss_outbox
SET attempts = attempts + 1,
    next_at = now() + make_interval(secs => $1::double precision)
WHERE id IN (
    SELECT o.id FROM dss_outbox o
    WHERE o.done_at IS NULL AND o.next_at <= now()
    ORDER BY o.next_at, o.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, entity_id, entity_version, payload, attempts, next_at, created_at, done_at, last_error
`

type ClaimOutboxParams struct {
	LeaseS float64 `json:"lease_s"`
	N      int32   `json:"n"`
}

// Claims up to n due items: each is leased until now + lease_s, so a
// worker that dies leaves it to be claimed again after the lease.
func (q *Queries) ClaimOutbox(ctx context.Context, arg ClaimOutboxParams) ([]DssOutbox, error) {
	rows, err := q.db.Query(ctx, claimOutbox, arg.LeaseS, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DssOutbox
	for rows.Next() {
		var i DssOutbox
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.EntityID,
			&i.EntityVersion,
			&i.Payload,
			&i.Attempts,
			&i.NextAt,
			&i.CreatedAt,
			&i.DoneAt,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const enqueueOutbox = `-- name: EnqueueOutbox :one

INSERT INTO dss_outbox (kind, entity_id, entity_version, payload, next_at)
VALUES ($1, $2, $3, $4,
        now() + make_interval(secs => $5::double precision))
ON CONFLICT (kind, entity_id, entity_version) DO NOTHING
RETURNING id
`

type EnqueueOutboxParams struct {
	Kind          string  `json:"kind"`
	EntityID      string  `json:"entity_id"`
	EntityVersion int64   `json:"entity_version"`
	Payload       []byte  `json:"payload"`
	HoldS         float64 `json:"hold_s"`
}

// The DSS outbox (internal/store Outbox). Idempotent by (kind,
// entity_id, entity_version): a second Enqueue of the same change
// returns no row. An item is due hold_s after it is queued (0: at
// once); until then no worker's Claim takes it.
func (q *Queries) EnqueueOutbox(ctx context.Context, arg EnqueueOutboxParams) (int64, error) {
	row := q.db.QueryRow(ctx, enqueueOutbox,
		arg.Kind,
		arg.EntityID,
		arg.EntityVersion,
		arg.Payload,
		arg.HoldS,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getOutboxItem = `-- name: GetOutboxItem :one
SELECT id, kind, entity_id, entity_version, payload, attempts, next_at, created_at, done_at, last_error
FROM dss_outbox WHERE id = $1
`

func (q *Queries) GetOutboxItem(ctx context.Context, id int64) (DssOutbox, error) {
	row := q.db.QueryRow(ctx, getOutboxItem, id)
	var i DssOutbox
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.EntityID,
		&i.EntityVersion,
		&i.Payload,
		&i.Attempts,
		&i.NextAt,
		&i.CreatedAt,
		&i.DoneAt,
		&i.LastError,
	)
	return i, err
}

const markOutboxDone = `-- name: MarkOutboxDone :execrows
UPDATE dss_outbox SET done_at = now(), last_error = NULL
WHERE id = $1 AND done_at IS NULL
`

func (q *Queries) MarkOutboxDone(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxDone, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markOutboxFailed = `-- name: MarkOutboxFailed :execrows
UPDATE dss_outbox
SET next_at = now() + make_interval(secs => $1::double precision),
    last_error = $2
WHERE id = $3 AND done_at IS NULL
`

type MarkOutboxFailedParams struct {
	BackoffS  float64 `json:"backoff_s"`
	LastError *string `json:"last_error"`
	ID        int64   `json:"id"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markOutboxFailed, arg.BackoffS, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
