// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policy.sql

package relational

import (
	"context"
)

const insertPolicy = `-- name: InsertPolicy :one
INSERT INTO policy (version, actor, reason, "values")
VALUES ($1, $2, $3, $4)
RETURNING version, created_at, actor, reason, "values"
`

type InsertPolicyParams struct {
	Version      int64  `json:"version"`
	Actor        string `json:"actor"`
	Reason       string `json:"reason"`
	PolicyValues []byte `json:"policy_values"`
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, insertPolicy,
		arg.Version,
		arg.Actor,
		arg.Reason,
		arg.PolicyValues,
	)
	var i Policy
	err := row.Scan(
		&i.Version,
		&i.CreatedAt,
		&i.Actor,
		&i.Reason,
		&i.Values,
	)
	return i, err
}

const newestPolicy = `-- name: NewestPolicy :one
SELECT version, created_at, actor, reason, "values"
FROM policy ORDER BY version DESC LIMIT 1
`

func (q *Queries) NewestPolicy(ctx context.Context) (Policy, error) {
	row := q.db.QueryRow(ctx, newestPolicy)
	var i Policy
	err := row.Scan(
		&i.Version,
		&i.CreatedAt,
		&i.Actor,
		&i.Reason,
		&i.Values,
	)
	return i, err
}

const nextPolicyVersion = `-- name: NextPolicyVersion :one

SELECT nextval('policy_version_seq')::bigint AS version
`

// The versioned policy row (internal/policy through internal/store).
func (q *Queries) NextPolicyVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextPolicyVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}
