// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package relational

import (
	"context"
	"time"
)

const deleteRegistryValidityByFold = `-- name: DeleteRegistryValidityByFold :many
DELETE FROM registry_validity
 WHERE entity_type = $1 AND key_fold = $2
RETURNING entity_type, key
`

type DeleteRegistryValidityByFoldParams struct {
	EntityType string `json:"entity_type"`
	KeyFold    string `json:"key_fold"`
}

type DeleteRegistryValidityByFoldRow struct {
	EntityType string `json:"entity_type"`
	Key        string `json:"key"`
}

// Invalidates every cached answer under a fold key and names them.
func (q *Queries) DeleteRegistryValidityByFold(ctx context.Context, arg DeleteRegistryValidityByFoldParams) ([]DeleteRegistryValidityByFoldRow, error) {
	rows, err := q.db.Query(ctx, deleteRegistryValidityByFold, arg.EntityType, arg.KeyFold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeleteRegistryValidityByFoldRow
	for rows.Next() {
		var i DeleteRegistryValidityByFoldRow
		if err := rows.Scan(&i.EntityType, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneRegistryInvalidations = `-- name: PruneRegistryInvalidations :execrows
DELETE FROM registry_invalidations WHERE at < now() - make_interval(secs => $1::float8)
`

// Forgets invalidations older than keep_s seconds: no fetch is in
// flight that long (the F8 deadline is seconds).
func (q *Queries) PruneRegistryInvalidations(ctx context.Context, keepS float64) (int64, error) {
	result, err := q.db.Exec(ctx, pruneRegistryInvalidations, keepS)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordRegistryInvalidation = `-- name: RecordRegistryInvalidation :exec
INSERT INTO registry_invalidations (entity_type, key_fold, seq, at)
VALUES ($1, $2, $3, now())
ON CONFLICT (entity_type, key_fold) DO UPDATE
   SET seq = GREATEST(registry_invalidations.seq, EXCLUDED.seq), at = now()
`

type RecordRegistryInvalidationParams struct {
	EntityType string `json:"entity_type"`
	KeyFold    string `json:"key_fold"`
	Seq        int64  `json:"seq"`
}

func (q *Queries) RecordRegistryInvalidation(ctx context.Context, arg RecordRegistryInvalidationParams) error {
	_, err := q.db.Exec(ctx, recordRegistryInvalidation, arg.EntityType, arg.KeyFold, arg.Seq)
	return err
}

const registryFeedCursor = `-- name: RegistryFeedCursor :one
SELECT since, etag, polled_at, extract(epoch FROM now() - polled_at)::float8 AS age_s
  FROM registry_feed
 WHERE id
`

type RegistryFeedCursorRow struct {
	Since    int64     `json:"since"`
	Etag     *string   `json:"etag"`
	PolledAt time.Time `json:"polled_at"`
	AgeS     float64   `json:"age_s"`
}

// The feed's cursor, the ETag of its page and the age of its last
// answer.
func (q *Queries) RegistryFeedCursor(ctx context.Context) (RegistryFeedCursorRow, error) {
	row := q.db.QueryRow(ctx, registryFeedCursor)
	var i RegistryFeedCursorRow
	err := row.Scan(
		&i.Since,
		&i.Etag,
		&i.PolledAt,
		&i.AgeS,
	)
	return i, err
}

const registryValidityAll = `-- name: RegistryValidityAll :many
SELECT entity_type, key, key_fold, status, valid_until, class_label, mtom_band,
       competencies, fetched_at, negative,
       extract(epoch FROM now() - fetched_at)::float8 AS age_s
  FROM registry_validity
 ORDER BY fetched_at DESC
 LIMIT $1
`

type RegistryValidityAllRow struct {
	EntityType   string     `json:"entity_type"`
	Key          string     `json:"key"`
	KeyFold      string     `json:"key_fold"`
	Status       string     `json:"status"`
	ValidUntil   *time.Time `json:"valid_until"`
	ClassLabel   *string    `json:"class_label"`
	MtomBand     *string    `json:"mtom_band"`
	Competencies []byte     `json:"competencies"`
	FetchedAt    time.Time  `json:"fetched_at"`
	Negative     bool       `json:"negative"`
	AgeS         float64    `json:"age_s"`
}

// Every cached answer, newest first, at most max_rows (the api's
// table-backed identification lookup).
func (q *Queries) RegistryValidityAll(ctx context.Context, maxRows int32) ([]RegistryValidityAllRow, error) {
	rows, err := q.db.Query(ctx, registryValidityAll, maxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryValidityAllRow
	for rows.Next() {
		var i RegistryValidityAllRow
		if err := rows.Scan(
			&i.EntityType,
			&i.Key,
			&i.KeyFold,
			&i.Status,
			&i.ValidUntil,
			&i.ClassLabel,
			&i.MtomBand,
			&i.Competencies,
			&i.FetchedAt,
			&i.Negative,
			&i.AgeS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registryValidityByKeys = `-- name: RegistryValidityByKeys :many

SELECT v.entity_type, v.key, v.key_fold, v.status, v.valid_until, v.class_label, v.mtom_band,
       v.competencies, v.fetched_at, v.negative,
       extract(epoch FROM now() - v.fetched_at)::float8 AS age_s
  FROM registry_validity v
  JOIN (SELECT unnest($1::text[]) AS entity_type,
               unnest($2::text[]) AS key) AS k
    ON v.entity_type = k.entity_type AND v.key = k.key
`

type RegistryValidityByKeysParams struct {
	EntityTypes []string `json:"entity_types"`
	Keys        []string `json:"keys"`
}

type RegistryValidityByKeysRow struct {
	EntityType   string     `json:"entity_type"`
	Key          string     `json:"key"`
	KeyFold      string     `json:"key_fold"`
	Status       string     `json:"status"`
	ValidUntil   *time.Time `json:"valid_until"`
	ClassLabel   *string    `json:"class_label"`
	MtomBand     *string    `json:"mtom_band"`
	Competencies []byte     `json:"competencies"`
	FetchedAt    time.Time  `json:"fetched_at"`
	Negative     bool       `json:"negative"`
	AgeS         float64    `json:"age_s"`
}

// The registry validity cache of WP-5 (internal/registry): the F8
// answers by key, the change feed's cursor and the invalidations it
// applied. Every age and every timestamp is the database clock.
// The cached answers for the (entity_type, key) pairs, with their age.
func (q *Queries) RegistryValidityByKeys(ctx context.Context, arg RegistryValidityByKeysParams) ([]RegistryValidityByKeysRow, error) {
	rows, err := q.db.Query(ctx, registryValidityByKeys, arg.EntityTypes, arg.Keys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RegistryValidityByKeysRow
	for rows.Next() {
		var i RegistryValidityByKeysRow
		if err := rows.Scan(
			&i.EntityType,
			&i.Key,
			&i.KeyFold,
			&i.Status,
			&i.ValidUntil,
			&i.ClassLabel,
			&i.MtomBand,
			&i.Competencies,
			&i.FetchedAt,
			&i.Negative,
			&i.AgeS,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRegistryFeedCursor = `-- name: SetRegistryFeedCursor :exec
INSERT INTO registry_feed (id, since, etag, polled_at)
VALUES (true, $1, $2, now())
ON CONFLICT (id) DO UPDATE
   SET since = GREATEST(registry_feed.since, EXCLUDED.since), etag = EXCLUDED.etag, polled_at = now()
`

type SetRegistryFeedCursorParams struct {
	Since int64   `json:"since"`
	Etag  *string `json:"etag"`
}

// Moves the cursor (never backwards) and records the answer's time.
func (q *Queries) SetRegistryFeedCursor(ctx context.Context, arg SetRegistryFeedCursorParams) error {
	_, err := q.db.Exec(ctx, setRegistryFeedCursor, arg.Since, arg.Etag)
	return err
}

const upsertRegistryValidity = `-- name: UpsertRegistryValidity :one
INSERT INTO registry_validity (entity_type, key, key_fold, status, valid_until, class_label, mtom_band,
                               competencies, fetched_at, negative)
SELECT $1::text, $2::text, $3::text, $4::text,
       $5::timestamptz, $6::text, $7::text,
       $8::jsonb, now(), $9::boolean
 WHERE NOT EXISTS (
       SELECT 1 FROM registry_invalidations i
        WHERE i.entity_type = $1::text AND i.key_fold = $3::text
          AND i.seq > $10::bigint)
ON CONFLICT (entity_type, key) DO UPDATE
   SET key_fold = EXCLUDED.key_fold, status = EXCLUDED.status, valid_until = EXCLUDED.valid_until,
       class_label = EXCLUDED.class_label, mtom_band = EXCLUDED.mtom_band,
       competencies = EXCLUDED.competencies, fetched_at = EXCLUDED.fetched_at, negative = EXCLUDED.negative
RETURNING fetched_at
`

type UpsertRegistryValidityParams struct {
	EntityType   string     `json:"entity_type"`
	Key          string     `json:"key"`
	KeyFold      string     `json:"key_fold"`
	Status       string     `json:"status"`
	ValidUntil   *time.Time `json:"valid_until"`
	ClassLabel   *string    `json:"class_label"`
	MtomBand     *string    `json:"mtom_band"`
	Competencies []byte     `json:"competencies"`
	Negative     bool       `json:"negative"`
	Since        int64      `json:"since"`
}

// Writes one answer unless the change feed invalidated its key under a
// sequence above since (the cursor read before the fetch): an answer
// that raced an invalidation is never written (no row returned).
func (q *Queries) UpsertRegistryValidity(ctx context.Context, arg UpsertRegistryValidityParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, upsertRegistryValidity,
		arg.EntityType,
		arg.Key,
		arg.KeyFold,
		arg.Status,
		arg.ValidUntil,
		arg.ClassLabel,
		arg.MtomBand,
		arg.Competencies,
		arg.Negative,
		arg.Since,
	)
	var fetched_at time.Time
	err := row.Scan(&fetched_at)
	return fetched_at, err
}
