// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sources.sql

package relational

import (
	"context"
)

const listSourceControls = `-- name: ListSourceControls :many
SELECT id, source_type, instance_id, enabled, reason, actor, changed_at, version, epoch
FROM source_controls
ORDER BY source_type, instance_id NULLS FIRST
`

func (q *Queries) ListSourceControls(ctx context.Context) ([]SourceControl, error) {
	rows, err := q.db.Query(ctx, listSourceControls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SourceControl
	for rows.Next() {
		var i SourceControl
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.InstanceID,
			&i.Enabled,
			&i.Reason,
			&i.Actor,
			&i.ChangedAt,
			&i.Version,
			&i.Epoch,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextSourceControlVersion = `-- name: NextSourceControlVersion :one
SELECT nextval('source_control_version_seq')::bigint AS version
`

func (q *Queries) NextSourceControlVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextSourceControlVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const sourceControlEpoch = `-- name: SourceControlEpoch :one

SELECT epoch FROM source_control_epoch
`

// Source switches (internal/sources).
func (q *Queries) SourceControlEpoch(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, sourceControlEpoch)
	var epoch string
	err := row.Scan(&epoch)
	return epoch, err
}

const upsertSourceControl = `-- name: UpsertSourceControl :one
INSERT INTO source_controls (source_type, instance_id, enabled, reason, actor, version, epoch)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (source_type, instance_id) DO UPDATE
SET enabled = EXCLUDED.enabled,
    reason = EXCLUDED.reason,
    actor = EXCLUDED.actor,
    changed_at = now(),
    version = EXCLUDED.version,
    epoch = EXCLUDED.epoch
RETURNING id, source_type, instance_id, enabled, reason, actor, changed_at, version, epoch
`

type UpsertSourceControlParams struct {
	SourceType string  `json:"source_type"`
	InstanceID *string `json:"instance_id"`
	Enabled    bool    `json:"enabled"`
	Reason     string  `json:"reason"`
	Actor      string  `json:"actor"`
	Version    int64   `json:"version"`
	Epoch      string  `json:"epoch"`
}

func (q *Queries) UpsertSourceControl(ctx context.Context, arg UpsertSourceControlParams) (SourceControl, error) {
	row := q.db.QueryRow(ctx, upsertSourceControl,
		arg.SourceType,
		arg.InstanceID,
		arg.Enabled,
		arg.Reason,
		arg.Actor,
		arg.Version,
		arg.Epoch,
	)
	var i SourceControl
	err := row.Scan(
		&i.ID,
		&i.SourceType,
		&i.InstanceID,
		&i.Enabled,
		&i.Reason,
		&i.Actor,
		&i.ChangedAt,
		&i.Version,
		&i.Epoch,
	)
	return i, err
}
