// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status.sql

package relational

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const statusClaim = `-- name: StatusClaim :many
UPDATE operating_status_notices
SET attempts = attempts + 1, next_at = now() + make_interval(secs => $1::double precision)
WHERE id IN (
    SELECT n.id FROM operating_status_notices n
    WHERE n.state = 'pending' AND n.next_at <= now()
      AND NOT EXISTS (SELECT 1 FROM operating_status_notices e
                      WHERE e.certificate_id = n.certificate_id AND e.state = 'pending' AND e.created_at < n.created_at)
    ORDER BY n.created_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING id, kind, at, certificate_id, reference, attempts
`

type StatusClaimParams struct {
	LeaseS float64 `json:"lease_s"`
	N      int32   `json:"n"`
}

type StatusClaimRow struct {
	ID            pgtype.UUID `json:"id"`
	Kind          string      `json:"kind"`
	At            time.Time   `json:"at"`
	CertificateID string      `json:"certificate_id"`
	Reference     string      `json:"reference"`
	Attempts      int32       `json:"attempts"`
}

func (q *Queries) StatusClaim(ctx context.Context, arg StatusClaimParams) ([]StatusClaimRow, error) {
	rows, err := q.db.Query(ctx, statusClaim, arg.LeaseS, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatusClaimRow
	for rows.Next() {
		var i StatusClaimRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.At,
			&i.CertificateID,
			&i.Reference,
			&i.Attempts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statusDelivered = `-- name: StatusDelivered :one
UPDATE operating_status_notices
SET state = 'delivered', submitted_at = now(), authority_ref = $1, last_error = NULL
WHERE id = $2::uuid AND state = 'pending'
RETURNING reference, kind
`

type StatusDeliveredParams struct {
	AuthorityRef *string     `json:"authority_ref"`
	ID           pgtype.UUID `json:"id"`
}

type StatusDeliveredRow struct {
	Reference string `json:"reference"`
	Kind      string `json:"kind"`
}

func (q *Queries) StatusDelivered(ctx context.Context, arg StatusDeliveredParams) (StatusDeliveredRow, error) {
	row := q.db.QueryRow(ctx, statusDelivered, arg.AuthorityRef, arg.ID)
	var i StatusDeliveredRow
	err := row.Scan(&i.Reference, &i.Kind)
	return i, err
}

const statusFail = `-- name: StatusFail :one
UPDATE operating_status_notices
SET state = 'failed', failed_at = now(), last_error = $1
WHERE id = $2::uuid AND state = 'pending'
RETURNING reference, kind
`

type StatusFailParams struct {
	LastError *string     `json:"last_error"`
	ID        pgtype.UUID `json:"id"`
}

type StatusFailRow struct {
	Reference string `json:"reference"`
	Kind      string `json:"kind"`
}

func (q *Queries) StatusFail(ctx context.Context, arg StatusFailParams) (StatusFailRow, error) {
	row := q.db.QueryRow(ctx, statusFail, arg.LastError, arg.ID)
	var i StatusFailRow
	err := row.Scan(&i.Reference, &i.Kind)
	return i, err
}

const statusInsert = `-- name: StatusInsert :one
INSERT INTO operating_status_notices (kind, at, certificate_id, reference, requested_by)
VALUES ($1, now(), $2, $3, $4)
RETURNING id, kind, at, submitted_at, authority_ref, certificate_id, reference, requested_by, state, attempts, next_at, last_error, failed_at, created_at
`

type StatusInsertParams struct {
	Kind          string `json:"kind"`
	CertificateID string `json:"certificate_id"`
	Reference     string `json:"reference"`
	RequestedBy   string `json:"requested_by"`
}

func (q *Queries) StatusInsert(ctx context.Context, arg StatusInsertParams) (OperatingStatusNotice, error) {
	row := q.db.QueryRow(ctx, statusInsert,
		arg.Kind,
		arg.CertificateID,
		arg.Reference,
		arg.RequestedBy,
	)
	var i OperatingStatusNotice
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.At,
		&i.SubmittedAt,
		&i.AuthorityRef,
		&i.CertificateID,
		&i.Reference,
		&i.RequestedBy,
		&i.State,
		&i.Attempts,
		&i.NextAt,
		&i.LastError,
		&i.FailedAt,
		&i.CreatedAt,
	)
	return i, err
}

const statusNotices = `-- name: StatusNotices :many

SELECT id, kind, at, submitted_at, authority_ref, certificate_id, reference, requested_by, state, attempts, next_at, last_error, failed_at, created_at
FROM operating_status_notices
WHERE certificate_id = $1
ORDER BY created_at DESC, id DESC
LIMIT $2
`

type StatusNoticesParams struct {
	CertificateID string `json:"certificate_id"`
	N             int32  `json:"n"`
}

// Operating-status notices to the authority (internal/status, WP-15;
// Art. 7(6)). Every time is the database clock.
// The notices of a certificate, newest first: what the next notice may
// be follows from the newest that did not fail.
func (q *Queries) StatusNotices(ctx context.Context, arg StatusNoticesParams) ([]OperatingStatusNotice, error) {
	rows, err := q.db.Query(ctx, statusNotices, arg.CertificateID, arg.N)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperatingStatusNotice
	for rows.Next() {
		var i OperatingStatusNotice
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.At,
			&i.SubmittedAt,
			&i.AuthorityRef,
			&i.CertificateID,
			&i.Reference,
			&i.RequestedBy,
			&i.State,
			&i.Attempts,
			&i.NextAt,
			&i.LastError,
			&i.FailedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statusRetry = `-- name: StatusRetry :execrows
UPDATE operating_status_notices
SET next_at = now() + make_interval(secs => $1::double precision), last_error = $2
WHERE id = $3::uuid AND state = 'pending'
`

type StatusRetryParams struct {
	BackoffS  float64     `json:"backoff_s"`
	LastError *string     `json:"last_error"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) StatusRetry(ctx context.Context, arg StatusRetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, statusRetry, arg.BackoffS, arg.LastError, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
