#!/usr/bin/env bash
# Regenerates every committed generated Go file from its source:
#   api/openapi.yaml -> internal/national/gen/server.gen.go   (oapi-codegen, api/oapi-codegen.server.yaml)
#   api/openapi.yaml -> internal/national/client/client.gen.go (oapi-codegen, api/oapi-codegen.client.yaml)
# sqlc (internal/store/*) joins with WP-1 and the standard interfaces
# (internal/stdapi) with WP-3. web/src/api/types.ts is generated by
# `pnpm gen:api` in web/ (the Makefile's generate target runs both).
#
# oapi-codegen runs through `go tool`, at the version go.mod's tool
# directive and go.sum pin, so it needs no network once the module
# cache holds it. OUT_DIR (optional) writes into a scratch tree instead
# of the repository, for scripts/check-generated.sh.
set -euo pipefail

GO=${GO:-go}
root=$(cd "$(dirname "$0")/.." && pwd)
out=${OUT_DIR:-$root}
cd "$root"

gen() {
  local config=$1 target=$2
  mkdir -p "$out/$(dirname "$target")"
  "$GO" tool oapi-codegen -config "$config" -o "$out/$target" api/openapi.yaml
  echo "generated: $target"
}

gen api/oapi-codegen.server.yaml internal/national/gen/server.gen.go
gen api/oapi-codegen.client.yaml internal/national/client/client.gen.go
