#!/usr/bin/env bash
# Regenerates every committed generated Go file from its source:
#   api/openapi.yaml -> internal/national/gen/server.gen.go   (oapi-codegen, api/oapi-codegen.server.yaml)
#   api/openapi.yaml -> internal/national/client/client.gen.go (oapi-codegen, api/oapi-codegen.client.yaml)
#   sqlc.yaml        -> internal/store/relational, internal/store/timeseries
#                       (sqlc, from the migration trees and internal/store/queries)
# The standard interfaces (internal/stdapi) join with WP-3. web/src/api/types.ts is generated by
# `pnpm gen:api` in web/ (the Makefile's generate target runs both).
#
# oapi-codegen runs through `go tool`, at the version go.mod's tool
# directive and go.sum pin, so it needs no network once the module
# cache holds it. OUT_DIR (optional) writes into a scratch tree instead
# of the repository, for scripts/check-generated.sh.
set -euo pipefail

# Pinned here and nowhere else; `go run` takes it from the module cache
# once downloaded (sqlc is not a go.mod tool: its dependency tree would
# enter the module's build list).
SQLC_VERSION=v1.31.1

GO=${GO:-go}
root=$(cd "$(dirname "$0")/.." && pwd)
out=${OUT_DIR:-$root}
cd "$root"

gen() {
  local config=$1 target=$2
  mkdir -p "$out/$(dirname "$target")"
  "$GO" tool oapi-codegen -config "$config" -o "$out/$target" api/openapi.yaml
  echo "generated: $target"
}

gen api/oapi-codegen.server.yaml internal/national/gen/server.gen.go
gen api/oapi-codegen.client.yaml internal/national/client/client.gen.go

# sqlc resolves every path in sqlc.yaml against the file's directory, so
# a scratch run copies the inputs beside a copy of the file.
sqlc_config=sqlc.yaml
if [ "$out" != "$root" ]; then
  for d in migrations internal/store/queries; do
    mkdir -p "$out/$d"
    cp -R "$d/." "$out/$d/"
  done
  cp sqlc.yaml "$out/sqlc.yaml"
  sqlc_config="$out/sqlc.yaml"
fi
"$GO" run "github.com/sqlc-dev/sqlc/cmd/sqlc@${SQLC_VERSION}" generate -f "$sqlc_config"
echo "generated: internal/store/relational, internal/store/timeseries (sqlc ${SQLC_VERSION})"
