// Package authclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package authclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ClassLabel.
const (
	C0 ClassLabel = "C0"
	C1 ClassLabel = "C1"
	C2 ClassLabel = "C2"
	C3 ClassLabel = "C3"
	C4 ClassLabel = "C4"
	C5 ClassLabel = "C5"
	C6 ClassLabel = "C6"
)

// Valid indicates whether the value is a known member of the ClassLabel enum.
func (e ClassLabel) Valid() bool {
	switch e {
	case C0:
		return true
	case C1:
		return true
	case C2:
		return true
	case C3:
		return true
	case C4:
		return true
	case C5:
		return true
	case C6:
		return true
	default:
		return false
	}
}

// Defines values for RegistryChangeEntityType.
const (
	Operator RegistryChangeEntityType = "operator"
	Pilot    RegistryChangeEntityType = "pilot"
	Uas      RegistryChangeEntityType = "uas"
)

// Valid indicates whether the value is a known member of the RegistryChangeEntityType enum.
func (e RegistryChangeEntityType) Valid() bool {
	switch e {
	case Operator:
		return true
	case Pilot:
		return true
	case Uas:
		return true
	default:
		return false
	}
}

// Defines values for RegistryPurpose.
const (
	Authorisation  RegistryPurpose = "authorisation"
	Identification RegistryPurpose = "identification"
)

// Valid indicates whether the value is a known member of the RegistryPurpose enum.
func (e RegistryPurpose) Valid() bool {
	switch e {
	case Authorisation:
		return true
	case Identification:
		return true
	default:
		return false
	}
}

// Defines values for RegistryStatus.
const (
	RegistryStatusActive    RegistryStatus = "active"
	RegistryStatusExpired   RegistryStatus = "expired"
	RegistryStatusRevoked   RegistryStatus = "revoked"
	RegistryStatusSuspended RegistryStatus = "suspended"
)

// Valid indicates whether the value is a known member of the RegistryStatus enum.
func (e RegistryStatus) Valid() bool {
	switch e {
	case RegistryStatusActive:
		return true
	case RegistryStatusExpired:
		return true
	case RegistryStatusRevoked:
		return true
	case RegistryStatusSuspended:
		return true
	default:
		return false
	}
}

// Defines values for RegistryValidityStatus.
const (
	RegistryValidityStatusRevoked   RegistryValidityStatus = "revoked"
	RegistryValidityStatusSuspended RegistryValidityStatus = "suspended"
	RegistryValidityStatusUnknown   RegistryValidityStatus = "unknown"
	RegistryValidityStatusValid     RegistryValidityStatus = "valid"
)

// Valid indicates whether the value is a known member of the RegistryValidityStatus enum.
func (e RegistryValidityStatus) Valid() bool {
	switch e {
	case RegistryValidityStatusRevoked:
		return true
	case RegistryValidityStatusSuspended:
		return true
	case RegistryValidityStatusUnknown:
		return true
	case RegistryValidityStatusValid:
		return true
	default:
		return false
	}
}

// Defines values for SourceType.
const (
	AnspFeed   SourceType = "ansp_feed"
	DirectRid  SourceType = "direct_rid"
	NetworkRid SourceType = "network_rid"
)

// Valid indicates whether the value is a known member of the SourceType enum.
func (e SourceType) Valid() bool {
	switch e {
	case AnspFeed:
		return true
	case DirectRid:
		return true
	case NetworkRid:
		return true
	default:
		return false
	}
}

// CertificateID defines model for CertificateID.
type CertificateID = string

// ClassLabel defines model for ClassLabel.
type ClassLabel string

// CompetencyValidity defines model for CompetencyValidity.
type CompetencyValidity struct {
	Competency string    `json:"competency"`
	ValidUntil time.Time `json:"valid_until"`
}

// FieldProblem defines model for FieldProblem.
type FieldProblem struct {
	// Field JSON path or parameter name, as core.FieldError writes it.
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

// OperatorValidity defines model for OperatorValidity.
type OperatorValidity struct {
	// RegistrationNumber The public part of the number asked (regnum.PublicPart); a secret part sent with it is never echoed or recorded.
	RegistrationNumber string                 `json:"registration_number"`
	Status             RegistryValidityStatus `json:"status"`
	ValidUntil         *time.Time             `json:"valid_until,omitempty"`
}

// PilotValidity defines model for PilotValidity.
type PilotValidity struct {
	Competencies []CompetencyValidity `json:"competencies"`

	// Pilot As asked.
	Pilot  string                 `json:"pilot"`
	Status RegistryValidityStatus `json:"status"`
}

// Problem RFC 9457 problem details with the field-error extension of
// decision M28; the shape of uspace-lab `schemas/common/problem/v1`.
// `errors` is capped at 100 entries; `truncated` is true when it
// was cut.
type Problem struct {
	Detail    *string        `json:"detail,omitempty"`
	Errors    []FieldProblem `json:"errors"`
	Instance  *string        `json:"instance,omitempty"`
	Status    int            `json:"status"`
	Title     string         `json:"title"`
	Truncated *bool          `json:"truncated,omitempty"`

	// Type `https://schemas.uspace.ge/problems/<slug>`, slug = the counter or refusal name.
	Type string `json:"type"`
}

// RegistryChange defines model for RegistryChange.
type RegistryChange struct {
	At         time.Time                `json:"at"`
	EntityId   string                   `json:"entity_id"`
	EntityType RegistryChangeEntityType `json:"entity_type"`

	// PublicKey The registration number, the serial or the pilot id.
	PublicKey string         `json:"public_key"`
	Seq       int64          `json:"seq"`
	Status    RegistryStatus `json:"status"`
}

// RegistryChangeEntityType defines model for RegistryChange.EntityType.
type RegistryChangeEntityType string

// RegistryChangePage defines model for RegistryChangePage.
type RegistryChangePage struct {
	Changes []RegistryChange `json:"changes"`

	// NextSince Pass as since for the next page.
	NextSince int64 `json:"next_since"`
}

// RegistryPurpose defines model for RegistryPurpose.
type RegistryPurpose string

// RegistryStatus defines model for RegistryStatus.
type RegistryStatus string

// RegistryValidateBatch defines model for RegistryValidateBatch.
type RegistryValidateBatch struct {
	Items []RegistryValidateItem `json:"items"`
}

// RegistryValidateItem At least one key.
type RegistryValidateItem struct {
	Operator *string `json:"operator,omitempty"`
	Pilot    *string `json:"pilot,omitempty"`
	Serial   *string `json:"serial,omitempty"`
}

// RegistryValidity One answer per key asked; status only.
type RegistryValidity struct {
	Operator *OperatorValidity `json:"operator,omitempty"`
	Pilot    *PilotValidity    `json:"pilot,omitempty"`
	Uas      *UASValidity      `json:"uas,omitempty"`
}

// RegistryValidityList defines model for RegistryValidityList.
type RegistryValidityList struct {
	Results []RegistryValidity `json:"results"`
}

// RegistryValidityStatus defines model for RegistryValidityStatus.
type RegistryValidityStatus string

// SourceType The adapter type (04 §2 `source`), one per adapter process.
type SourceType string

// UASValidity defines model for UASValidity.
type UASValidity struct {
	ClassLabel *ClassLabel `json:"class_label,omitempty"`

	// MtomBand The MTOM band of REGISTRY_MTOM_BANDS_G: under_<g>g, or from_<g>g above the last bound.
	MtomBand *string `json:"mtom_band,omitempty"`

	// Serial As asked.
	Serial string                 `json:"serial"`
	Status RegistryValidityStatus `json:"status"`
}

// ListRegistryChangesParams defines parameters for ListRegistryChanges.
type ListRegistryChangesParams struct {
	Since       *int64  `form:"since,omitempty" json:"since,omitempty"`
	Limit       *int    `form:"limit,omitempty" json:"limit,omitempty"`
	IfNoneMatch *string `json:"If-None-Match,omitempty"`
}

// ValidateRegistryParams defines parameters for ValidateRegistry.
type ValidateRegistryParams struct {
	Purpose  RegistryPurpose `form:"purpose" json:"purpose"`
	Operator *string         `form:"operator,omitempty" json:"operator,omitempty"`
	Serial   *string         `form:"serial,omitempty" json:"serial,omitempty"`
	Pilot    *string         `form:"pilot,omitempty" json:"pilot,omitempty"`
}

// ValidateRegistryBatchParams defines parameters for ValidateRegistryBatch.
type ValidateRegistryBatchParams struct {
	Purpose RegistryPurpose `form:"purpose" json:"purpose"`
}

// ValidateRegistryBatchJSONRequestBody defines body for ValidateRegistryBatch for application/json ContentType.
type ValidateRegistryBatchJSONRequestBody = RegistryValidateBatch

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListRegistryChanges The status change feed (F8), ids and statuses only
	//
	// Changes after `since` in sequence order, for cache
	// invalidation. `next_since` is the last sequence of the page;
	// an `ETag` names the page, and `If-None-Match` with it answers
	// 304 while nothing newer exists.
	//
	// Corresponds with GET /v1/registry/changes (the `ListRegistryChanges` operationId).
	ListRegistryChanges(ctx context.Context, params *ListRegistryChangesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ValidateRegistry Validity of an operator, a UAS and a pilot (F8)
	//
	// Status only, per entity: `valid`, `suspended`, `revoked` or
	// `unknown`, the end of validity, the class label and MTOM band of
	// a UAS and the competency set of a pilot. No name, address, phone
	// or e-mail: the response schema has no such property, and a test
	// fails if one appears. An expired registration answers `revoked`
	// with its `valid_until` in the past. `operator` is compared on its
	// public part (an EU secret suffix is removed, G-04); `serial`
	// exactly, else on its ASCII fold when one aircraft has it (G-05);
	// `pilot` is the remote pilot's registry id. Every call is an
	// events row with the client and the purpose.
	//
	// Corresponds with GET /v1/registry/validate (the `ValidateRegistry` operationId).
	ValidateRegistry(ctx context.Context, params *ValidateRegistryParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ValidateRegistryBatchWithBody Validity of up to 100 entities (F8)
	//
	// The GET's answer for each item, in order; one events row for the batch.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/registry/validate (the `ValidateRegistryBatch` operationId).
	ValidateRegistryBatchWithBody(ctx context.Context, params *ValidateRegistryBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ValidateRegistryBatch Validity of up to 100 entities (F8)
	//
	// The GET's answer for each item, in order; one events row for the batch.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/registry/validate (the `ValidateRegistryBatch` operationId).
	ValidateRegistryBatch(ctx context.Context, params *ValidateRegistryBatchParams, body ValidateRegistryBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListRegistryChanges The status change feed (F8), ids and statuses only
//
// Changes after `since` in sequence order, for cache
// invalidation. `next_since` is the last sequence of the page;
// an `ETag` names the page, and `If-None-Match` with it answers
// 304 while nothing newer exists.
//
// Corresponds with GET /v1/registry/changes (the `ListRegistryChanges` operationId).
func (c *Client) ListRegistryChanges(ctx context.Context, params *ListRegistryChangesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListRegistryChangesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ValidateRegistry Validity of an operator, a UAS and a pilot (F8)
//
// Status only, per entity: `valid`, `suspended`, `revoked` or
// `unknown`, the end of validity, the class label and MTOM band of
// a UAS and the competency set of a pilot. No name, address, phone
// or e-mail: the response schema has no such property, and a test
// fails if one appears. An expired registration answers `revoked`
// with its `valid_until` in the past. `operator` is compared on its
// public part (an EU secret suffix is removed, G-04); `serial`
// exactly, else on its ASCII fold when one aircraft has it (G-05);
// `pilot` is the remote pilot's registry id. Every call is an
// events row with the client and the purpose.
//
// Corresponds with GET /v1/registry/validate (the `ValidateRegistry` operationId).
func (c *Client) ValidateRegistry(ctx context.Context, params *ValidateRegistryParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidateRegistryRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ValidateRegistryBatchWithBody Validity of up to 100 entities (F8)
//
// The GET's answer for each item, in order; one events row for the batch.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/registry/validate (the `ValidateRegistryBatch` operationId).
func (c *Client) ValidateRegistryBatchWithBody(ctx context.Context, params *ValidateRegistryBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidateRegistryBatchRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ValidateRegistryBatch Validity of up to 100 entities (F8)
//
// The GET's answer for each item, in order; one events row for the batch.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/registry/validate (the `ValidateRegistryBatch` operationId).
func (c *Client) ValidateRegistryBatch(ctx context.Context, params *ValidateRegistryBatchParams, body ValidateRegistryBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewValidateRegistryBatchRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListRegistryChangesRequest constructs an http.Request for the ListRegistryChanges method
func NewListRegistryChangesRequest(server string, params *ListRegistryChangesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/registry/changes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Since != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "since", *params.Since, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.IfNoneMatch != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithOptions("simple", false, "If-None-Match", *params.IfNoneMatch, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
			if err != nil {
				return nil, err
			}

			req.Header.Set("If-None-Match", headerParam0)
		}

	}

	return req, nil
}

// NewValidateRegistryRequest constructs an http.Request for the ValidateRegistry method
func NewValidateRegistryRequest(server string, params *ValidateRegistryParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/registry/validate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "purpose", params.Purpose, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Operator != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "operator", *params.Operator, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Serial != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "serial", *params.Serial, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Pilot != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pilot", *params.Pilot, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewValidateRegistryBatchRequest calls the generic ValidateRegistryBatch builder with application/json body
func NewValidateRegistryBatchRequest(server string, params *ValidateRegistryBatchParams, body ValidateRegistryBatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewValidateRegistryBatchRequestWithBody(server, params, "application/json", bodyReader)
}

// NewValidateRegistryBatchRequestWithBody constructs an http.Request for the ValidateRegistryBatch method, with any body, and a specified content type
func NewValidateRegistryBatchRequestWithBody(server string, params *ValidateRegistryBatchParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/registry/validate")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "purpose", params.Purpose, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListRegistryChangesWithResponse The status change feed (F8), ids and statuses only
	//
	// Changes after `since` in sequence order, for cache
	// invalidation. `next_since` is the last sequence of the page;
	// an `ETag` names the page, and `If-None-Match` with it answers
	// 304 while nothing newer exists.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/registry/changes (the `ListRegistryChanges` operationId).
	ListRegistryChangesWithResponse(ctx context.Context, params *ListRegistryChangesParams, reqEditors ...RequestEditorFn) (*ListRegistryChangesResponse, error)

	// ValidateRegistryWithResponse Validity of an operator, a UAS and a pilot (F8)
	//
	// Status only, per entity: `valid`, `suspended`, `revoked` or
	// `unknown`, the end of validity, the class label and MTOM band of
	// a UAS and the competency set of a pilot. No name, address, phone
	// or e-mail: the response schema has no such property, and a test
	// fails if one appears. An expired registration answers `revoked`
	// with its `valid_until` in the past. `operator` is compared on its
	// public part (an EU secret suffix is removed, G-04); `serial`
	// exactly, else on its ASCII fold when one aircraft has it (G-05);
	// `pilot` is the remote pilot's registry id. Every call is an
	// events row with the client and the purpose.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /v1/registry/validate (the `ValidateRegistry` operationId).
	ValidateRegistryWithResponse(ctx context.Context, params *ValidateRegistryParams, reqEditors ...RequestEditorFn) (*ValidateRegistryResponse, error)

	// ValidateRegistryBatchWithBodyWithResponse Validity of up to 100 entities (F8)
	//
	// The GET's answer for each item, in order; one events row for the batch.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/registry/validate (the `ValidateRegistryBatch` operationId).
	ValidateRegistryBatchWithBodyWithResponse(ctx context.Context, params *ValidateRegistryBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ValidateRegistryBatchResponse, error)

	// ValidateRegistryBatchWithResponse Validity of up to 100 entities (F8)
	//
	// The GET's answer for each item, in order; one events row for the batch.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/registry/validate (the `ValidateRegistryBatch` operationId).
	ValidateRegistryBatchWithResponse(ctx context.Context, params *ValidateRegistryBatchParams, body ValidateRegistryBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*ValidateRegistryBatchResponse, error)
}

// ListRegistryChangesResponse200Headers the declared response headers of an HTTP 200 response for ListRegistryChanges
type ListRegistryChangesResponse200Headers struct {
	ETag *string
}

// ListRegistryChangesResponse304Headers the declared response headers of an HTTP 304 response for ListRegistryChanges
type ListRegistryChangesResponse304Headers struct {
	ETag *string
}

type ListRegistryChangesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RegistryChangePage
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *ListRegistryChangesResponse200Headers
	// Headers304 the parsed response headers for an HTTP 304 response
	Headers304 *ListRegistryChangesResponse304Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListRegistryChangesResponse) GetJSON200() *RegistryChangePage {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r ListRegistryChangesResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r ListRegistryChangesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListRegistryChangesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListRegistryChangesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListRegistryChangesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ValidateRegistryResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RegistryValidity
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ValidateRegistryResponse) GetJSON200() *RegistryValidity {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r ValidateRegistryResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r ValidateRegistryResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ValidateRegistryResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ValidateRegistryResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ValidateRegistryResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ValidateRegistryBatchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *RegistryValidityList
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ValidateRegistryBatchResponse) GetJSON200() *RegistryValidityList {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r ValidateRegistryBatchResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r ValidateRegistryBatchResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ValidateRegistryBatchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ValidateRegistryBatchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ValidateRegistryBatchResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListRegistryChangesWithResponse The status change feed (F8), ids and statuses only
//
// Changes after `since` in sequence order, for cache
// invalidation. `next_since` is the last sequence of the page;
// an `ETag` names the page, and `If-None-Match` with it answers
// 304 while nothing newer exists.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/registry/changes (the `ListRegistryChanges` operationId).
func (c *ClientWithResponses) ListRegistryChangesWithResponse(ctx context.Context, params *ListRegistryChangesParams, reqEditors ...RequestEditorFn) (*ListRegistryChangesResponse, error) {
	rsp, err := c.ListRegistryChanges(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListRegistryChangesResponse(rsp)
}

// ValidateRegistryWithResponse Validity of an operator, a UAS and a pilot (F8)
//
// Status only, per entity: `valid`, `suspended`, `revoked` or
// `unknown`, the end of validity, the class label and MTOM band of
// a UAS and the competency set of a pilot. No name, address, phone
// or e-mail: the response schema has no such property, and a test
// fails if one appears. An expired registration answers `revoked`
// with its `valid_until` in the past. `operator` is compared on its
// public part (an EU secret suffix is removed, G-04); `serial`
// exactly, else on its ASCII fold when one aircraft has it (G-05);
// `pilot` is the remote pilot's registry id. Every call is an
// events row with the client and the purpose.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /v1/registry/validate (the `ValidateRegistry` operationId).
func (c *ClientWithResponses) ValidateRegistryWithResponse(ctx context.Context, params *ValidateRegistryParams, reqEditors ...RequestEditorFn) (*ValidateRegistryResponse, error) {
	rsp, err := c.ValidateRegistry(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidateRegistryResponse(rsp)
}

// ValidateRegistryBatchWithBodyWithResponse Validity of up to 100 entities (F8)
//
// The GET's answer for each item, in order; one events row for the batch.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/registry/validate (the `ValidateRegistryBatch` operationId).
func (c *ClientWithResponses) ValidateRegistryBatchWithBodyWithResponse(ctx context.Context, params *ValidateRegistryBatchParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ValidateRegistryBatchResponse, error) {
	rsp, err := c.ValidateRegistryBatchWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidateRegistryBatchResponse(rsp)
}

// ValidateRegistryBatchWithResponse Validity of up to 100 entities (F8)
//
// The GET's answer for each item, in order; one events row for the batch.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/registry/validate (the `ValidateRegistryBatch` operationId).
func (c *ClientWithResponses) ValidateRegistryBatchWithResponse(ctx context.Context, params *ValidateRegistryBatchParams, body ValidateRegistryBatchJSONRequestBody, reqEditors ...RequestEditorFn) (*ValidateRegistryBatchResponse, error) {
	rsp, err := c.ValidateRegistryBatch(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseValidateRegistryBatchResponse(rsp)
}

// ParseListRegistryChangesResponse parses an HTTP response from a ListRegistryChangesWithResponse call
func ParseListRegistryChangesResponse(rsp *http.Response) (*ListRegistryChangesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListRegistryChangesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RegistryChangePage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case rsp.StatusCode == 304:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers ListRegistryChangesResponse200Headers
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		response.Headers200 = &headers
	case rsp.StatusCode == 304:
		var headers ListRegistryChangesResponse304Headers
		if values := rsp.Header.Values("ETag"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "ETag", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.ETag = &value
		}
		response.Headers304 = &headers
	}

	return response, nil
}

// ParseValidateRegistryResponse parses an HTTP response from a ValidateRegistryWithResponse call
func ParseValidateRegistryResponse(rsp *http.Response) (*ValidateRegistryResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ValidateRegistryResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RegistryValidity
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseValidateRegistryBatchResponse parses an HTTP response from a ValidateRegistryBatchWithResponse call
func ParseValidateRegistryBatchResponse(rsp *http.Response) (*ValidateRegistryBatchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ValidateRegistryBatchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RegistryValidityList
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
